-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: rpcv2Cbor

local types = require("rpcV2Protocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.rpcv2")
local protocol = protocol_mod.new_cbor()

local service = schema.service({
    id = shape_id.from("smithy.protocoltests.rpcv2Cbor", "RpcV2Protocol"),
    version = "2020-07-14",
    traits = {},
})

describe("RpcV2CborLists request", function()
    it("RpcV2CborLists", function()
        local input = {
            stringList = {
            "foo",
            "bar",
        },
            stringSet = {
            "foo",
            "bar",
        },
            integerList = {
            1,
            2,
        },
            booleanList = {
            true,
            false,
        },
            timestampList = {
            1398796238,
            1398796238,
        },
            enumList = {
            "Foo",
            "0",
        },
            intEnumList = {
            1,
            2,
        },
            nestedStringList = {
            {
            "foo",
            "bar",
        },
            {
            "baz",
            "qux",
        },
        },
            structureList = {
            {
            a = "1",
            b = "2",
        },
            {
            a = "3",
            b = "4",
        },
        },
            blobList = {
            "foo",
            "bar",
        },
        }
        local operation = schema.operation({
            id = shape_id.from("smithy.protocoltests.rpcv2Cbor", "RpcV2CborLists"),
            input = types.RpcV2CborListsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/service/RpcV2Protocol/operation/RpcV2CborLists" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/service/RpcV2Protocol/operation/RpcV2CborLists")
        h.assert_header(request, "Accept", "application/cbor")
        h.assert_header(request, "Content-Type", "application/cbor")
        h.assert_header(request, "smithy-protocol", "rpc-v2-cbor")
        local body_str = h.read_body(request.body)
        h.assert_cbor_eq(body_str, h.base64_decode([[v2pzdHJpbmdMaXN0gmNmb29jYmFyaXN0cmluZ1NldIJjZm9vY2JhcmtpbnRlZ2VyTGlzdIIBAmtib29sZWFuTGlzdIL19G10aW1lc3RhbXBMaXN0gsH7QdTX+/OAAADB+0HU1/vzgAAAaGVudW1MaXN0gmNGb29hMGtpbnRFbnVtTGlzdIIBAnBuZXN0ZWRTdHJpbmdMaXN0goJjZm9vY2JhcoJjYmF6Y3F1eG1zdHJ1Y3R1cmVMaXN0gqJhYWExYWJhMqJhYWEzYWJhNGhibG9iTGlzdIJDZm9vQ2Jhcv8=]]))
    end)

    it("RpcV2CborListsEmpty", function()
        local input = {
            stringList = {},
        }
        local operation = schema.operation({
            id = shape_id.from("smithy.protocoltests.rpcv2Cbor", "RpcV2CborLists"),
            input = types.RpcV2CborListsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/service/RpcV2Protocol/operation/RpcV2CborLists" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/service/RpcV2Protocol/operation/RpcV2CborLists")
        h.assert_header(request, "Accept", "application/cbor")
        h.assert_header(request, "Content-Type", "application/cbor")
        h.assert_header(request, "smithy-protocol", "rpc-v2-cbor")
        local body_str = h.read_body(request.body)
        h.assert_cbor_eq(body_str, h.base64_decode([[v2pzdHJpbmdMaXN0n///]]))
    end)

    it("RpcV2CborListsEmptyUsingDefiniteLength", function()
        local input = {
            stringList = {},
        }
        local operation = schema.operation({
            id = shape_id.from("smithy.protocoltests.rpcv2Cbor", "RpcV2CborLists"),
            input = types.RpcV2CborListsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/service/RpcV2Protocol/operation/RpcV2CborLists" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/service/RpcV2Protocol/operation/RpcV2CborLists")
        h.assert_header(request, "Accept", "application/cbor")
        h.assert_header(request, "Content-Type", "application/cbor")
        h.assert_header(request, "smithy-protocol", "rpc-v2-cbor")
        local body_str = h.read_body(request.body)
        h.assert_cbor_eq(body_str, h.base64_decode([[oWpzdHJpbmdMaXN0gA==]]))
    end)

end)
