-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: rpcv2Cbor

local types = require("rpcV2Protocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.rpcv2")
local protocol = protocol_mod.new_cbor()

local service = schema.service({
    id = shape_id.from("smithy.protocoltests.rpcv2Cbor", "RpcV2Protocol"),
    version = "2020-07-14",
    traits = {},
})

describe("RpcV2CborSparseMaps request", function()
    it("RpcV2CborSparseMaps", function()
        local input = {
            sparseStructMap = {
            foo = {
            hi = "there",
        },
            baz = {
            hi = "bye",
        },
        },
        }
        local operation = schema.operation({
            id = shape_id.from("smithy.protocoltests.rpcv2Cbor", "RpcV2CborSparseMaps"),
            input = types.RpcV2CborSparseMapsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/service/RpcV2Protocol/operation/RpcV2CborSparseMaps" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/service/RpcV2Protocol/operation/RpcV2CborSparseMaps")
        h.assert_header(request, "Accept", "application/cbor")
        h.assert_header(request, "Content-Type", "application/cbor")
        h.assert_header(request, "smithy-protocol", "rpc-v2-cbor")
        local body_str = h.read_body(request.body)
        h.assert_cbor_eq(body_str, h.base64_decode([[v29zcGFyc2VTdHJ1Y3RNYXC/Y2Zvb79iaGlldGhlcmX/Y2Jher9iaGljYnll////]]))
    end)

    it("RpcV2CborSerializesNullMapValues", function()
        local input = {
            sparseBooleanMap = {
            x = nil,
        },
            sparseNumberMap = {
            x = nil,
        },
            sparseStringMap = {
            x = nil,
        },
            sparseStructMap = {
            x = nil,
        },
        }
        local operation = schema.operation({
            id = shape_id.from("smithy.protocoltests.rpcv2Cbor", "RpcV2CborSparseMaps"),
            input = types.RpcV2CborSparseMapsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/service/RpcV2Protocol/operation/RpcV2CborSparseMaps" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/service/RpcV2Protocol/operation/RpcV2CborSparseMaps")
        h.assert_header(request, "Accept", "application/cbor")
        h.assert_header(request, "Content-Type", "application/cbor")
        h.assert_header(request, "smithy-protocol", "rpc-v2-cbor")
        local body_str = h.read_body(request.body)
        h.assert_cbor_eq(body_str, h.base64_decode([[v3BzcGFyc2VCb29sZWFuTWFwv2F49v9vc3BhcnNlTnVtYmVyTWFwv2F49v9vc3BhcnNlU3RyaW5nTWFwv2F49v9vc3BhcnNlU3RydWN0TWFwv2F49v//]]))
    end)

    it("RpcV2CborSerializesSparseSetMap", function()
        local input = {
            sparseSetMap = {
            x = {},
            y = {
            "a",
            "b",
        },
        },
        }
        local operation = schema.operation({
            id = shape_id.from("smithy.protocoltests.rpcv2Cbor", "RpcV2CborSparseMaps"),
            input = types.RpcV2CborSparseMapsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/service/RpcV2Protocol/operation/RpcV2CborSparseMaps" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/service/RpcV2Protocol/operation/RpcV2CborSparseMaps")
        h.assert_header(request, "Accept", "application/cbor")
        h.assert_header(request, "Content-Type", "application/cbor")
        h.assert_header(request, "smithy-protocol", "rpc-v2-cbor")
        local body_str = h.read_body(request.body)
        h.assert_cbor_eq(body_str, h.base64_decode([[v2xzcGFyc2VTZXRNYXC/YXif/2F5n2FhYWL///8=]]))
    end)

    it("RpcV2CborSerializesSparseSetMapAndRetainsNull", function()
        local input = {
            sparseSetMap = {
            x = {},
            y = {
            "a",
            "b",
        },
            z = nil,
        },
        }
        local operation = schema.operation({
            id = shape_id.from("smithy.protocoltests.rpcv2Cbor", "RpcV2CborSparseMaps"),
            input = types.RpcV2CborSparseMapsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/service/RpcV2Protocol/operation/RpcV2CborSparseMaps" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/service/RpcV2Protocol/operation/RpcV2CborSparseMaps")
        h.assert_header(request, "Accept", "application/cbor")
        h.assert_header(request, "Content-Type", "application/cbor")
        h.assert_header(request, "smithy-protocol", "rpc-v2-cbor")
        local body_str = h.read_body(request.body)
        h.assert_cbor_eq(body_str, h.base64_decode([[v2xzcGFyc2VTZXRNYXC/YXif/2F5n2FhYWL/YXr2//8=]]))
    end)

    it("RpcV2CborSerializesZeroValuesInSparseMaps", function()
        local input = {
            sparseNumberMap = {
            x = 0,
        },
            sparseBooleanMap = {
            x = false,
        },
        }
        local operation = schema.operation({
            id = shape_id.from("smithy.protocoltests.rpcv2Cbor", "RpcV2CborSparseMaps"),
            input = types.RpcV2CborSparseMapsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/service/RpcV2Protocol/operation/RpcV2CborSparseMaps" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/service/RpcV2Protocol/operation/RpcV2CborSparseMaps")
        h.assert_header(request, "Accept", "application/cbor")
        h.assert_header(request, "Content-Type", "application/cbor")
        h.assert_header(request, "smithy-protocol", "rpc-v2-cbor")
        local body_str = h.read_body(request.body)
        h.assert_cbor_eq(body_str, h.base64_decode([[v29zcGFyc2VOdW1iZXJNYXC/YXgA/3BzcGFyc2VCb29sZWFuTWFwv2F49P//]]))
    end)

end)
