-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: rpcv2Cbor

local types = require("rpcV2Protocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.rpcv2")
local protocol = protocol_mod.new_cbor()

local service = schema.service({
    id = shape_id.from("smithy.protocoltests.rpcv2Cbor", "RpcV2Protocol"),
    version = "2020-07-14",
    traits = {},
})

describe("RpcV2CborLists response", function()
    it("RpcV2CborLists", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/cbor",
                ["smithy-protocol"] = "rpc-v2-cbor",
            },
            body = http.string_reader(h.base64_decode([[v2pzdHJpbmdMaXN0n2Nmb29jYmFy/2lzdHJpbmdTZXSfY2Zvb2NiYXL/a2ludGVnZXJMaXN0nwEC/2tib29sZWFuTGlzdJ/19P9tdGltZXN0YW1wTGlzdJ/B+0HU1/vzgAAAwftB1Nf784AAAP9oZW51bUxpc3SfY0Zvb2Ew/2tpbnRFbnVtTGlzdJ8BAv9wbmVzdGVkU3RyaW5nTGlzdJ+fY2Zvb2NiYXL/n2NiYXpjcXV4//9tc3RydWN0dXJlTGlzdJ+/YWFhMWFiYTL/v2FhYTNhYmE0//9oYmxvYkxpc3SfQ2Zvb0NiYXL//w==]])),
        }
        local operation = schema.operation({
            id = shape_id.from("smithy.protocoltests.rpcv2Cbor", "RpcV2CborLists"),
            input = schema.new({ type = "structure" }),
            output = types.RpcV2CborListsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            stringList = {
            "foo",
            "bar",
        },
            stringSet = {
            "foo",
            "bar",
        },
            integerList = {
            1,
            2,
        },
            booleanList = {
            true,
            false,
        },
            timestampList = {
            1398796238,
            1398796238,
        },
            enumList = {
            "Foo",
            "0",
        },
            intEnumList = {
            1,
            2,
        },
            nestedStringList = {
            {
            "foo",
            "bar",
        },
            {
            "baz",
            "qux",
        },
        },
            structureList = {
            {
            a = "1",
            b = "2",
        },
            {
            a = "3",
            b = "4",
        },
        },
            blobList = {
            "foo",
            "bar",
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("RpcV2CborListsEmpty", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/cbor",
                ["smithy-protocol"] = "rpc-v2-cbor",
            },
            body = http.string_reader(h.base64_decode([[v2pzdHJpbmdMaXN0n///]])),
        }
        local operation = schema.operation({
            id = shape_id.from("smithy.protocoltests.rpcv2Cbor", "RpcV2CborLists"),
            input = schema.new({ type = "structure" }),
            output = types.RpcV2CborListsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            stringList = {},
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("RpcV2CborIndefiniteStringInsideIndefiniteListCanDeserialize", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/cbor",
                ["smithy-protocol"] = "rpc-v2-cbor",
            },
            body = http.string_reader(h.base64_decode([[v2pzdHJpbmdMaXN0n394HUFuIGV4YW1wbGUgaW5kZWZpbml0ZSBzdHJpbmcsdyB3aGljaCB3aWxsIGJlIGNodW5rZWQsbiBvbiBlYWNoIGNvbW1h/394NUFub3RoZXIgZXhhbXBsZSBpbmRlZmluaXRlIHN0cmluZyB3aXRoIG9ubHkgb25lIGNodW5r/3ZUaGlzIGlzIGEgcGxhaW4gc3RyaW5n//8=]])),
        }
        local operation = schema.operation({
            id = shape_id.from("smithy.protocoltests.rpcv2Cbor", "RpcV2CborLists"),
            input = schema.new({ type = "structure" }),
            output = types.RpcV2CborListsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            stringList = {
            "An example indefinite string, which will be chunked, on each comma",
            "Another example indefinite string with only one chunk",
            "This is a plain string",
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("RpcV2CborIndefiniteStringInsideDefiniteListCanDeserialize", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/cbor",
                ["smithy-protocol"] = "rpc-v2-cbor",
            },
            body = http.string_reader(h.base64_decode([[oWpzdHJpbmdMaXN0g394HUFuIGV4YW1wbGUgaW5kZWZpbml0ZSBzdHJpbmcsdyB3aGljaCB3aWxsIGJlIGNodW5rZWQsbiBvbiBlYWNoIGNvbW1h/394NUFub3RoZXIgZXhhbXBsZSBpbmRlZmluaXRlIHN0cmluZyB3aXRoIG9ubHkgb25lIGNodW5r/3ZUaGlzIGlzIGEgcGxhaW4gc3RyaW5n]])),
        }
        local operation = schema.operation({
            id = shape_id.from("smithy.protocoltests.rpcv2Cbor", "RpcV2CborLists"),
            input = schema.new({ type = "structure" }),
            output = types.RpcV2CborListsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            stringList = {
            "An example indefinite string, which will be chunked, on each comma",
            "Another example indefinite string with only one chunk",
            "This is a plain string",
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

end)
