-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: rpcv2Cbor

local types = require("rpcV2Protocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.rpcv2")
local protocol = protocol_mod.new_cbor()

local service = schema.service({
    id = shape_id.from("smithy.protocoltests.rpcv2Cbor", "RpcV2Protocol"),
    version = "2020-07-14",
    traits = {},
})

describe("SparseNullsOperation request", function()
    it("RpcV2CborSparseMapsSerializeNullValues", function()
        local input = {
            sparseStringMap = {
            foo = nil,
        },
        }
        local operation = schema.operation({
            id = shape_id.from("smithy.protocoltests.rpcv2Cbor", "SparseNullsOperation"),
            input = types.SparseNullsOperationInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/service/RpcV2Protocol/operation/SparseNullsOperation" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/service/RpcV2Protocol/operation/SparseNullsOperation")
        h.assert_header(request, "Accept", "application/cbor")
        h.assert_header(request, "Content-Type", "application/cbor")
        h.assert_header(request, "smithy-protocol", "rpc-v2-cbor")
        local body_str = h.read_body(request.body)
        h.assert_cbor_eq(body_str, h.base64_decode([[v29zcGFyc2VTdHJpbmdNYXC/Y2Zvb/b//w==]]))
    end)

    it("RpcV2CborSparseListsSerializeNull", function()
        local input = {
            sparseStringList = {
            nil,
        },
        }
        local operation = schema.operation({
            id = shape_id.from("smithy.protocoltests.rpcv2Cbor", "SparseNullsOperation"),
            input = types.SparseNullsOperationInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/service/RpcV2Protocol/operation/SparseNullsOperation" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/service/RpcV2Protocol/operation/SparseNullsOperation")
        h.assert_header(request, "Accept", "application/cbor")
        h.assert_header(request, "Content-Type", "application/cbor")
        h.assert_header(request, "smithy-protocol", "rpc-v2-cbor")
        local body_str = h.read_body(request.body)
        h.assert_cbor_eq(body_str, h.base64_decode([[v3BzcGFyc2VTdHJpbmdMaXN0n/b//w==]]))
    end)

end)
