-- Code generated by lua-client-codegen. DO NOT EDIT.

local awsjson_protocol = require("smithy.protocol.awsjson")
local base_client = require("smithy.client")
local defaults = require("smithy.defaults")
local schemas = require("jsonprotocol.schemas")
local traits = require("smithy.traits")

local M = {}

local Client = {}
Client.__index = Client

Client.invokeOperation = base_client.invokeOperation

function M.new(cfg)
    cfg = cfg or {}
    cfg.service_id = "JsonProtocol"
    if not cfg.protocol then
        cfg.protocol = awsjson_protocol.new({ version = "1.1", service_id = cfg.service_id })
    end
    if not cfg.auth_scheme_resolver then
        cfg.auth_scheme_resolver = function(service, operation)
            local auth_trait = operation:trait(traits.AUTH) or service:trait(traits.AUTH)
            local options = {}
            for _, scheme in ipairs(auth_trait or {}) do
                local scheme_id = scheme.scheme_id or scheme
                if scheme_id == "aws.auth#sigv4" or scheme_id == "aws.auth#sigv4a" then
                    options[#options + 1] = { scheme_id = scheme_id, signer_properties = { signing_name = "jsonprotocol", signing_region = cfg.region } }
                else
                    options[#options + 1] = { scheme_id = scheme_id }
                end
            end
            return options
        end
    end
    defaults.resolve_auth_schemes(cfg)
    defaults.resolve_identity_resolvers(cfg)
    defaults.resolve_http_client(cfg)
    defaults.resolve_retry_strategy(cfg)
    local self = setmetatable(base_client.new(cfg), Client)
    return self
end

function Client:contentTypeParameters(input, options)
    return self:invokeOperation(schemas.Service, schemas.ContentTypeParameters, input, options)
end

function Client:datetimeOffsets(input, options)
    return self:invokeOperation(schemas.Service, schemas.DatetimeOffsets, input, options)
end

function Client:emptyOperation(input, options)
    return self:invokeOperation(schemas.Service, schemas.EmptyOperation, input, options)
end

function Client:endpointOperation(input, options)
    return self:invokeOperation(schemas.Service, schemas.EndpointOperation, input, options)
end

function Client:endpointWithHostLabelOperation(input, options)
    return self:invokeOperation(schemas.Service, schemas.EndpointWithHostLabelOperation, input, options)
end

function Client:fractionalSeconds(input, options)
    return self:invokeOperation(schemas.Service, schemas.FractionalSeconds, input, options)
end

function Client:greetingWithErrors(input, options)
    return self:invokeOperation(schemas.Service, schemas.GreetingWithErrors, input, options)
end

function Client:hostWithPathOperation(input, options)
    return self:invokeOperation(schemas.Service, schemas.HostWithPathOperation, input, options)
end

function Client:jsonEnums(input, options)
    return self:invokeOperation(schemas.Service, schemas.JsonEnums, input, options)
end

function Client:jsonIntEnums(input, options)
    return self:invokeOperation(schemas.Service, schemas.JsonIntEnums, input, options)
end

function Client:jsonUnions(input, options)
    return self:invokeOperation(schemas.Service, schemas.JsonUnions, input, options)
end

function Client:kitchenSinkOperation(input, options)
    return self:invokeOperation(schemas.Service, schemas.KitchenSinkOperation, input, options)
end

function Client:nullOperation(input, options)
    return self:invokeOperation(schemas.Service, schemas.NullOperation, input, options)
end

function Client:operationWithOptionalInputOutput(input, options)
    return self:invokeOperation(schemas.Service, schemas.OperationWithOptionalInputOutput, input, options)
end

function Client:putAndGetInlineDocuments(input, options)
    return self:invokeOperation(schemas.Service, schemas.PutAndGetInlineDocuments, input, options)
end

function Client:putWithContentEncoding(input, options)
    return self:invokeOperation(schemas.Service, schemas.PutWithContentEncoding, input, options)
end

function Client:simpleScalarProperties(input, options)
    return self:invokeOperation(schemas.Service, schemas.SimpleScalarProperties, input, options)
end

function Client:sparseNullsOperation(input, options)
    return self:invokeOperation(schemas.Service, schemas.SparseNullsOperation, input, options)
end

return M
