-- Code generated by lua-client-codegen. DO NOT EDIT.

local id = require("smithy.shape_id")
local schema = require("smithy.schema")
local prelude = require("smithy.prelude")
local traits = require("smithy.traits")

local _N = "aws.protocoltests.json"

local M = {}

M.ListOfListOfStrings = schema.new({ type = "list", list_member = M.ListOfStrings })

M.ListOfMapsOfStrings = schema.new({ type = "list", list_member = M.MapOfStrings })

M.ListOfStrings = schema.new({ type = "list", list_member = prelude.String })

M.ListOfStructs = schema.new({ type = "list", list_member = M.SimpleStruct })

M.MapOfListsOfStrings = schema.new({ type = "map", map_key = prelude.String, map_value = M.ListOfStrings })

M.MapOfMapOfStrings = schema.new({ type = "map", map_key = prelude.String, map_value = M.MapOfStrings })

M.MapOfStrings = schema.new({ type = "map", map_key = prelude.String, map_value = prelude.String })

M.MapOfStructs = schema.new({ type = "map", map_key = prelude.String, map_value = M.SimpleStruct })

M.ListOfKitchenSinks = schema.new({ type = "list", list_member = M.KitchenSink })

M.MapOfKitchenSinks = schema.new({ type = "map", map_key = prelude.String, map_value = M.KitchenSink })

M.FooEnumList = schema.new({ type = "list", list_member = prelude.String })

M.FooEnumSet = schema.new({ type = "list", list_member = prelude.String })

M.FooEnumMap = schema.new({ type = "map", map_key = prelude.String, map_value = prelude.String })

M.IntegerEnumList = schema.new({ type = "list", list_member = prelude.Integer })

M.IntegerEnumSet = schema.new({ type = "list", list_member = prelude.Integer })

M.IntegerEnumMap = schema.new({ type = "map", map_key = prelude.String, map_value = prelude.Integer })

M.SparseStringList = schema.new({ type = "list", list_member = prelude.String })

M.SparseStringMap = schema.new({ type = "map", map_key = prelude.String, map_value = prelude.String })

M.StringList = schema.new({ type = "list", list_member = prelude.String })

M.StringMap = schema.new({ type = "map", map_key = prelude.String, map_value = prelude.String })

M.ComplexNestedErrorData = schema.new({
    id = id.from(_N, "ComplexNestedErrorData"),
    type = "structure",
    members = {
        Foo = schema.new({
            id = id.from(_N, "ComplexNestedErrorData", "Foo"),
            type = "string",
            name = "Foo",
            target_id = prelude.String.id,
            traits = {
                [traits.JSON_NAME] = { name = "Fooooo" },
            },
        }),
    },
})

M.ComplexError = schema.new({
    id = id.from(_N, "ComplexError"),
    type = "structure",
    traits = {
        [traits.ERROR] = { value = "client" },
    },
    members = {
        TopLevel = schema.new({
            id = id.from(_N, "ComplexError", "TopLevel"),
            type = "string",
            name = "TopLevel",
            target_id = prelude.String.id,
        }),
        Nested = schema.new({
            id = id.from(_N, "ComplexError", "Nested"),
            type = "structure",
            name = "Nested",
            target_id = id.from(_N, "ComplexNestedErrorData"),
            target = M.ComplexNestedErrorData,
        }),
    },
})

M.ContentTypeParametersInput = schema.new({
    id = id.from(_N, "ContentTypeParametersInput"),
    type = "structure",
    members = {
        value = schema.new({
            id = id.from(_N, "ContentTypeParametersInput", "value"),
            type = "integer",
            name = "value",
            target_id = prelude.Integer.id,
        }),
    },
})

M.ContentTypeParametersOutput = schema.new({
    id = id.from(_N, "ContentTypeParametersOutput"),
    type = "structure",
})

M.DatetimeOffsetsInput = prelude.Unit

M.DatetimeOffsetsOutput = schema.new({
    id = id.from(_N, "DatetimeOffsetsOutput"),
    type = "structure",
    members = {
        datetime = schema.new({
            id = id.from(_N, "DatetimeOffsetsOutput", "datetime"),
            type = "timestamp",
            name = "datetime",
            target_id = prelude.Timestamp.id,
            traits = {
                [traits.TIMESTAMP_FORMAT] = { format = "date-time" },
            },
        }),
    },
})

M.EmptyOperationInput = prelude.Unit

M.EmptyOperationOutput = prelude.Unit

M.EmptyStruct = schema.new({
    id = id.from(_N, "EmptyStruct"),
    type = "structure",
})

M.EndpointOperationInput = prelude.Unit

M.EndpointOperationOutput = prelude.Unit

M.EndpointWithHostLabelOperationInput = schema.new({
    id = id.from(_N, "HostLabelInput"),
    type = "structure",
    members = {
        label = schema.new({
            id = id.from(_N, "EndpointWithHostLabelOperationInput", "label"),
            type = "string",
            name = "label",
            target_id = prelude.String.id,
            traits = {
                [traits.REQUIRED] = {},
            },
        }),
    },
})

M.EndpointWithHostLabelOperationOutput = prelude.Unit

M.SimpleStruct = schema.new({
    id = id.from(_N, "SimpleStruct"),
    type = "structure",
    members = {
        Value = schema.new({
            id = id.from(_N, "SimpleStruct", "Value"),
            type = "string",
            name = "Value",
            target_id = prelude.String.id,
        }),
    },
})

M.StructWithJsonName = schema.new({
    id = id.from(_N, "StructWithJsonName"),
    type = "structure",
    members = {
        Value = schema.new({
            id = id.from(_N, "StructWithJsonName", "Value"),
            type = "string",
            name = "Value",
            target_id = prelude.String.id,
            traits = {
                [traits.JSON_NAME] = { name = "RenamedMember" },
            },
        }),
    },
})

M.ErrorWithoutMembers = schema.new({
    id = id.from(_N, "ErrorWithoutMembers"),
    type = "structure",
    traits = {
        [traits.ERROR] = { value = "server" },
    },
})

M.FooError = schema.new({
    id = id.from(_N, "FooError"),
    type = "structure",
    traits = {
        [traits.ERROR] = { value = "server" },
    },
})

M.FractionalSecondsInput = prelude.Unit

M.FractionalSecondsOutput = schema.new({
    id = id.from(_N, "FractionalSecondsOutput"),
    type = "structure",
    members = {
        datetime = schema.new({
            id = id.from(_N, "FractionalSecondsOutput", "datetime"),
            type = "timestamp",
            name = "datetime",
            target_id = prelude.Timestamp.id,
            traits = {
                [traits.TIMESTAMP_FORMAT] = { format = "date-time" },
            },
        }),
    },
})

M.GreetingWithErrorsInput = prelude.Unit

M.GreetingWithErrorsOutput = schema.new({
    id = id.from(_N, "GreetingWithErrorsOutput"),
    type = "structure",
    members = {
        greeting = schema.new({
            id = id.from(_N, "GreetingWithErrorsOutput", "greeting"),
            type = "string",
            name = "greeting",
            target_id = prelude.String.id,
        }),
    },
})

M.InvalidGreeting = schema.new({
    id = id.from(_N, "InvalidGreeting"),
    type = "structure",
    traits = {
        [traits.ERROR] = { value = "client" },
    },
    members = {
        Message = schema.new({
            id = id.from(_N, "InvalidGreeting", "Message"),
            type = "string",
            name = "Message",
            target_id = prelude.String.id,
        }),
    },
})

M.HostWithPathOperationInput = prelude.Unit

M.HostWithPathOperationOutput = prelude.Unit

M.JsonEnumsInput = schema.new({
    id = id.from(_N, "JsonEnumsInputOutput"),
    type = "structure",
    members = {
        fooEnum1 = schema.new({
            id = id.from(_N, "JsonEnumsInput", "fooEnum1"),
            type = "string",
            name = "fooEnum1",
            target_id = prelude.String.id,
        }),
        fooEnum2 = schema.new({
            id = id.from(_N, "JsonEnumsInput", "fooEnum2"),
            type = "string",
            name = "fooEnum2",
            target_id = prelude.String.id,
        }),
        fooEnum3 = schema.new({
            id = id.from(_N, "JsonEnumsInput", "fooEnum3"),
            type = "string",
            name = "fooEnum3",
            target_id = prelude.String.id,
        }),
        fooEnumList = schema.new({
            id = id.from(_N, "JsonEnumsInput", "fooEnumList"),
            type = "list",
            name = "fooEnumList",
            target_id = prelude.Document.id,
            list_member = prelude.String,
        }),
        fooEnumSet = schema.new({
            id = id.from(_N, "JsonEnumsInput", "fooEnumSet"),
            type = "list",
            name = "fooEnumSet",
            target_id = prelude.Document.id,
            list_member = prelude.String,
        }),
        fooEnumMap = schema.new({
            id = id.from(_N, "JsonEnumsInput", "fooEnumMap"),
            type = "map",
            name = "fooEnumMap",
            target_id = prelude.Document.id,
            map_key = prelude.String,
            map_value = prelude.String,
        }),
    },
})

M.JsonEnumsOutput = schema.new({
    id = id.from(_N, "JsonEnumsInputOutput"),
    type = "structure",
    members = {
        fooEnum1 = schema.new({
            id = id.from(_N, "JsonEnumsOutput", "fooEnum1"),
            type = "string",
            name = "fooEnum1",
            target_id = prelude.String.id,
        }),
        fooEnum2 = schema.new({
            id = id.from(_N, "JsonEnumsOutput", "fooEnum2"),
            type = "string",
            name = "fooEnum2",
            target_id = prelude.String.id,
        }),
        fooEnum3 = schema.new({
            id = id.from(_N, "JsonEnumsOutput", "fooEnum3"),
            type = "string",
            name = "fooEnum3",
            target_id = prelude.String.id,
        }),
        fooEnumList = schema.new({
            id = id.from(_N, "JsonEnumsOutput", "fooEnumList"),
            type = "list",
            name = "fooEnumList",
            target_id = prelude.Document.id,
            list_member = prelude.String,
        }),
        fooEnumSet = schema.new({
            id = id.from(_N, "JsonEnumsOutput", "fooEnumSet"),
            type = "list",
            name = "fooEnumSet",
            target_id = prelude.Document.id,
            list_member = prelude.String,
        }),
        fooEnumMap = schema.new({
            id = id.from(_N, "JsonEnumsOutput", "fooEnumMap"),
            type = "map",
            name = "fooEnumMap",
            target_id = prelude.Document.id,
            map_key = prelude.String,
            map_value = prelude.String,
        }),
    },
})

M.JsonIntEnumsInput = schema.new({
    id = id.from(_N, "JsonIntEnumsInputOutput"),
    type = "structure",
    members = {
        intEnum1 = schema.new({
            id = id.from(_N, "JsonIntEnumsInput", "intEnum1"),
            type = "number",
            name = "intEnum1",
            target_id = prelude.Integer.id,
        }),
        intEnum2 = schema.new({
            id = id.from(_N, "JsonIntEnumsInput", "intEnum2"),
            type = "number",
            name = "intEnum2",
            target_id = prelude.Integer.id,
        }),
        intEnum3 = schema.new({
            id = id.from(_N, "JsonIntEnumsInput", "intEnum3"),
            type = "number",
            name = "intEnum3",
            target_id = prelude.Integer.id,
        }),
        intEnumList = schema.new({
            id = id.from(_N, "JsonIntEnumsInput", "intEnumList"),
            type = "list",
            name = "intEnumList",
            target_id = prelude.Document.id,
            list_member = prelude.Integer,
        }),
        intEnumSet = schema.new({
            id = id.from(_N, "JsonIntEnumsInput", "intEnumSet"),
            type = "list",
            name = "intEnumSet",
            target_id = prelude.Document.id,
            list_member = prelude.Integer,
        }),
        intEnumMap = schema.new({
            id = id.from(_N, "JsonIntEnumsInput", "intEnumMap"),
            type = "map",
            name = "intEnumMap",
            target_id = prelude.Document.id,
            map_key = prelude.String,
            map_value = prelude.Integer,
        }),
    },
})

M.JsonIntEnumsOutput = schema.new({
    id = id.from(_N, "JsonIntEnumsInputOutput"),
    type = "structure",
    members = {
        intEnum1 = schema.new({
            id = id.from(_N, "JsonIntEnumsOutput", "intEnum1"),
            type = "number",
            name = "intEnum1",
            target_id = prelude.Integer.id,
        }),
        intEnum2 = schema.new({
            id = id.from(_N, "JsonIntEnumsOutput", "intEnum2"),
            type = "number",
            name = "intEnum2",
            target_id = prelude.Integer.id,
        }),
        intEnum3 = schema.new({
            id = id.from(_N, "JsonIntEnumsOutput", "intEnum3"),
            type = "number",
            name = "intEnum3",
            target_id = prelude.Integer.id,
        }),
        intEnumList = schema.new({
            id = id.from(_N, "JsonIntEnumsOutput", "intEnumList"),
            type = "list",
            name = "intEnumList",
            target_id = prelude.Document.id,
            list_member = prelude.Integer,
        }),
        intEnumSet = schema.new({
            id = id.from(_N, "JsonIntEnumsOutput", "intEnumSet"),
            type = "list",
            name = "intEnumSet",
            target_id = prelude.Document.id,
            list_member = prelude.Integer,
        }),
        intEnumMap = schema.new({
            id = id.from(_N, "JsonIntEnumsOutput", "intEnumMap"),
            type = "map",
            name = "intEnumMap",
            target_id = prelude.Document.id,
            map_key = prelude.String,
            map_value = prelude.Integer,
        }),
    },
})

M.GreetingStruct = schema.new({
    id = id.from(_N, "GreetingStruct"),
    type = "structure",
    members = {
        hi = schema.new({
            id = id.from(_N, "GreetingStruct", "hi"),
            type = "string",
            name = "hi",
            target_id = prelude.String.id,
        }),
    },
})

M.MyUnion = schema.new({
    id = id.from(_N, "MyUnion"),
    type = "union",
    members = {
        stringValue = schema.new({
            id = id.from(_N, "MyUnion", "stringValue"),
            type = "string",
            name = "stringValue",
            target_id = prelude.String.id,
        }),
        booleanValue = schema.new({
            id = id.from(_N, "MyUnion", "booleanValue"),
            type = "boolean",
            name = "booleanValue",
            target_id = prelude.Boolean.id,
        }),
        numberValue = schema.new({
            id = id.from(_N, "MyUnion", "numberValue"),
            type = "integer",
            name = "numberValue",
            target_id = prelude.Integer.id,
        }),
        blobValue = schema.new({
            id = id.from(_N, "MyUnion", "blobValue"),
            type = "blob",
            name = "blobValue",
            target_id = prelude.Blob.id,
        }),
        timestampValue = schema.new({
            id = id.from(_N, "MyUnion", "timestampValue"),
            type = "timestamp",
            name = "timestampValue",
            target_id = prelude.Timestamp.id,
        }),
        enumValue = schema.new({
            id = id.from(_N, "MyUnion", "enumValue"),
            type = "string",
            name = "enumValue",
            target_id = prelude.String.id,
        }),
        listValue = schema.new({
            id = id.from(_N, "MyUnion", "listValue"),
            type = "list",
            name = "listValue",
            target_id = prelude.Document.id,
            list_member = prelude.String,
        }),
        mapValue = schema.new({
            id = id.from(_N, "MyUnion", "mapValue"),
            type = "map",
            name = "mapValue",
            target_id = prelude.Document.id,
            map_key = prelude.String,
            map_value = prelude.String,
        }),
        structureValue = schema.new({
            id = id.from(_N, "MyUnion", "structureValue"),
            type = "structure",
            name = "structureValue",
            target_id = id.from(_N, "GreetingStruct"),
            target = M.GreetingStruct,
        }),
    },
})

M.JsonUnionsInput = schema.new({
    id = id.from(_N, "UnionInputOutput"),
    type = "structure",
    members = {
        contents = schema.new({
            id = id.from(_N, "JsonUnionsInput", "contents"),
            type = "union",
            name = "contents",
            target_id = id.from(_N, "MyUnion"),
            target = M.MyUnion,
        }),
    },
})

M.JsonUnionsOutput = schema.new({
    id = id.from(_N, "UnionInputOutput"),
    type = "structure",
    members = {
        contents = schema.new({
            id = id.from(_N, "JsonUnionsOutput", "contents"),
            type = "union",
            name = "contents",
            target_id = id.from(_N, "MyUnion"),
            target = M.MyUnion,
        }),
    },
})

M.NullOperationInput = schema.new({
    id = id.from(_N, "NullOperationInputOutput"),
    type = "structure",
    members = {
        string = schema.new({
            id = id.from(_N, "NullOperationInput", "string"),
            type = "string",
            name = "string",
            target_id = prelude.String.id,
        }),
    },
})

M.NullOperationOutput = schema.new({
    id = id.from(_N, "NullOperationInputOutput"),
    type = "structure",
    members = {
        string = schema.new({
            id = id.from(_N, "NullOperationOutput", "string"),
            type = "string",
            name = "string",
            target_id = prelude.String.id,
        }),
    },
})

M.OperationWithOptionalInputOutputInput = schema.new({
    id = id.from(_N, "OperationWithOptionalInputOutputInput"),
    type = "structure",
    members = {
        Value = schema.new({
            id = id.from(_N, "OperationWithOptionalInputOutputInput", "Value"),
            type = "string",
            name = "Value",
            target_id = prelude.String.id,
        }),
    },
})

M.OperationWithOptionalInputOutputOutput = schema.new({
    id = id.from(_N, "OperationWithOptionalInputOutputOutput"),
    type = "structure",
    members = {
        Value = schema.new({
            id = id.from(_N, "OperationWithOptionalInputOutputOutput", "Value"),
            type = "string",
            name = "Value",
            target_id = prelude.String.id,
        }),
    },
})

M.PutAndGetInlineDocumentsInput = schema.new({
    id = id.from(_N, "PutAndGetInlineDocumentsInputOutput"),
    type = "structure",
    members = {
        inlineDocument = schema.new({
            id = id.from(_N, "PutAndGetInlineDocumentsInput", "inlineDocument"),
            type = "document",
            name = "inlineDocument",
            target_id = prelude.Document.id,
        }),
    },
})

M.PutAndGetInlineDocumentsOutput = schema.new({
    id = id.from(_N, "PutAndGetInlineDocumentsInputOutput"),
    type = "structure",
    members = {
        inlineDocument = schema.new({
            id = id.from(_N, "PutAndGetInlineDocumentsOutput", "inlineDocument"),
            type = "document",
            name = "inlineDocument",
            target_id = prelude.Document.id,
        }),
    },
})

M.PutWithContentEncodingInput = schema.new({
    id = id.from(_N, "PutWithContentEncodingInput"),
    type = "structure",
    members = {
        encoding = schema.new({
            id = id.from(_N, "PutWithContentEncodingInput", "encoding"),
            type = "string",
            name = "encoding",
            target_id = prelude.String.id,
            traits = {
                [traits.HTTP_HEADER] = { name = "Content-Encoding" },
            },
        }),
        data = schema.new({
            id = id.from(_N, "PutWithContentEncodingInput", "data"),
            type = "string",
            name = "data",
            target_id = prelude.String.id,
        }),
    },
})

M.PutWithContentEncodingOutput = prelude.Unit

M.SimpleScalarPropertiesInput = schema.new({
    id = id.from(_N, "SimpleScalarPropertiesInputOutput"),
    type = "structure",
    members = {
        floatValue = schema.new({
            id = id.from(_N, "SimpleScalarPropertiesInput", "floatValue"),
            type = "float",
            name = "floatValue",
            target_id = prelude.Float.id,
        }),
        doubleValue = schema.new({
            id = id.from(_N, "SimpleScalarPropertiesInput", "doubleValue"),
            type = "double",
            name = "doubleValue",
            target_id = prelude.Double.id,
        }),
    },
})

M.SimpleScalarPropertiesOutput = schema.new({
    id = id.from(_N, "SimpleScalarPropertiesInputOutput"),
    type = "structure",
    members = {
        floatValue = schema.new({
            id = id.from(_N, "SimpleScalarPropertiesOutput", "floatValue"),
            type = "float",
            name = "floatValue",
            target_id = prelude.Float.id,
        }),
        doubleValue = schema.new({
            id = id.from(_N, "SimpleScalarPropertiesOutput", "doubleValue"),
            type = "double",
            name = "doubleValue",
            target_id = prelude.Double.id,
        }),
    },
})

M.SparseNullsOperationInput = schema.new({
    id = id.from(_N, "SparseNullsOperationInputOutput"),
    type = "structure",
    members = {
        sparseStringList = schema.new({
            id = id.from(_N, "SparseNullsOperationInput", "sparseStringList"),
            type = "list",
            name = "sparseStringList",
            target_id = prelude.Document.id,
            list_member = prelude.String,
        }),
        sparseStringMap = schema.new({
            id = id.from(_N, "SparseNullsOperationInput", "sparseStringMap"),
            type = "map",
            name = "sparseStringMap",
            target_id = prelude.Document.id,
            map_key = prelude.String,
            map_value = prelude.String,
        }),
    },
})

M.SparseNullsOperationOutput = schema.new({
    id = id.from(_N, "SparseNullsOperationInputOutput"),
    type = "structure",
    members = {
        sparseStringList = schema.new({
            id = id.from(_N, "SparseNullsOperationOutput", "sparseStringList"),
            type = "list",
            name = "sparseStringList",
            target_id = prelude.Document.id,
            list_member = prelude.String,
        }),
        sparseStringMap = schema.new({
            id = id.from(_N, "SparseNullsOperationOutput", "sparseStringMap"),
            type = "map",
            name = "sparseStringMap",
            target_id = prelude.Document.id,
            map_key = prelude.String,
            map_value = prelude.String,
        }),
    },
})

M.KitchenSink = schema.new({
    id = id.from(_N, "KitchenSink"),
    type = "structure",
    members = {
        Blob = schema.new({
            id = id.from(_N, "KitchenSink", "Blob"),
            type = "blob",
            name = "Blob",
            target_id = prelude.Blob.id,
        }),
        Boolean = schema.new({
            id = id.from(_N, "KitchenSink", "Boolean"),
            type = "boolean",
            name = "Boolean",
            target_id = prelude.Boolean.id,
        }),
        Double = schema.new({
            id = id.from(_N, "KitchenSink", "Double"),
            type = "double",
            name = "Double",
            target_id = prelude.Double.id,
        }),
        EmptyStruct = schema.new({
            id = id.from(_N, "KitchenSink", "EmptyStruct"),
            type = "structure",
            name = "EmptyStruct",
            target_id = id.from(_N, "EmptyStruct"),
            target = M.EmptyStruct,
        }),
        Float = schema.new({
            id = id.from(_N, "KitchenSink", "Float"),
            type = "float",
            name = "Float",
            target_id = prelude.Float.id,
        }),
        HttpdateTimestamp = schema.new({
            id = id.from(_N, "KitchenSink", "HttpdateTimestamp"),
            type = "timestamp",
            name = "HttpdateTimestamp",
            target_id = prelude.Timestamp.id,
            traits = {
                [traits.TIMESTAMP_FORMAT] = { format = "http-date" },
            },
        }),
        Integer = schema.new({
            id = id.from(_N, "KitchenSink", "Integer"),
            type = "integer",
            name = "Integer",
            target_id = prelude.Integer.id,
        }),
        Iso8601Timestamp = schema.new({
            id = id.from(_N, "KitchenSink", "Iso8601Timestamp"),
            type = "timestamp",
            name = "Iso8601Timestamp",
            target_id = prelude.Timestamp.id,
            traits = {
                [traits.TIMESTAMP_FORMAT] = { format = "date-time" },
            },
        }),
        JsonValue = schema.new({
            id = id.from(_N, "KitchenSink", "JsonValue"),
            type = "string",
            name = "JsonValue",
            target_id = prelude.String.id,
            traits = {
                [traits.MEDIA_TYPE] = { value = "application/json" },
            },
        }),
        ListOfLists = schema.new({
            id = id.from(_N, "KitchenSink", "ListOfLists"),
            type = "list",
            name = "ListOfLists",
            target_id = prelude.Document.id,
            list_member = schema.new({ type = "list", list_member = prelude.String }),
        }),
        ListOfMapsOfStrings = schema.new({
            id = id.from(_N, "KitchenSink", "ListOfMapsOfStrings"),
            type = "list",
            name = "ListOfMapsOfStrings",
            target_id = prelude.Document.id,
            list_member = M.MapOfStrings,
        }),
        ListOfStrings = schema.new({
            id = id.from(_N, "KitchenSink", "ListOfStrings"),
            type = "list",
            name = "ListOfStrings",
            target_id = prelude.Document.id,
            list_member = prelude.String,
        }),
        ListOfStructs = schema.new({
            id = id.from(_N, "KitchenSink", "ListOfStructs"),
            type = "list",
            name = "ListOfStructs",
            target_id = prelude.Document.id,
            list_member = M.SimpleStruct,
        }),
        Long = schema.new({
            id = id.from(_N, "KitchenSink", "Long"),
            type = "long",
            name = "Long",
            target_id = prelude.Long.id,
        }),
        MapOfListsOfStrings = schema.new({
            id = id.from(_N, "KitchenSink", "MapOfListsOfStrings"),
            type = "map",
            name = "MapOfListsOfStrings",
            target_id = prelude.Document.id,
            map_key = prelude.String,
            map_value = schema.new({ type = "list", list_member = prelude.String }),
        }),
        MapOfMaps = schema.new({
            id = id.from(_N, "KitchenSink", "MapOfMaps"),
            type = "map",
            name = "MapOfMaps",
            target_id = prelude.Document.id,
            map_key = prelude.String,
            map_value = schema.new({ type = "map", map_key = prelude.String, map_value = prelude.String }),
        }),
        MapOfStrings = schema.new({
            id = id.from(_N, "KitchenSink", "MapOfStrings"),
            type = "map",
            name = "MapOfStrings",
            target_id = prelude.Document.id,
            map_key = prelude.String,
            map_value = prelude.String,
        }),
        MapOfStructs = schema.new({
            id = id.from(_N, "KitchenSink", "MapOfStructs"),
            type = "map",
            name = "MapOfStructs",
            target_id = prelude.Document.id,
            map_key = prelude.String,
            map_value = M.SimpleStruct,
        }),
        RecursiveList = schema.new({
            id = id.from(_N, "KitchenSink", "RecursiveList"),
            type = "list",
            name = "RecursiveList",
            target_id = prelude.Document.id,
            list_member = M.KitchenSink,
        }),
        RecursiveMap = schema.new({
            id = id.from(_N, "KitchenSink", "RecursiveMap"),
            type = "map",
            name = "RecursiveMap",
            target_id = prelude.Document.id,
            map_key = prelude.String,
            map_value = M.KitchenSink,
        }),
        RecursiveStruct = schema.new({
            id = id.from(_N, "KitchenSink", "RecursiveStruct"),
            type = "structure",
            name = "RecursiveStruct",
            target_id = id.from(_N, "KitchenSink"),
            target = M.KitchenSink,
        }),
        SimpleStruct = schema.new({
            id = id.from(_N, "KitchenSink", "SimpleStruct"),
            type = "structure",
            name = "SimpleStruct",
            target_id = id.from(_N, "SimpleStruct"),
            target = M.SimpleStruct,
        }),
        String = schema.new({
            id = id.from(_N, "KitchenSink", "String"),
            type = "string",
            name = "String",
            target_id = prelude.String.id,
        }),
        StructWithJsonName = schema.new({
            id = id.from(_N, "KitchenSink", "StructWithJsonName"),
            type = "structure",
            name = "StructWithJsonName",
            target_id = id.from(_N, "StructWithJsonName"),
            target = M.StructWithJsonName,
        }),
        Timestamp = schema.new({
            id = id.from(_N, "KitchenSink", "Timestamp"),
            type = "timestamp",
            name = "Timestamp",
            target_id = prelude.Timestamp.id,
        }),
        UnixTimestamp = schema.new({
            id = id.from(_N, "KitchenSink", "UnixTimestamp"),
            type = "timestamp",
            name = "UnixTimestamp",
            target_id = prelude.Timestamp.id,
            traits = {
                [traits.TIMESTAMP_FORMAT] = { format = "epoch-seconds" },
            },
        }),
    },
})

M.ErrorWithMembers = schema.new({
    id = id.from(_N, "ErrorWithMembers"),
    type = "structure",
    traits = {
        [traits.ERROR] = { value = "client" },
    },
    members = {
        Code = schema.new({
            id = id.from(_N, "ErrorWithMembers", "Code"),
            type = "string",
            name = "Code",
            target_id = prelude.String.id,
        }),
        ComplexData = schema.new({
            id = id.from(_N, "ErrorWithMembers", "ComplexData"),
            type = "structure",
            name = "ComplexData",
            target_id = id.from(_N, "KitchenSink"),
            target = M.KitchenSink,
        }),
        IntegerField = schema.new({
            id = id.from(_N, "ErrorWithMembers", "IntegerField"),
            type = "integer",
            name = "IntegerField",
            target_id = prelude.Integer.id,
        }),
        ListField = schema.new({
            id = id.from(_N, "ErrorWithMembers", "ListField"),
            type = "list",
            name = "ListField",
            target_id = prelude.Document.id,
            list_member = prelude.String,
        }),
        MapField = schema.new({
            id = id.from(_N, "ErrorWithMembers", "MapField"),
            type = "map",
            name = "MapField",
            target_id = prelude.Document.id,
            map_key = prelude.String,
            map_value = prelude.String,
        }),
        Message = schema.new({
            id = id.from(_N, "ErrorWithMembers", "Message"),
            type = "string",
            name = "Message",
            target_id = prelude.String.id,
        }),
        StringField = schema.new({
            id = id.from(_N, "ErrorWithMembers", "StringField"),
            type = "string",
            name = "StringField",
            target_id = prelude.String.id,
        }),
    },
})

M.KitchenSinkOperationInput = schema.new({
    id = id.from(_N, "KitchenSink"),
    type = "structure",
    members = {
        Blob = schema.new({
            id = id.from(_N, "KitchenSinkOperationInput", "Blob"),
            type = "blob",
            name = "Blob",
            target_id = prelude.Blob.id,
        }),
        Boolean = schema.new({
            id = id.from(_N, "KitchenSinkOperationInput", "Boolean"),
            type = "boolean",
            name = "Boolean",
            target_id = prelude.Boolean.id,
        }),
        Double = schema.new({
            id = id.from(_N, "KitchenSinkOperationInput", "Double"),
            type = "double",
            name = "Double",
            target_id = prelude.Double.id,
        }),
        EmptyStruct = schema.new({
            id = id.from(_N, "KitchenSinkOperationInput", "EmptyStruct"),
            type = "structure",
            name = "EmptyStruct",
            target_id = id.from(_N, "EmptyStruct"),
            target = M.EmptyStruct,
        }),
        Float = schema.new({
            id = id.from(_N, "KitchenSinkOperationInput", "Float"),
            type = "float",
            name = "Float",
            target_id = prelude.Float.id,
        }),
        HttpdateTimestamp = schema.new({
            id = id.from(_N, "KitchenSinkOperationInput", "HttpdateTimestamp"),
            type = "timestamp",
            name = "HttpdateTimestamp",
            target_id = prelude.Timestamp.id,
            traits = {
                [traits.TIMESTAMP_FORMAT] = { format = "http-date" },
            },
        }),
        Integer = schema.new({
            id = id.from(_N, "KitchenSinkOperationInput", "Integer"),
            type = "integer",
            name = "Integer",
            target_id = prelude.Integer.id,
        }),
        Iso8601Timestamp = schema.new({
            id = id.from(_N, "KitchenSinkOperationInput", "Iso8601Timestamp"),
            type = "timestamp",
            name = "Iso8601Timestamp",
            target_id = prelude.Timestamp.id,
            traits = {
                [traits.TIMESTAMP_FORMAT] = { format = "date-time" },
            },
        }),
        JsonValue = schema.new({
            id = id.from(_N, "KitchenSinkOperationInput", "JsonValue"),
            type = "string",
            name = "JsonValue",
            target_id = prelude.String.id,
            traits = {
                [traits.MEDIA_TYPE] = { value = "application/json" },
            },
        }),
        ListOfLists = schema.new({
            id = id.from(_N, "KitchenSinkOperationInput", "ListOfLists"),
            type = "list",
            name = "ListOfLists",
            target_id = prelude.Document.id,
            list_member = schema.new({ type = "list", list_member = prelude.String }),
        }),
        ListOfMapsOfStrings = schema.new({
            id = id.from(_N, "KitchenSinkOperationInput", "ListOfMapsOfStrings"),
            type = "list",
            name = "ListOfMapsOfStrings",
            target_id = prelude.Document.id,
            list_member = M.MapOfStrings,
        }),
        ListOfStrings = schema.new({
            id = id.from(_N, "KitchenSinkOperationInput", "ListOfStrings"),
            type = "list",
            name = "ListOfStrings",
            target_id = prelude.Document.id,
            list_member = prelude.String,
        }),
        ListOfStructs = schema.new({
            id = id.from(_N, "KitchenSinkOperationInput", "ListOfStructs"),
            type = "list",
            name = "ListOfStructs",
            target_id = prelude.Document.id,
            list_member = M.SimpleStruct,
        }),
        Long = schema.new({
            id = id.from(_N, "KitchenSinkOperationInput", "Long"),
            type = "long",
            name = "Long",
            target_id = prelude.Long.id,
        }),
        MapOfListsOfStrings = schema.new({
            id = id.from(_N, "KitchenSinkOperationInput", "MapOfListsOfStrings"),
            type = "map",
            name = "MapOfListsOfStrings",
            target_id = prelude.Document.id,
            map_key = prelude.String,
            map_value = schema.new({ type = "list", list_member = prelude.String }),
        }),
        MapOfMaps = schema.new({
            id = id.from(_N, "KitchenSinkOperationInput", "MapOfMaps"),
            type = "map",
            name = "MapOfMaps",
            target_id = prelude.Document.id,
            map_key = prelude.String,
            map_value = schema.new({ type = "map", map_key = prelude.String, map_value = prelude.String }),
        }),
        MapOfStrings = schema.new({
            id = id.from(_N, "KitchenSinkOperationInput", "MapOfStrings"),
            type = "map",
            name = "MapOfStrings",
            target_id = prelude.Document.id,
            map_key = prelude.String,
            map_value = prelude.String,
        }),
        MapOfStructs = schema.new({
            id = id.from(_N, "KitchenSinkOperationInput", "MapOfStructs"),
            type = "map",
            name = "MapOfStructs",
            target_id = prelude.Document.id,
            map_key = prelude.String,
            map_value = M.SimpleStruct,
        }),
        RecursiveList = schema.new({
            id = id.from(_N, "KitchenSinkOperationInput", "RecursiveList"),
            type = "list",
            name = "RecursiveList",
            target_id = prelude.Document.id,
            list_member = M.KitchenSink,
        }),
        RecursiveMap = schema.new({
            id = id.from(_N, "KitchenSinkOperationInput", "RecursiveMap"),
            type = "map",
            name = "RecursiveMap",
            target_id = prelude.Document.id,
            map_key = prelude.String,
            map_value = M.KitchenSink,
        }),
        RecursiveStruct = schema.new({
            id = id.from(_N, "KitchenSinkOperationInput", "RecursiveStruct"),
            type = "structure",
            name = "RecursiveStruct",
            target_id = id.from(_N, "KitchenSink"),
            target = M.KitchenSink,
        }),
        SimpleStruct = schema.new({
            id = id.from(_N, "KitchenSinkOperationInput", "SimpleStruct"),
            type = "structure",
            name = "SimpleStruct",
            target_id = id.from(_N, "SimpleStruct"),
            target = M.SimpleStruct,
        }),
        String = schema.new({
            id = id.from(_N, "KitchenSinkOperationInput", "String"),
            type = "string",
            name = "String",
            target_id = prelude.String.id,
        }),
        StructWithJsonName = schema.new({
            id = id.from(_N, "KitchenSinkOperationInput", "StructWithJsonName"),
            type = "structure",
            name = "StructWithJsonName",
            target_id = id.from(_N, "StructWithJsonName"),
            target = M.StructWithJsonName,
        }),
        Timestamp = schema.new({
            id = id.from(_N, "KitchenSinkOperationInput", "Timestamp"),
            type = "timestamp",
            name = "Timestamp",
            target_id = prelude.Timestamp.id,
        }),
        UnixTimestamp = schema.new({
            id = id.from(_N, "KitchenSinkOperationInput", "UnixTimestamp"),
            type = "timestamp",
            name = "UnixTimestamp",
            target_id = prelude.Timestamp.id,
            traits = {
                [traits.TIMESTAMP_FORMAT] = { format = "epoch-seconds" },
            },
        }),
    },
})

M.KitchenSinkOperationOutput = schema.new({
    id = id.from(_N, "KitchenSink"),
    type = "structure",
    members = {
        Blob = schema.new({
            id = id.from(_N, "KitchenSinkOperationOutput", "Blob"),
            type = "blob",
            name = "Blob",
            target_id = prelude.Blob.id,
        }),
        Boolean = schema.new({
            id = id.from(_N, "KitchenSinkOperationOutput", "Boolean"),
            type = "boolean",
            name = "Boolean",
            target_id = prelude.Boolean.id,
        }),
        Double = schema.new({
            id = id.from(_N, "KitchenSinkOperationOutput", "Double"),
            type = "double",
            name = "Double",
            target_id = prelude.Double.id,
        }),
        EmptyStruct = schema.new({
            id = id.from(_N, "KitchenSinkOperationOutput", "EmptyStruct"),
            type = "structure",
            name = "EmptyStruct",
            target_id = id.from(_N, "EmptyStruct"),
            target = M.EmptyStruct,
        }),
        Float = schema.new({
            id = id.from(_N, "KitchenSinkOperationOutput", "Float"),
            type = "float",
            name = "Float",
            target_id = prelude.Float.id,
        }),
        HttpdateTimestamp = schema.new({
            id = id.from(_N, "KitchenSinkOperationOutput", "HttpdateTimestamp"),
            type = "timestamp",
            name = "HttpdateTimestamp",
            target_id = prelude.Timestamp.id,
            traits = {
                [traits.TIMESTAMP_FORMAT] = { format = "http-date" },
            },
        }),
        Integer = schema.new({
            id = id.from(_N, "KitchenSinkOperationOutput", "Integer"),
            type = "integer",
            name = "Integer",
            target_id = prelude.Integer.id,
        }),
        Iso8601Timestamp = schema.new({
            id = id.from(_N, "KitchenSinkOperationOutput", "Iso8601Timestamp"),
            type = "timestamp",
            name = "Iso8601Timestamp",
            target_id = prelude.Timestamp.id,
            traits = {
                [traits.TIMESTAMP_FORMAT] = { format = "date-time" },
            },
        }),
        JsonValue = schema.new({
            id = id.from(_N, "KitchenSinkOperationOutput", "JsonValue"),
            type = "string",
            name = "JsonValue",
            target_id = prelude.String.id,
            traits = {
                [traits.MEDIA_TYPE] = { value = "application/json" },
            },
        }),
        ListOfLists = schema.new({
            id = id.from(_N, "KitchenSinkOperationOutput", "ListOfLists"),
            type = "list",
            name = "ListOfLists",
            target_id = prelude.Document.id,
            list_member = schema.new({ type = "list", list_member = prelude.String }),
        }),
        ListOfMapsOfStrings = schema.new({
            id = id.from(_N, "KitchenSinkOperationOutput", "ListOfMapsOfStrings"),
            type = "list",
            name = "ListOfMapsOfStrings",
            target_id = prelude.Document.id,
            list_member = M.MapOfStrings,
        }),
        ListOfStrings = schema.new({
            id = id.from(_N, "KitchenSinkOperationOutput", "ListOfStrings"),
            type = "list",
            name = "ListOfStrings",
            target_id = prelude.Document.id,
            list_member = prelude.String,
        }),
        ListOfStructs = schema.new({
            id = id.from(_N, "KitchenSinkOperationOutput", "ListOfStructs"),
            type = "list",
            name = "ListOfStructs",
            target_id = prelude.Document.id,
            list_member = M.SimpleStruct,
        }),
        Long = schema.new({
            id = id.from(_N, "KitchenSinkOperationOutput", "Long"),
            type = "long",
            name = "Long",
            target_id = prelude.Long.id,
        }),
        MapOfListsOfStrings = schema.new({
            id = id.from(_N, "KitchenSinkOperationOutput", "MapOfListsOfStrings"),
            type = "map",
            name = "MapOfListsOfStrings",
            target_id = prelude.Document.id,
            map_key = prelude.String,
            map_value = schema.new({ type = "list", list_member = prelude.String }),
        }),
        MapOfMaps = schema.new({
            id = id.from(_N, "KitchenSinkOperationOutput", "MapOfMaps"),
            type = "map",
            name = "MapOfMaps",
            target_id = prelude.Document.id,
            map_key = prelude.String,
            map_value = schema.new({ type = "map", map_key = prelude.String, map_value = prelude.String }),
        }),
        MapOfStrings = schema.new({
            id = id.from(_N, "KitchenSinkOperationOutput", "MapOfStrings"),
            type = "map",
            name = "MapOfStrings",
            target_id = prelude.Document.id,
            map_key = prelude.String,
            map_value = prelude.String,
        }),
        MapOfStructs = schema.new({
            id = id.from(_N, "KitchenSinkOperationOutput", "MapOfStructs"),
            type = "map",
            name = "MapOfStructs",
            target_id = prelude.Document.id,
            map_key = prelude.String,
            map_value = M.SimpleStruct,
        }),
        RecursiveList = schema.new({
            id = id.from(_N, "KitchenSinkOperationOutput", "RecursiveList"),
            type = "list",
            name = "RecursiveList",
            target_id = prelude.Document.id,
            list_member = M.KitchenSink,
        }),
        RecursiveMap = schema.new({
            id = id.from(_N, "KitchenSinkOperationOutput", "RecursiveMap"),
            type = "map",
            name = "RecursiveMap",
            target_id = prelude.Document.id,
            map_key = prelude.String,
            map_value = M.KitchenSink,
        }),
        RecursiveStruct = schema.new({
            id = id.from(_N, "KitchenSinkOperationOutput", "RecursiveStruct"),
            type = "structure",
            name = "RecursiveStruct",
            target_id = id.from(_N, "KitchenSink"),
            target = M.KitchenSink,
        }),
        SimpleStruct = schema.new({
            id = id.from(_N, "KitchenSinkOperationOutput", "SimpleStruct"),
            type = "structure",
            name = "SimpleStruct",
            target_id = id.from(_N, "SimpleStruct"),
            target = M.SimpleStruct,
        }),
        String = schema.new({
            id = id.from(_N, "KitchenSinkOperationOutput", "String"),
            type = "string",
            name = "String",
            target_id = prelude.String.id,
        }),
        StructWithJsonName = schema.new({
            id = id.from(_N, "KitchenSinkOperationOutput", "StructWithJsonName"),
            type = "structure",
            name = "StructWithJsonName",
            target_id = id.from(_N, "StructWithJsonName"),
            target = M.StructWithJsonName,
        }),
        Timestamp = schema.new({
            id = id.from(_N, "KitchenSinkOperationOutput", "Timestamp"),
            type = "timestamp",
            name = "Timestamp",
            target_id = prelude.Timestamp.id,
        }),
        UnixTimestamp = schema.new({
            id = id.from(_N, "KitchenSinkOperationOutput", "UnixTimestamp"),
            type = "timestamp",
            name = "UnixTimestamp",
            target_id = prelude.Timestamp.id,
            traits = {
                [traits.TIMESTAMP_FORMAT] = { format = "epoch-seconds" },
            },
        }),
    },
})

-- Fix forward references for recursive schemas
for _, s in pairs(M) do
    if type(s) == "table" and (s.type == "structure" or s.type == "union") then
        local members = rawget(s, "_members")
        if members then
            for _, ms in pairs(members) do
                if (ms.type == "structure" or ms.type == "union") and not rawget(ms, "_target") and ms.target_id then
                    rawset(ms, "_target", M[ms.target_id.name])
                end
            end
        end
    end
end

M.Service = schema.service({
    id = id.from("aws.protocoltests.json", "JsonProtocol"),
    version = "2018-01-01",
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.ContentTypeParameters = schema.operation({
    id = id.from("aws.protocoltests.json", "ContentTypeParameters"),
    input = M.ContentTypeParametersInput,
    output = M.ContentTypeParametersOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.DatetimeOffsets = schema.operation({
    id = id.from("aws.protocoltests.json", "DatetimeOffsets"),
    input = M.DatetimeOffsetsInput,
    output = M.DatetimeOffsetsOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.EmptyOperation = schema.operation({
    id = id.from("aws.protocoltests.json", "EmptyOperation"),
    input = M.EmptyOperationInput,
    output = M.EmptyOperationOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.EndpointOperation = schema.operation({
    id = id.from("aws.protocoltests.json", "EndpointOperation"),
    input = M.EndpointOperationInput,
    output = M.EndpointOperationOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.EndpointWithHostLabelOperation = schema.operation({
    id = id.from("aws.protocoltests.json", "EndpointWithHostLabelOperation"),
    input = M.EndpointWithHostLabelOperationInput,
    output = M.EndpointWithHostLabelOperationOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.FractionalSeconds = schema.operation({
    id = id.from("aws.protocoltests.json", "FractionalSeconds"),
    input = M.FractionalSecondsInput,
    output = M.FractionalSecondsOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.GreetingWithErrors = schema.operation({
    id = id.from("aws.protocoltests.json", "GreetingWithErrors"),
    input = M.GreetingWithErrorsInput,
    output = M.GreetingWithErrorsOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.HostWithPathOperation = schema.operation({
    id = id.from("aws.protocoltests.json", "HostWithPathOperation"),
    input = M.HostWithPathOperationInput,
    output = M.HostWithPathOperationOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.JsonEnums = schema.operation({
    id = id.from("aws.protocoltests.json", "JsonEnums"),
    input = M.JsonEnumsInput,
    output = M.JsonEnumsOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.JsonIntEnums = schema.operation({
    id = id.from("aws.protocoltests.json", "JsonIntEnums"),
    input = M.JsonIntEnumsInput,
    output = M.JsonIntEnumsOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.JsonUnions = schema.operation({
    id = id.from("aws.protocoltests.json", "JsonUnions"),
    input = M.JsonUnionsInput,
    output = M.JsonUnionsOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.KitchenSinkOperation = schema.operation({
    id = id.from("aws.protocoltests.json", "KitchenSinkOperation"),
    input = M.KitchenSinkOperationInput,
    output = M.KitchenSinkOperationOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.NullOperation = schema.operation({
    id = id.from("aws.protocoltests.json", "NullOperation"),
    input = M.NullOperationInput,
    output = M.NullOperationOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.OperationWithOptionalInputOutput = schema.operation({
    id = id.from("aws.protocoltests.json", "OperationWithOptionalInputOutput"),
    input = M.OperationWithOptionalInputOutputInput,
    output = M.OperationWithOptionalInputOutputOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.PutAndGetInlineDocuments = schema.operation({
    id = id.from("aws.protocoltests.json", "PutAndGetInlineDocuments"),
    input = M.PutAndGetInlineDocumentsInput,
    output = M.PutAndGetInlineDocumentsOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.PutWithContentEncoding = schema.operation({
    id = id.from("aws.protocoltests.json", "PutWithContentEncoding"),
    input = M.PutWithContentEncodingInput,
    output = M.PutWithContentEncodingOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.SimpleScalarProperties = schema.operation({
    id = id.from("aws.protocoltests.json", "SimpleScalarProperties"),
    input = M.SimpleScalarPropertiesInput,
    output = M.SimpleScalarPropertiesOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.SparseNullsOperation = schema.operation({
    id = id.from("aws.protocoltests.json", "SparseNullsOperation"),
    input = M.SparseNullsOperationInput,
    output = M.SparseNullsOperationOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

return M
