-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: awsJson1_1

local types = require("jsonprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.awsjson")
local protocol = protocol_mod.new({ version = "1.1" })

local service = schema.service({
    id = shape_id.from("aws.protocoltests.json", "JsonProtocol"),
    version = "2018-01-01",
    traits = {},
})

describe("JsonIntEnums response", function()
    it("AwsJson11IntEnums", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.1",
                ["X-Amz-Target"] = "JsonProtocol.JsonIntEnums",
            },
            body = http.string_reader([[{
                "intEnum1": 1,
                "intEnum2": 2,
                "intEnum3": 3,
                "intEnumList": [
                    1,
                    2
                ],
                "intEnumSet": [
                    1,
                    2
                ],
                "intEnumMap": {
                    "a": 1,
                    "b": 2
                }
            }]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "JsonIntEnums"),
            input = schema.new({ type = "structure" }),
            output = types.JsonIntEnumsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            intEnum1 = 1,
            intEnum2 = 2,
            intEnum3 = 3,
            intEnumList = {
            1,
            2,
        },
            intEnumSet = {
            1,
            2,
        },
            intEnumMap = {
            a = 1,
            b = 2,
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

end)
