-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: awsJson1_1

local types = require("jsonprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.awsjson")
local protocol = protocol_mod.new({ version = "1.1" })

local service = schema.service({
    id = shape_id.from("aws.protocoltests.json", "JsonProtocol"),
    version = "2018-01-01",
    traits = {},
})

describe("JsonIntEnums request", function()
    it("AwsJson11IntEnums", function()
        local input = {
            intEnum1 = 1,
            intEnum2 = 2,
            intEnum3 = 3,
            intEnumList = {
            1,
            2,
        },
            intEnumSet = {
            1,
            2,
        },
            intEnumMap = {
            a = 1,
            b = 2,
        },
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "JsonIntEnums"),
            input = types.JsonIntEnumsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-amz-json-1.1")
        h.assert_header(request, "X-Amz-Target", "JsonProtocol.JsonIntEnums")
        local body_str = h.read_body(request.body)
        h.assert_json_eq(body_str, [[{
            "intEnum1": 1,
            "intEnum2": 2,
            "intEnum3": 3,
            "intEnumList": [
                1,
                2
            ],
            "intEnumSet": [
                1,
                2
            ],
            "intEnumMap": {
                "a": 1,
                "b": 2
            }
        }]])
    end)

end)
