-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: awsJson1_1

local types = require("jsonprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.awsjson")
local protocol = protocol_mod.new({ version = "1.1" })

local service = schema.service({
    id = shape_id.from("aws.protocoltests.json", "JsonProtocol"),
    version = "2018-01-01",
    traits = {},
})

describe("EmptyOperation response", function()
    it("handles_empty_output_shape", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.1",
            },
            body = http.string_reader([[{}]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "EmptyOperation"),
            input = schema.new({ type = "structure" }),
            output = types.EmptyOperationOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
    end)

    it("handles_unexpected_json_output", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.1",
            },
            body = http.string_reader([[{
                "foo": true
            }]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "EmptyOperation"),
            input = schema.new({ type = "structure" }),
            output = types.EmptyOperationOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
    end)

    it("json_1_1_service_responds_with_no_payload", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.1",
            },
            body = http.string_reader([[]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "EmptyOperation"),
            input = schema.new({ type = "structure" }),
            output = types.EmptyOperationOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
    end)

end)
