-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: awsJson1_1

local types = require("jsonprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.awsjson")
local protocol = protocol_mod.new({ version = "1.1" })

local service = schema.service({
    id = shape_id.from("aws.protocoltests.json", "JsonProtocol"),
    version = "2018-01-01",
    traits = {},
})

describe("KitchenSinkOperation response", function()
    it("parses_operations_with_empty_json_bodies", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.1",
            },
            body = http.string_reader([[{}]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "KitchenSinkOperation"),
            input = schema.new({ type = "structure" }),
            output = types.KitchenSinkOperationOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
    end)

    it("parses_string_shapes", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.1",
            },
            body = http.string_reader([[{"String":"string-value"}]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "KitchenSinkOperation"),
            input = schema.new({ type = "structure" }),
            output = types.KitchenSinkOperationOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            String = "string-value",
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("parses_integer_shapes", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.1",
            },
            body = http.string_reader([[{"Integer":1234}]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "KitchenSinkOperation"),
            input = schema.new({ type = "structure" }),
            output = types.KitchenSinkOperationOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            Integer = 1234,
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("parses_long_shapes", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.1",
            },
            body = http.string_reader([[{"Long":1234567890123456789}]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "KitchenSinkOperation"),
            input = schema.new({ type = "structure" }),
            output = types.KitchenSinkOperationOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            Long = 1234567890123456789,
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("parses_float_shapes", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.1",
            },
            body = http.string_reader([[{"Float":1234.5}]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "KitchenSinkOperation"),
            input = schema.new({ type = "structure" }),
            output = types.KitchenSinkOperationOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            Float = 1234.5,
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("parses_double_shapes", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.1",
            },
            body = http.string_reader([[{"Double":123456789.12345679}]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "KitchenSinkOperation"),
            input = schema.new({ type = "structure" }),
            output = types.KitchenSinkOperationOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            Double = 1.2345678912345679E8,
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("parses_boolean_shapes_true", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.1",
            },
            body = http.string_reader([[{"Boolean":true}]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "KitchenSinkOperation"),
            input = schema.new({ type = "structure" }),
            output = types.KitchenSinkOperationOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            Boolean = true,
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("parses_boolean_false", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.1",
            },
            body = http.string_reader([[{"Boolean":false}]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "KitchenSinkOperation"),
            input = schema.new({ type = "structure" }),
            output = types.KitchenSinkOperationOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            Boolean = false,
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("parses_blob_shapes", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.1",
            },
            body = http.string_reader([[{"Blob":"YmluYXJ5LXZhbHVl"}]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "KitchenSinkOperation"),
            input = schema.new({ type = "structure" }),
            output = types.KitchenSinkOperationOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            Blob = "binary-value",
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("parses_timestamp_shapes", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.1",
            },
            body = http.string_reader([[{"Timestamp":946845296}]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "KitchenSinkOperation"),
            input = schema.new({ type = "structure" }),
            output = types.KitchenSinkOperationOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            Timestamp = 946845296,
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("parses_iso8601_timestamps", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.1",
            },
            body = http.string_reader([[{"Iso8601Timestamp":"2000-01-02T20:34:56Z"}]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "KitchenSinkOperation"),
            input = schema.new({ type = "structure" }),
            output = types.KitchenSinkOperationOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            Iso8601Timestamp = 946845296,
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("parses_httpdate_timestamps", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.1",
            },
            body = http.string_reader([[{"HttpdateTimestamp":"Sun, 02 Jan 2000 20:34:56 GMT"}]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "KitchenSinkOperation"),
            input = schema.new({ type = "structure" }),
            output = types.KitchenSinkOperationOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            HttpdateTimestamp = 946845296,
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("parses_list_shapes", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.1",
            },
            body = http.string_reader([[{"ListOfStrings":["abc","mno","xyz"]}]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "KitchenSinkOperation"),
            input = schema.new({ type = "structure" }),
            output = types.KitchenSinkOperationOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            ListOfStrings = {
            "abc",
            "mno",
            "xyz",
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("parses_list_of_map_shapes", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.1",
            },
            body = http.string_reader([[{"ListOfMapsOfStrings":[{"size":"large"},{"color":"red"}]}]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "KitchenSinkOperation"),
            input = schema.new({ type = "structure" }),
            output = types.KitchenSinkOperationOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            ListOfMapsOfStrings = {
            {
            size = "large",
        },
            {
            color = "red",
        },
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("parses_list_of_list_shapes", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.1",
            },
            body = http.string_reader([=[{"ListOfLists":[["abc","mno","xyz"],["hjk","qrs","tuv"]]}]=]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "KitchenSinkOperation"),
            input = schema.new({ type = "structure" }),
            output = types.KitchenSinkOperationOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            ListOfLists = {
            {
            "abc",
            "mno",
            "xyz",
        },
            {
            "hjk",
            "qrs",
            "tuv",
        },
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("parses_list_of_structure_shapes", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.1",
            },
            body = http.string_reader([[{"ListOfStructs":[{"Value":"value-1"},{"Value":"value-2"}]}]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "KitchenSinkOperation"),
            input = schema.new({ type = "structure" }),
            output = types.KitchenSinkOperationOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            ListOfStructs = {
            {
            Value = "value-1",
        },
            {
            Value = "value-2",
        },
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("parses_list_of_recursive_structure_shapes", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.1",
            },
            body = http.string_reader([[{"RecursiveList":[{"RecursiveList":[{"RecursiveList":[{"String":"value"}]}]}]}]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "KitchenSinkOperation"),
            input = schema.new({ type = "structure" }),
            output = types.KitchenSinkOperationOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            RecursiveList = {
            {
            RecursiveList = {
            {
            RecursiveList = {
            {
            String = "value",
        },
        },
        },
        },
        },
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("parses_map_shapes", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.1",
            },
            body = http.string_reader([[{"MapOfStrings":{"size":"large","color":"red"}}]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "KitchenSinkOperation"),
            input = schema.new({ type = "structure" }),
            output = types.KitchenSinkOperationOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            MapOfStrings = {
            size = "large",
            color = "red",
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("parses_map_of_list_shapes", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.1",
            },
            body = http.string_reader([[{"MapOfListsOfStrings":{"sizes":["large","small"],"colors":["red","green"]}}]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "KitchenSinkOperation"),
            input = schema.new({ type = "structure" }),
            output = types.KitchenSinkOperationOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            MapOfListsOfStrings = {
            sizes = {
            "large",
            "small",
        },
            colors = {
            "red",
            "green",
        },
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("parses_map_of_map_shapes", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.1",
            },
            body = http.string_reader([[{"MapOfMaps":{"sizes":{"large":"L","medium":"M"},"colors":{"red":"R","blue":"B"}}}]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "KitchenSinkOperation"),
            input = schema.new({ type = "structure" }),
            output = types.KitchenSinkOperationOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            MapOfMaps = {
            sizes = {
            large = "L",
            medium = "M",
        },
            colors = {
            red = "R",
            blue = "B",
        },
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("parses_map_of_structure_shapes", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.1",
            },
            body = http.string_reader([[{"MapOfStructs":{"size":{"Value":"small"},"color":{"Value":"red"}}}]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "KitchenSinkOperation"),
            input = schema.new({ type = "structure" }),
            output = types.KitchenSinkOperationOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            MapOfStructs = {
            size = {
            Value = "small",
        },
            color = {
            Value = "red",
        },
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("parses_map_of_recursive_structure_shapes", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.1",
            },
            body = http.string_reader([[{"RecursiveMap":{"key-1":{"RecursiveMap":{"key-2":{"RecursiveMap":{"key-3":{"String":"value"}}}}}}}]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "KitchenSinkOperation"),
            input = schema.new({ type = "structure" }),
            output = types.KitchenSinkOperationOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            RecursiveMap = {
            ["key-1"] = {
            RecursiveMap = {
            ["key-2"] = {
            RecursiveMap = {
            ["key-3"] = {
            String = "value",
        },
        },
        },
        },
        },
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("parses_the_request_id_from_the_response", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.1",
                ["X-Amzn-Requestid"] = "amazon-uniq-request-id",
            },
            body = http.string_reader([[{}]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "KitchenSinkOperation"),
            input = schema.new({ type = "structure" }),
            output = types.KitchenSinkOperationOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
    end)

end)
