-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: awsJson1_1

local types = require("jsonprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.awsjson")
local protocol = protocol_mod.new({ version = "1.1" })

local service = schema.service({
    id = shape_id.from("aws.protocoltests.json", "JsonProtocol"),
    version = "2018-01-01",
    traits = {},
})

describe("JsonUnions request", function()
    it("AwsJson11SerializeStringUnionValue", function()
        local input = {
            contents = {
            stringValue = "foo",
        },
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "JsonUnions"),
            input = types.JsonUnionsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-amz-json-1.1")
        h.assert_header(request, "X-Amz-Target", "JsonProtocol.JsonUnions")
        local body_str = h.read_body(request.body)
        h.assert_json_eq(body_str, [[{
            "contents": {
                "stringValue": "foo"
            }
        }]])
    end)

    it("AwsJson11SerializeBooleanUnionValue", function()
        local input = {
            contents = {
            booleanValue = true,
        },
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "JsonUnions"),
            input = types.JsonUnionsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-amz-json-1.1")
        h.assert_header(request, "X-Amz-Target", "JsonProtocol.JsonUnions")
        local body_str = h.read_body(request.body)
        h.assert_json_eq(body_str, [[{
            "contents": {
                "booleanValue": true
            }
        }]])
    end)

    it("AwsJson11SerializeNumberUnionValue", function()
        local input = {
            contents = {
            numberValue = 1,
        },
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "JsonUnions"),
            input = types.JsonUnionsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-amz-json-1.1")
        h.assert_header(request, "X-Amz-Target", "JsonProtocol.JsonUnions")
        local body_str = h.read_body(request.body)
        h.assert_json_eq(body_str, [[{
            "contents": {
                "numberValue": 1
            }
        }]])
    end)

    it("AwsJson11SerializeBlobUnionValue", function()
        local input = {
            contents = {
            blobValue = "foo",
        },
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "JsonUnions"),
            input = types.JsonUnionsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-amz-json-1.1")
        h.assert_header(request, "X-Amz-Target", "JsonProtocol.JsonUnions")
        local body_str = h.read_body(request.body)
        h.assert_json_eq(body_str, [[{
            "contents": {
                "blobValue": "Zm9v"
            }
        }]])
    end)

    it("AwsJson11SerializeTimestampUnionValue", function()
        local input = {
            contents = {
            timestampValue = 1398796238,
        },
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "JsonUnions"),
            input = types.JsonUnionsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-amz-json-1.1")
        h.assert_header(request, "X-Amz-Target", "JsonProtocol.JsonUnions")
        local body_str = h.read_body(request.body)
        h.assert_json_eq(body_str, [[{
            "contents": {
                "timestampValue": 1398796238
            }
        }]])
    end)

    it("AwsJson11SerializeEnumUnionValue", function()
        local input = {
            contents = {
            enumValue = "Foo",
        },
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "JsonUnions"),
            input = types.JsonUnionsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-amz-json-1.1")
        h.assert_header(request, "X-Amz-Target", "JsonProtocol.JsonUnions")
        local body_str = h.read_body(request.body)
        h.assert_json_eq(body_str, [[{
            "contents": {
                "enumValue": "Foo"
            }
        }]])
    end)

    it("AwsJson11SerializeListUnionValue", function()
        local input = {
            contents = {
            listValue = {
            "foo",
            "bar",
        },
        },
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "JsonUnions"),
            input = types.JsonUnionsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-amz-json-1.1")
        h.assert_header(request, "X-Amz-Target", "JsonProtocol.JsonUnions")
        local body_str = h.read_body(request.body)
        h.assert_json_eq(body_str, [[{
            "contents": {
                "listValue": ["foo", "bar"]
            }
        }]])
    end)

    it("AwsJson11SerializeMapUnionValue", function()
        local input = {
            contents = {
            mapValue = {
            foo = "bar",
            spam = "eggs",
        },
        },
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "JsonUnions"),
            input = types.JsonUnionsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-amz-json-1.1")
        h.assert_header(request, "X-Amz-Target", "JsonProtocol.JsonUnions")
        local body_str = h.read_body(request.body)
        h.assert_json_eq(body_str, [[{
            "contents": {
                "mapValue": {
                    "foo": "bar",
                    "spam": "eggs"
                }
            }
        }]])
    end)

    it("AwsJson11SerializeStructureUnionValue", function()
        local input = {
            contents = {
            structureValue = {
            hi = "hello",
        },
        },
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "JsonUnions"),
            input = types.JsonUnionsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-amz-json-1.1")
        h.assert_header(request, "X-Amz-Target", "JsonProtocol.JsonUnions")
        local body_str = h.read_body(request.body)
        h.assert_json_eq(body_str, [[{
            "contents": {
                "structureValue": {
                    "hi": "hello"
                }
            }
        }]])
    end)

end)
