-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: awsJson1_1

local types = require("jsonprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.awsjson")
local protocol = protocol_mod.new({ version = "1.1" })

local service = schema.service({
    id = shape_id.from("aws.protocoltests.json", "JsonProtocol"),
    version = "2018-01-01",
    traits = {},
})

describe("SimpleScalarProperties response", function()
    it("AwsJson11SupportsNaNFloatInputs", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.1",
            },
            body = http.string_reader([[{
                "floatValue": "NaN",
                "doubleValue": "NaN"
            }]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "SimpleScalarProperties"),
            input = schema.new({ type = "structure" }),
            output = types.SimpleScalarPropertiesOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            floatValue = 0/0,
            doubleValue = 0/0,
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("AwsJson11SupportsInfinityFloatInputs", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.1",
            },
            body = http.string_reader([[{
                "floatValue": "Infinity",
                "doubleValue": "Infinity"
            }]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "SimpleScalarProperties"),
            input = schema.new({ type = "structure" }),
            output = types.SimpleScalarPropertiesOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            floatValue = math.huge,
            doubleValue = math.huge,
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("AwsJson11SupportsNegativeInfinityFloatInputs", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.1",
            },
            body = http.string_reader([[{
                "floatValue": "-Infinity",
                "doubleValue": "-Infinity"
            }]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json", "SimpleScalarProperties"),
            input = schema.new({ type = "structure" }),
            output = types.SimpleScalarPropertiesOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            floatValue = -math.huge,
            doubleValue = -math.huge,
        }
        h.assert_deep_eq(output, expected, "output")
    end)

end)
