-- Code generated by lua-client-codegen. DO NOT EDIT.

local id = require("smithy.shape_id")
local schema = require("smithy.schema")
local prelude = require("smithy.prelude")
local traits = require("smithy.traits")

local _N = "aws.protocoltests.query"

local M = {}

M.StringList = schema.new({ type = "list", list_member = prelude.String })

M.GreetingList = schema.new({ type = "list", list_member = M.GreetingStruct })

M.ListWithXmlName = schema.new({ type = "list", list_member = prelude.String })

M.StringMap = schema.new({ type = "map", map_key = prelude.String, map_value = prelude.String })

M.ComplexMap = schema.new({ type = "map", map_key = prelude.String, map_value = M.GreetingStruct })

M.MapWithXmlName = schema.new({ type = "map", map_key = prelude.String, map_value = prelude.String })

M.MapOfLists = schema.new({ type = "map", map_key = prelude.String, map_value = M.StringList })

M.XmlMapsOutputMap = schema.new({ type = "map", map_key = prelude.String, map_value = M.GreetingStruct })

M.XmlMapsXmlNameOutputMap = schema.new({ type = "map", map_key = prelude.String, map_value = M.GreetingStruct })

M.FooEnumMap = schema.new({ type = "map", map_key = prelude.String, map_value = prelude.String })

M.FlattenedXmlMapWithXmlNameOutputMap = schema.new({ type = "map", map_key = prelude.String, map_value = prelude.String })

M.FlattenedXmlMapWithXmlNamespaceOutputMap = schema.new({ type = "map", map_key = prelude.String, map_value = prelude.String })

M.StringSet = schema.new({ type = "list", list_member = prelude.String })

M.IntegerList = schema.new({ type = "list", list_member = prelude.Integer })

M.BooleanList = schema.new({ type = "list", list_member = prelude.Boolean })

M.TimestampList = schema.new({ type = "list", list_member = prelude.Timestamp })

M.FooEnumList = schema.new({ type = "list", list_member = prelude.String })

M.IntegerEnumList = schema.new({ type = "list", list_member = prelude.Integer })

M.NestedStringList = schema.new({ type = "list", list_member = M.StringList })

M.RenamedListMembers = schema.new({ type = "list", list_member = prelude.String })

M.ListWithMemberNamespace = schema.new({ type = "list", list_member = prelude.String })

M.ListWithNamespace = schema.new({ type = "list", list_member = prelude.String })

M.StructureList = schema.new({ type = "list", list_member = M.StructureListMember })

M.FooEnumSet = schema.new({ type = "list", list_member = prelude.String })

M.IntegerEnumSet = schema.new({ type = "list", list_member = prelude.Integer })

M.IntegerEnumMap = schema.new({ type = "map", map_key = prelude.String, map_value = prelude.Integer })

M.XmlNamespacedList = schema.new({ type = "list", list_member = prelude.String })

M.DatetimeOffsetsInput = prelude.Unit

M.DatetimeOffsetsOutput = schema.new({
    id = id.from(_N, "DatetimeOffsetsOutput"),
    type = "structure",
    members = {
        datetime = schema.new({
            id = id.from(_N, "DatetimeOffsetsOutput", "datetime"),
            type = "timestamp",
            name = "datetime",
            target_id = prelude.Timestamp.id,
            traits = {
                [traits.TIMESTAMP_FORMAT] = { format = "date-time" },
            },
        }),
    },
})

M.EmptyInputAndEmptyOutputInput = schema.new({
    id = id.from(_N, "EmptyInputAndEmptyOutputInput"),
    type = "structure",
})

M.EmptyInputAndEmptyOutputOutput = schema.new({
    id = id.from(_N, "EmptyInputAndEmptyOutputOutput"),
    type = "structure",
})

M.EndpointOperationInput = prelude.Unit

M.EndpointOperationOutput = prelude.Unit

M.EndpointWithHostLabelOperationInput = schema.new({
    id = id.from(_N, "HostLabelInput"),
    type = "structure",
    members = {
        label = schema.new({
            id = id.from(_N, "EndpointWithHostLabelOperationInput", "label"),
            type = "string",
            name = "label",
            target_id = prelude.String.id,
            traits = {
                [traits.REQUIRED] = {},
            },
        }),
    },
})

M.EndpointWithHostLabelOperationOutput = prelude.Unit

M.FlattenedXmlMapInput = prelude.Unit

M.FlattenedXmlMapOutput = schema.new({
    id = id.from(_N, "FlattenedXmlMapOutput"),
    type = "structure",
    members = {
        myMap = schema.new({
            id = id.from(_N, "FlattenedXmlMapOutput", "myMap"),
            type = "map",
            name = "myMap",
            target_id = prelude.Document.id,
            map_key = prelude.String,
            map_value = prelude.String,
            traits = {
                [traits.XML_FLATTENED] = {},
            },
        }),
    },
})

M.FlattenedXmlMapWithXmlNameInput = prelude.Unit

M.FlattenedXmlMapWithXmlNameOutput = schema.new({
    id = id.from(_N, "FlattenedXmlMapWithXmlNameOutput"),
    type = "structure",
    members = {
        myMap = schema.new({
            id = id.from(_N, "FlattenedXmlMapWithXmlNameOutput", "myMap"),
            type = "map",
            name = "myMap",
            target_id = prelude.Document.id,
            map_key = schema.new({ type = "string", traits = { [traits.XML_NAME] = { name = "K" } } }),
            map_value = schema.new({ type = "string", target = prelude.String, traits = { [traits.XML_NAME] = { name = "V" } } }),
            traits = {
                [traits.XML_NAME] = { name = "KVP" },
                [traits.XML_FLATTENED] = {},
            },
        }),
    },
})

M.FlattenedXmlMapWithXmlNamespaceInput = prelude.Unit

M.FlattenedXmlMapWithXmlNamespaceOutput = schema.new({
    id = id.from(_N, "FlattenedXmlMapWithXmlNamespaceOutput"),
    type = "structure",
    members = {
        myMap = schema.new({
            id = id.from(_N, "FlattenedXmlMapWithXmlNamespaceOutput", "myMap"),
            type = "map",
            name = "myMap",
            target_id = prelude.Document.id,
            map_key = schema.new({ type = "string", traits = { [traits.XML_NAME] = { name = "K" }, [traits.XML_NAMESPACE] = { uri = "https://the-key.example.com" } } }),
            map_value = schema.new({ type = "string", target = prelude.String, traits = { [traits.XML_NAME] = { name = "V" }, [traits.XML_NAMESPACE] = { uri = "https://the-value.example.com" } } }),
            traits = {
                [traits.XML_NAME] = { name = "KVP" },
                [traits.XML_FLATTENED] = {},
                [traits.XML_NAMESPACE] = { uri = "https://the-member.example.com" },
            },
        }),
    },
})

M.FractionalSecondsInput = prelude.Unit

M.FractionalSecondsOutput = schema.new({
    id = id.from(_N, "FractionalSecondsOutput"),
    type = "structure",
    members = {
        datetime = schema.new({
            id = id.from(_N, "FractionalSecondsOutput", "datetime"),
            type = "timestamp",
            name = "datetime",
            target_id = prelude.Timestamp.id,
            traits = {
                [traits.TIMESTAMP_FORMAT] = { format = "date-time" },
            },
        }),
    },
})

M.ComplexNestedErrorData = schema.new({
    id = id.from(_N, "ComplexNestedErrorData"),
    type = "structure",
    members = {
        Foo = schema.new({
            id = id.from(_N, "ComplexNestedErrorData", "Foo"),
            type = "string",
            name = "Foo",
            target_id = prelude.String.id,
        }),
    },
})

M.ComplexError = schema.new({
    id = id.from(_N, "ComplexError"),
    type = "structure",
    traits = {
        [traits.ERROR] = { value = "client" },
    },
    members = {
        TopLevel = schema.new({
            id = id.from(_N, "ComplexError", "TopLevel"),
            type = "string",
            name = "TopLevel",
            target_id = prelude.String.id,
        }),
        Nested = schema.new({
            id = id.from(_N, "ComplexError", "Nested"),
            type = "structure",
            name = "Nested",
            target_id = id.from(_N, "ComplexNestedErrorData"),
            target = M.ComplexNestedErrorData,
        }),
    },
})

M.CustomCodeError = schema.new({
    id = id.from(_N, "CustomCodeError"),
    type = "structure",
    traits = {
        [traits.ERROR] = { value = "client" },
    },
    members = {
        Message = schema.new({
            id = id.from(_N, "CustomCodeError", "Message"),
            type = "string",
            name = "Message",
            target_id = prelude.String.id,
        }),
    },
})

M.GreetingWithErrorsInput = prelude.Unit

M.GreetingWithErrorsOutput = schema.new({
    id = id.from(_N, "GreetingWithErrorsOutput"),
    type = "structure",
    members = {
        greeting = schema.new({
            id = id.from(_N, "GreetingWithErrorsOutput", "greeting"),
            type = "string",
            name = "greeting",
            target_id = prelude.String.id,
        }),
    },
})

M.InvalidGreeting = schema.new({
    id = id.from(_N, "InvalidGreeting"),
    type = "structure",
    traits = {
        [traits.ERROR] = { value = "client" },
    },
    members = {
        Message = schema.new({
            id = id.from(_N, "InvalidGreeting", "Message"),
            type = "string",
            name = "Message",
            target_id = prelude.String.id,
        }),
    },
})

M.HostWithPathOperationInput = prelude.Unit

M.HostWithPathOperationOutput = prelude.Unit

M.IgnoresWrappingXmlNameInput = prelude.Unit

M.IgnoresWrappingXmlNameOutput = schema.new({
    id = id.from(_N, "IgnoresWrappingXmlNameOutput"),
    type = "structure",
    traits = {
        [traits.XML_NAME] = { name = "IgnoreMe" },
    },
    members = {
        foo = schema.new({
            id = id.from(_N, "IgnoresWrappingXmlNameOutput", "foo"),
            type = "string",
            name = "foo",
            target_id = prelude.String.id,
        }),
    },
})

M.NestedStructuresOutput = prelude.Unit

M.NoInputAndNoOutputInput = prelude.Unit

M.NoInputAndNoOutputOutput = prelude.Unit

M.NoInputAndOutputInput = schema.new({
    id = id.from(_N, "NoInputAndOutputInput"),
    type = "structure",
})

M.NoInputAndOutputOutput = schema.new({
    id = id.from(_N, "NoInputAndOutputOutput"),
    type = "structure",
})

M.PutWithContentEncodingInput = schema.new({
    id = id.from(_N, "PutWithContentEncodingInput"),
    type = "structure",
    members = {
        encoding = schema.new({
            id = id.from(_N, "PutWithContentEncodingInput", "encoding"),
            type = "string",
            name = "encoding",
            target_id = prelude.String.id,
            traits = {
                [traits.HTTP_HEADER] = { name = "Content-Encoding" },
            },
        }),
        data = schema.new({
            id = id.from(_N, "PutWithContentEncodingInput", "data"),
            type = "string",
            name = "data",
            target_id = prelude.String.id,
        }),
    },
})

M.PutWithContentEncodingOutput = prelude.Unit

M.QueryIdempotencyTokenAutoFillInput = schema.new({
    id = id.from(_N, "QueryIdempotencyTokenAutoFillInput"),
    type = "structure",
    members = {
        token = schema.new({
            id = id.from(_N, "QueryIdempotencyTokenAutoFillInput", "token"),
            type = "string",
            name = "token",
            target_id = prelude.String.id,
            traits = {
                [traits.IDEMPOTENCY_TOKEN] = {},
            },
        }),
    },
})

M.QueryIdempotencyTokenAutoFillOutput = prelude.Unit

M.GreetingStruct = schema.new({
    id = id.from(_N, "GreetingStruct"),
    type = "structure",
    members = {
        hi = schema.new({
            id = id.from(_N, "GreetingStruct", "hi"),
            type = "string",
            name = "hi",
            target_id = prelude.String.id,
        }),
    },
})

M.NestedStructWithList = schema.new({
    id = id.from(_N, "NestedStructWithList"),
    type = "structure",
    members = {
        ListArg = schema.new({
            id = id.from(_N, "NestedStructWithList", "ListArg"),
            type = "list",
            name = "ListArg",
            target_id = prelude.Document.id,
            list_member = prelude.String,
        }),
    },
})

M.QueryListsInput = schema.new({
    id = id.from(_N, "QueryListsInput"),
    type = "structure",
    members = {
        ListArg = schema.new({
            id = id.from(_N, "QueryListsInput", "ListArg"),
            type = "list",
            name = "ListArg",
            target_id = prelude.Document.id,
            list_member = prelude.String,
        }),
        ComplexListArg = schema.new({
            id = id.from(_N, "QueryListsInput", "ComplexListArg"),
            type = "list",
            name = "ComplexListArg",
            target_id = prelude.Document.id,
            list_member = M.GreetingStruct,
        }),
        FlattenedListArg = schema.new({
            id = id.from(_N, "QueryListsInput", "FlattenedListArg"),
            type = "list",
            name = "FlattenedListArg",
            target_id = prelude.Document.id,
            list_member = prelude.String,
            traits = {
                [traits.XML_FLATTENED] = {},
            },
        }),
        ListArgWithXmlNameMember = schema.new({
            id = id.from(_N, "QueryListsInput", "ListArgWithXmlNameMember"),
            type = "list",
            name = "ListArgWithXmlNameMember",
            target_id = prelude.Document.id,
            list_member = schema.new({ type = "string", target = prelude.String, traits = { [traits.XML_NAME] = { name = "item" } } }),
        }),
        FlattenedListArgWithXmlName = schema.new({
            id = id.from(_N, "QueryListsInput", "FlattenedListArgWithXmlName"),
            type = "list",
            name = "FlattenedListArgWithXmlName",
            target_id = prelude.Document.id,
            list_member = schema.new({ type = "string", target = prelude.String, traits = { [traits.XML_NAME] = { name = "item" } } }),
            traits = {
                [traits.XML_NAME] = { name = "Hi" },
                [traits.XML_FLATTENED] = {},
            },
        }),
        NestedWithList = schema.new({
            id = id.from(_N, "QueryListsInput", "NestedWithList"),
            type = "structure",
            name = "NestedWithList",
            target_id = id.from(_N, "NestedStructWithList"),
            target = M.NestedStructWithList,
        }),
    },
})

M.QueryListsOutput = prelude.Unit

M.NestedStructWithMap = schema.new({
    id = id.from(_N, "NestedStructWithMap"),
    type = "structure",
    members = {
        MapArg = schema.new({
            id = id.from(_N, "NestedStructWithMap", "MapArg"),
            type = "map",
            name = "MapArg",
            target_id = prelude.Document.id,
            map_key = prelude.String,
            map_value = prelude.String,
        }),
    },
})

M.QueryMapsInput = schema.new({
    id = id.from(_N, "QueryMapsInput"),
    type = "structure",
    members = {
        MapArg = schema.new({
            id = id.from(_N, "QueryMapsInput", "MapArg"),
            type = "map",
            name = "MapArg",
            target_id = prelude.Document.id,
            map_key = prelude.String,
            map_value = prelude.String,
        }),
        RenamedMapArg = schema.new({
            id = id.from(_N, "QueryMapsInput", "RenamedMapArg"),
            type = "map",
            name = "RenamedMapArg",
            target_id = prelude.Document.id,
            map_key = prelude.String,
            map_value = prelude.String,
            traits = {
                [traits.XML_NAME] = { name = "Foo" },
            },
        }),
        ComplexMapArg = schema.new({
            id = id.from(_N, "QueryMapsInput", "ComplexMapArg"),
            type = "map",
            name = "ComplexMapArg",
            target_id = prelude.Document.id,
            map_key = prelude.String,
            map_value = M.GreetingStruct,
        }),
        MapWithXmlMemberName = schema.new({
            id = id.from(_N, "QueryMapsInput", "MapWithXmlMemberName"),
            type = "map",
            name = "MapWithXmlMemberName",
            target_id = prelude.Document.id,
            map_key = schema.new({ type = "string", traits = { [traits.XML_NAME] = { name = "K" } } }),
            map_value = schema.new({ type = "string", target = prelude.String, traits = { [traits.XML_NAME] = { name = "V" } } }),
        }),
        FlattenedMap = schema.new({
            id = id.from(_N, "QueryMapsInput", "FlattenedMap"),
            type = "map",
            name = "FlattenedMap",
            target_id = prelude.Document.id,
            map_key = prelude.String,
            map_value = prelude.String,
            traits = {
                [traits.XML_FLATTENED] = {},
            },
        }),
        FlattenedMapWithXmlName = schema.new({
            id = id.from(_N, "QueryMapsInput", "FlattenedMapWithXmlName"),
            type = "map",
            name = "FlattenedMapWithXmlName",
            target_id = prelude.Document.id,
            map_key = schema.new({ type = "string", traits = { [traits.XML_NAME] = { name = "K" } } }),
            map_value = schema.new({ type = "string", target = prelude.String, traits = { [traits.XML_NAME] = { name = "V" } } }),
            traits = {
                [traits.XML_NAME] = { name = "Hi" },
                [traits.XML_FLATTENED] = {},
            },
        }),
        MapOfLists = schema.new({
            id = id.from(_N, "QueryMapsInput", "MapOfLists"),
            type = "map",
            name = "MapOfLists",
            target_id = prelude.Document.id,
            map_key = prelude.String,
            map_value = schema.new({ type = "list", list_member = prelude.String }),
        }),
        NestedStructWithMap = schema.new({
            id = id.from(_N, "QueryMapsInput", "NestedStructWithMap"),
            type = "structure",
            name = "NestedStructWithMap",
            target_id = id.from(_N, "NestedStructWithMap"),
            target = M.NestedStructWithMap,
        }),
    },
})

M.QueryMapsOutput = prelude.Unit

M.QueryTimestampsInput = schema.new({
    id = id.from(_N, "QueryTimestampsInput"),
    type = "structure",
    members = {
        normalFormat = schema.new({
            id = id.from(_N, "QueryTimestampsInput", "normalFormat"),
            type = "timestamp",
            name = "normalFormat",
            target_id = prelude.Timestamp.id,
        }),
        epochMember = schema.new({
            id = id.from(_N, "QueryTimestampsInput", "epochMember"),
            type = "timestamp",
            name = "epochMember",
            target_id = prelude.Timestamp.id,
            traits = {
                [traits.TIMESTAMP_FORMAT] = { format = "epoch-seconds" },
            },
        }),
        epochTarget = schema.new({
            id = id.from(_N, "QueryTimestampsInput", "epochTarget"),
            type = "timestamp",
            name = "epochTarget",
            target_id = prelude.Timestamp.id,
            traits = {
                [traits.TIMESTAMP_FORMAT] = { format = "epoch-seconds" },
            },
        }),
    },
})

M.QueryTimestampsOutput = prelude.Unit

M.RecursiveXmlShapesInput = prelude.Unit

M.SimpleInputParamsInput = schema.new({
    id = id.from(_N, "SimpleInputParamsInput"),
    type = "structure",
    members = {
        Foo = schema.new({
            id = id.from(_N, "SimpleInputParamsInput", "Foo"),
            type = "string",
            name = "Foo",
            target_id = prelude.String.id,
        }),
        Bar = schema.new({
            id = id.from(_N, "SimpleInputParamsInput", "Bar"),
            type = "string",
            name = "Bar",
            target_id = prelude.String.id,
        }),
        Baz = schema.new({
            id = id.from(_N, "SimpleInputParamsInput", "Baz"),
            type = "boolean",
            name = "Baz",
            target_id = prelude.Boolean.id,
        }),
        Bam = schema.new({
            id = id.from(_N, "SimpleInputParamsInput", "Bam"),
            type = "integer",
            name = "Bam",
            target_id = prelude.Integer.id,
        }),
        FloatValue = schema.new({
            id = id.from(_N, "SimpleInputParamsInput", "FloatValue"),
            type = "float",
            name = "FloatValue",
            target_id = prelude.Float.id,
        }),
        Boo = schema.new({
            id = id.from(_N, "SimpleInputParamsInput", "Boo"),
            type = "double",
            name = "Boo",
            target_id = prelude.Double.id,
        }),
        Qux = schema.new({
            id = id.from(_N, "SimpleInputParamsInput", "Qux"),
            type = "blob",
            name = "Qux",
            target_id = prelude.Blob.id,
        }),
        FooEnum = schema.new({
            id = id.from(_N, "SimpleInputParamsInput", "FooEnum"),
            type = "string",
            name = "FooEnum",
            target_id = prelude.String.id,
        }),
        IntegerEnum = schema.new({
            id = id.from(_N, "SimpleInputParamsInput", "IntegerEnum"),
            type = "number",
            name = "IntegerEnum",
            target_id = prelude.Integer.id,
        }),
    },
})

M.SimpleInputParamsOutput = prelude.Unit

M.SimpleScalarXmlPropertiesInput = prelude.Unit

M.SimpleScalarXmlPropertiesOutput = schema.new({
    id = id.from(_N, "SimpleScalarXmlPropertiesOutput"),
    type = "structure",
    members = {
        stringValue = schema.new({
            id = id.from(_N, "SimpleScalarXmlPropertiesOutput", "stringValue"),
            type = "string",
            name = "stringValue",
            target_id = prelude.String.id,
        }),
        emptyStringValue = schema.new({
            id = id.from(_N, "SimpleScalarXmlPropertiesOutput", "emptyStringValue"),
            type = "string",
            name = "emptyStringValue",
            target_id = prelude.String.id,
        }),
        trueBooleanValue = schema.new({
            id = id.from(_N, "SimpleScalarXmlPropertiesOutput", "trueBooleanValue"),
            type = "boolean",
            name = "trueBooleanValue",
            target_id = prelude.Boolean.id,
        }),
        falseBooleanValue = schema.new({
            id = id.from(_N, "SimpleScalarXmlPropertiesOutput", "falseBooleanValue"),
            type = "boolean",
            name = "falseBooleanValue",
            target_id = prelude.Boolean.id,
        }),
        byteValue = schema.new({
            id = id.from(_N, "SimpleScalarXmlPropertiesOutput", "byteValue"),
            type = "byte",
            name = "byteValue",
            target_id = prelude.Byte.id,
        }),
        shortValue = schema.new({
            id = id.from(_N, "SimpleScalarXmlPropertiesOutput", "shortValue"),
            type = "short",
            name = "shortValue",
            target_id = prelude.Short.id,
        }),
        integerValue = schema.new({
            id = id.from(_N, "SimpleScalarXmlPropertiesOutput", "integerValue"),
            type = "integer",
            name = "integerValue",
            target_id = prelude.Integer.id,
        }),
        longValue = schema.new({
            id = id.from(_N, "SimpleScalarXmlPropertiesOutput", "longValue"),
            type = "long",
            name = "longValue",
            target_id = prelude.Long.id,
        }),
        floatValue = schema.new({
            id = id.from(_N, "SimpleScalarXmlPropertiesOutput", "floatValue"),
            type = "float",
            name = "floatValue",
            target_id = prelude.Float.id,
        }),
        doubleValue = schema.new({
            id = id.from(_N, "SimpleScalarXmlPropertiesOutput", "doubleValue"),
            type = "double",
            name = "doubleValue",
            target_id = prelude.Double.id,
            traits = {
                [traits.XML_NAME] = { name = "DoubleDribble" },
            },
        }),
    },
})

M.XmlBlobsInput = prelude.Unit

M.XmlBlobsOperationOutput = schema.new({
    id = id.from(_N, "XmlBlobsOutput"),
    type = "structure",
    members = {
        data = schema.new({
            id = id.from(_N, "XmlBlobsOperationOutput", "data"),
            type = "blob",
            name = "data",
            target_id = prelude.Blob.id,
        }),
    },
})

M.XmlEmptyBlobsInput = prelude.Unit

M.XmlEmptyBlobsOutput = schema.new({
    id = id.from(_N, "XmlBlobsOutput"),
    type = "structure",
    members = {
        data = schema.new({
            id = id.from(_N, "XmlEmptyBlobsOutput", "data"),
            type = "blob",
            name = "data",
            target_id = prelude.Blob.id,
        }),
    },
})

M.XmlEmptyListsInput = prelude.Unit

M.StructureListMember = schema.new({
    id = id.from(_N, "StructureListMember"),
    type = "structure",
    members = {
        a = schema.new({
            id = id.from(_N, "StructureListMember", "a"),
            type = "string",
            name = "a",
            target_id = prelude.String.id,
            traits = {
                [traits.XML_NAME] = { name = "value" },
            },
        }),
        b = schema.new({
            id = id.from(_N, "StructureListMember", "b"),
            type = "string",
            name = "b",
            target_id = prelude.String.id,
            traits = {
                [traits.XML_NAME] = { name = "other" },
            },
        }),
    },
})

M.XmlEmptyListsOutput = schema.new({
    id = id.from(_N, "XmlListsOutput"),
    type = "structure",
    members = {
        stringList = schema.new({
            id = id.from(_N, "XmlEmptyListsOutput", "stringList"),
            type = "list",
            name = "stringList",
            target_id = prelude.Document.id,
            list_member = prelude.String,
        }),
        stringSet = schema.new({
            id = id.from(_N, "XmlEmptyListsOutput", "stringSet"),
            type = "list",
            name = "stringSet",
            target_id = prelude.Document.id,
            list_member = prelude.String,
        }),
        integerList = schema.new({
            id = id.from(_N, "XmlEmptyListsOutput", "integerList"),
            type = "list",
            name = "integerList",
            target_id = prelude.Document.id,
            list_member = prelude.Integer,
        }),
        booleanList = schema.new({
            id = id.from(_N, "XmlEmptyListsOutput", "booleanList"),
            type = "list",
            name = "booleanList",
            target_id = prelude.Document.id,
            list_member = prelude.Boolean,
        }),
        timestampList = schema.new({
            id = id.from(_N, "XmlEmptyListsOutput", "timestampList"),
            type = "list",
            name = "timestampList",
            target_id = prelude.Document.id,
            list_member = prelude.Timestamp,
        }),
        enumList = schema.new({
            id = id.from(_N, "XmlEmptyListsOutput", "enumList"),
            type = "list",
            name = "enumList",
            target_id = prelude.Document.id,
            list_member = prelude.String,
        }),
        intEnumList = schema.new({
            id = id.from(_N, "XmlEmptyListsOutput", "intEnumList"),
            type = "list",
            name = "intEnumList",
            target_id = prelude.Document.id,
            list_member = prelude.Integer,
        }),
        nestedStringList = schema.new({
            id = id.from(_N, "XmlEmptyListsOutput", "nestedStringList"),
            type = "list",
            name = "nestedStringList",
            target_id = prelude.Document.id,
            list_member = schema.new({ type = "list", list_member = prelude.String }),
        }),
        renamedListMembers = schema.new({
            id = id.from(_N, "XmlEmptyListsOutput", "renamedListMembers"),
            type = "list",
            name = "renamedListMembers",
            target_id = prelude.Document.id,
            list_member = schema.new({ type = "string", target = prelude.String, traits = { [traits.XML_NAME] = { name = "item" } } }),
            traits = {
                [traits.XML_NAME] = { name = "renamed" },
            },
        }),
        flattenedList = schema.new({
            id = id.from(_N, "XmlEmptyListsOutput", "flattenedList"),
            type = "list",
            name = "flattenedList",
            target_id = prelude.Document.id,
            list_member = schema.new({ type = "string", target = prelude.String, traits = { [traits.XML_NAME] = { name = "item" } } }),
            traits = {
                [traits.XML_FLATTENED] = {},
            },
        }),
        flattenedList2 = schema.new({
            id = id.from(_N, "XmlEmptyListsOutput", "flattenedList2"),
            type = "list",
            name = "flattenedList2",
            target_id = prelude.Document.id,
            list_member = schema.new({ type = "string", target = prelude.String, traits = { [traits.XML_NAME] = { name = "item" } } }),
            traits = {
                [traits.XML_NAME] = { name = "customName" },
                [traits.XML_FLATTENED] = {},
            },
        }),
        flattenedListWithMemberNamespace = schema.new({
            id = id.from(_N, "XmlEmptyListsOutput", "flattenedListWithMemberNamespace"),
            type = "list",
            name = "flattenedListWithMemberNamespace",
            target_id = prelude.Document.id,
            list_member = schema.new({ type = "string", target = prelude.String, traits = { [traits.XML_NAMESPACE] = { uri = "https://xml-member.example.com" } } }),
            traits = {
                [traits.XML_FLATTENED] = {},
            },
        }),
        flattenedListWithNamespace = schema.new({
            id = id.from(_N, "XmlEmptyListsOutput", "flattenedListWithNamespace"),
            type = "list",
            name = "flattenedListWithNamespace",
            target_id = prelude.Document.id,
            list_member = prelude.String,
            traits = {
                [traits.XML_FLATTENED] = {},
            },
        }),
        structureList = schema.new({
            id = id.from(_N, "XmlEmptyListsOutput", "structureList"),
            type = "list",
            name = "structureList",
            target_id = prelude.Document.id,
            list_member = schema.new({ type = "structure", target = M.StructureListMember, traits = { [traits.XML_NAME] = { name = "item" } } }),
            traits = {
                [traits.XML_NAME] = { name = "myStructureList" },
            },
        }),
    },
})

M.XmlEmptyMapsInput = prelude.Unit

M.XmlEmptyMapsOutput = schema.new({
    id = id.from(_N, "XmlMapsOutput"),
    type = "structure",
    members = {
        myMap = schema.new({
            id = id.from(_N, "XmlEmptyMapsOutput", "myMap"),
            type = "map",
            name = "myMap",
            target_id = prelude.Document.id,
            map_key = prelude.String,
            map_value = M.GreetingStruct,
        }),
    },
})

M.XmlEnumsInput = prelude.Unit

M.XmlEnumsOutput = schema.new({
    id = id.from(_N, "XmlEnumsOutput"),
    type = "structure",
    members = {
        fooEnum1 = schema.new({
            id = id.from(_N, "XmlEnumsOutput", "fooEnum1"),
            type = "string",
            name = "fooEnum1",
            target_id = prelude.String.id,
        }),
        fooEnum2 = schema.new({
            id = id.from(_N, "XmlEnumsOutput", "fooEnum2"),
            type = "string",
            name = "fooEnum2",
            target_id = prelude.String.id,
        }),
        fooEnum3 = schema.new({
            id = id.from(_N, "XmlEnumsOutput", "fooEnum3"),
            type = "string",
            name = "fooEnum3",
            target_id = prelude.String.id,
        }),
        fooEnumList = schema.new({
            id = id.from(_N, "XmlEnumsOutput", "fooEnumList"),
            type = "list",
            name = "fooEnumList",
            target_id = prelude.Document.id,
            list_member = prelude.String,
        }),
        fooEnumSet = schema.new({
            id = id.from(_N, "XmlEnumsOutput", "fooEnumSet"),
            type = "list",
            name = "fooEnumSet",
            target_id = prelude.Document.id,
            list_member = prelude.String,
        }),
        fooEnumMap = schema.new({
            id = id.from(_N, "XmlEnumsOutput", "fooEnumMap"),
            type = "map",
            name = "fooEnumMap",
            target_id = prelude.Document.id,
            map_key = prelude.String,
            map_value = prelude.String,
        }),
    },
})

M.XmlIntEnumsInput = prelude.Unit

M.XmlIntEnumsOutput = schema.new({
    id = id.from(_N, "XmlIntEnumsOutput"),
    type = "structure",
    members = {
        intEnum1 = schema.new({
            id = id.from(_N, "XmlIntEnumsOutput", "intEnum1"),
            type = "number",
            name = "intEnum1",
            target_id = prelude.Integer.id,
        }),
        intEnum2 = schema.new({
            id = id.from(_N, "XmlIntEnumsOutput", "intEnum2"),
            type = "number",
            name = "intEnum2",
            target_id = prelude.Integer.id,
        }),
        intEnum3 = schema.new({
            id = id.from(_N, "XmlIntEnumsOutput", "intEnum3"),
            type = "number",
            name = "intEnum3",
            target_id = prelude.Integer.id,
        }),
        intEnumList = schema.new({
            id = id.from(_N, "XmlIntEnumsOutput", "intEnumList"),
            type = "list",
            name = "intEnumList",
            target_id = prelude.Document.id,
            list_member = prelude.Integer,
        }),
        intEnumSet = schema.new({
            id = id.from(_N, "XmlIntEnumsOutput", "intEnumSet"),
            type = "list",
            name = "intEnumSet",
            target_id = prelude.Document.id,
            list_member = prelude.Integer,
        }),
        intEnumMap = schema.new({
            id = id.from(_N, "XmlIntEnumsOutput", "intEnumMap"),
            type = "map",
            name = "intEnumMap",
            target_id = prelude.Document.id,
            map_key = prelude.String,
            map_value = prelude.Integer,
        }),
    },
})

M.XmlListsInput = prelude.Unit

M.XmlListsOperationOutput = schema.new({
    id = id.from(_N, "XmlListsOutput"),
    type = "structure",
    members = {
        stringList = schema.new({
            id = id.from(_N, "XmlListsOperationOutput", "stringList"),
            type = "list",
            name = "stringList",
            target_id = prelude.Document.id,
            list_member = prelude.String,
        }),
        stringSet = schema.new({
            id = id.from(_N, "XmlListsOperationOutput", "stringSet"),
            type = "list",
            name = "stringSet",
            target_id = prelude.Document.id,
            list_member = prelude.String,
        }),
        integerList = schema.new({
            id = id.from(_N, "XmlListsOperationOutput", "integerList"),
            type = "list",
            name = "integerList",
            target_id = prelude.Document.id,
            list_member = prelude.Integer,
        }),
        booleanList = schema.new({
            id = id.from(_N, "XmlListsOperationOutput", "booleanList"),
            type = "list",
            name = "booleanList",
            target_id = prelude.Document.id,
            list_member = prelude.Boolean,
        }),
        timestampList = schema.new({
            id = id.from(_N, "XmlListsOperationOutput", "timestampList"),
            type = "list",
            name = "timestampList",
            target_id = prelude.Document.id,
            list_member = prelude.Timestamp,
        }),
        enumList = schema.new({
            id = id.from(_N, "XmlListsOperationOutput", "enumList"),
            type = "list",
            name = "enumList",
            target_id = prelude.Document.id,
            list_member = prelude.String,
        }),
        intEnumList = schema.new({
            id = id.from(_N, "XmlListsOperationOutput", "intEnumList"),
            type = "list",
            name = "intEnumList",
            target_id = prelude.Document.id,
            list_member = prelude.Integer,
        }),
        nestedStringList = schema.new({
            id = id.from(_N, "XmlListsOperationOutput", "nestedStringList"),
            type = "list",
            name = "nestedStringList",
            target_id = prelude.Document.id,
            list_member = schema.new({ type = "list", list_member = prelude.String }),
        }),
        renamedListMembers = schema.new({
            id = id.from(_N, "XmlListsOperationOutput", "renamedListMembers"),
            type = "list",
            name = "renamedListMembers",
            target_id = prelude.Document.id,
            list_member = schema.new({ type = "string", target = prelude.String, traits = { [traits.XML_NAME] = { name = "item" } } }),
            traits = {
                [traits.XML_NAME] = { name = "renamed" },
            },
        }),
        flattenedList = schema.new({
            id = id.from(_N, "XmlListsOperationOutput", "flattenedList"),
            type = "list",
            name = "flattenedList",
            target_id = prelude.Document.id,
            list_member = schema.new({ type = "string", target = prelude.String, traits = { [traits.XML_NAME] = { name = "item" } } }),
            traits = {
                [traits.XML_FLATTENED] = {},
            },
        }),
        flattenedList2 = schema.new({
            id = id.from(_N, "XmlListsOperationOutput", "flattenedList2"),
            type = "list",
            name = "flattenedList2",
            target_id = prelude.Document.id,
            list_member = schema.new({ type = "string", target = prelude.String, traits = { [traits.XML_NAME] = { name = "item" } } }),
            traits = {
                [traits.XML_NAME] = { name = "customName" },
                [traits.XML_FLATTENED] = {},
            },
        }),
        flattenedListWithMemberNamespace = schema.new({
            id = id.from(_N, "XmlListsOperationOutput", "flattenedListWithMemberNamespace"),
            type = "list",
            name = "flattenedListWithMemberNamespace",
            target_id = prelude.Document.id,
            list_member = schema.new({ type = "string", target = prelude.String, traits = { [traits.XML_NAMESPACE] = { uri = "https://xml-member.example.com" } } }),
            traits = {
                [traits.XML_FLATTENED] = {},
            },
        }),
        flattenedListWithNamespace = schema.new({
            id = id.from(_N, "XmlListsOperationOutput", "flattenedListWithNamespace"),
            type = "list",
            name = "flattenedListWithNamespace",
            target_id = prelude.Document.id,
            list_member = prelude.String,
            traits = {
                [traits.XML_FLATTENED] = {},
            },
        }),
        structureList = schema.new({
            id = id.from(_N, "XmlListsOperationOutput", "structureList"),
            type = "list",
            name = "structureList",
            target_id = prelude.Document.id,
            list_member = schema.new({ type = "structure", target = M.StructureListMember, traits = { [traits.XML_NAME] = { name = "item" } } }),
            traits = {
                [traits.XML_NAME] = { name = "myStructureList" },
            },
        }),
    },
})

M.XmlMapsInput = prelude.Unit

M.XmlMapsOperationOutput = schema.new({
    id = id.from(_N, "XmlMapsOutput"),
    type = "structure",
    members = {
        myMap = schema.new({
            id = id.from(_N, "XmlMapsOperationOutput", "myMap"),
            type = "map",
            name = "myMap",
            target_id = prelude.Document.id,
            map_key = prelude.String,
            map_value = M.GreetingStruct,
        }),
    },
})

M.XmlMapsXmlNameInput = prelude.Unit

M.XmlMapsXmlNameOutput = schema.new({
    id = id.from(_N, "XmlMapsXmlNameOutput"),
    type = "structure",
    members = {
        myMap = schema.new({
            id = id.from(_N, "XmlMapsXmlNameOutput", "myMap"),
            type = "map",
            name = "myMap",
            target_id = prelude.Document.id,
            map_key = schema.new({ type = "string", traits = { [traits.XML_NAME] = { name = "Attribute" } } }),
            map_value = schema.new({ type = "structure", target = M.GreetingStruct, traits = { [traits.XML_NAME] = { name = "Setting" } } }),
        }),
    },
})

M.XmlNamespacesInput = prelude.Unit

M.XmlNamespaceNested = schema.new({
    id = id.from(_N, "XmlNamespaceNested"),
    type = "structure",
    traits = {
        [traits.XML_NAMESPACE] = { uri = "http://boo.com" },
    },
    members = {
        foo = schema.new({
            id = id.from(_N, "XmlNamespaceNested", "foo"),
            type = "string",
            name = "foo",
            target_id = prelude.String.id,
            traits = {
                [traits.XML_NAMESPACE] = { uri = "http://baz.com", prefix = "baz" },
            },
        }),
        values = schema.new({
            id = id.from(_N, "XmlNamespaceNested", "values"),
            type = "list",
            name = "values",
            target_id = prelude.Document.id,
            list_member = schema.new({ type = "string", target = prelude.String, traits = { [traits.XML_NAMESPACE] = { uri = "http://bux.com" } } }),
            traits = {
                [traits.XML_NAMESPACE] = { uri = "http://qux.com" },
            },
        }),
    },
})

M.XmlNamespacesOutput = schema.new({
    id = id.from(_N, "XmlNamespacesOutput"),
    type = "structure",
    traits = {
        [traits.XML_NAMESPACE] = { uri = "http://foo.com" },
    },
    members = {
        nested = schema.new({
            id = id.from(_N, "XmlNamespacesOutput", "nested"),
            type = "structure",
            name = "nested",
            target_id = id.from(_N, "XmlNamespaceNested"),
            target = M.XmlNamespaceNested,
        }),
    },
})

M.XmlTimestampsInput = prelude.Unit

M.XmlTimestampsOutput = schema.new({
    id = id.from(_N, "XmlTimestampsOutput"),
    type = "structure",
    members = {
        normal = schema.new({
            id = id.from(_N, "XmlTimestampsOutput", "normal"),
            type = "timestamp",
            name = "normal",
            target_id = prelude.Timestamp.id,
        }),
        dateTime = schema.new({
            id = id.from(_N, "XmlTimestampsOutput", "dateTime"),
            type = "timestamp",
            name = "dateTime",
            target_id = prelude.Timestamp.id,
            traits = {
                [traits.TIMESTAMP_FORMAT] = { format = "date-time" },
            },
        }),
        dateTimeOnTarget = schema.new({
            id = id.from(_N, "XmlTimestampsOutput", "dateTimeOnTarget"),
            type = "timestamp",
            name = "dateTimeOnTarget",
            target_id = prelude.Timestamp.id,
            traits = {
                [traits.TIMESTAMP_FORMAT] = { format = "date-time" },
            },
        }),
        epochSeconds = schema.new({
            id = id.from(_N, "XmlTimestampsOutput", "epochSeconds"),
            type = "timestamp",
            name = "epochSeconds",
            target_id = prelude.Timestamp.id,
            traits = {
                [traits.TIMESTAMP_FORMAT] = { format = "epoch-seconds" },
            },
        }),
        epochSecondsOnTarget = schema.new({
            id = id.from(_N, "XmlTimestampsOutput", "epochSecondsOnTarget"),
            type = "timestamp",
            name = "epochSecondsOnTarget",
            target_id = prelude.Timestamp.id,
            traits = {
                [traits.TIMESTAMP_FORMAT] = { format = "epoch-seconds" },
            },
        }),
        httpDate = schema.new({
            id = id.from(_N, "XmlTimestampsOutput", "httpDate"),
            type = "timestamp",
            name = "httpDate",
            target_id = prelude.Timestamp.id,
            traits = {
                [traits.TIMESTAMP_FORMAT] = { format = "http-date" },
            },
        }),
        httpDateOnTarget = schema.new({
            id = id.from(_N, "XmlTimestampsOutput", "httpDateOnTarget"),
            type = "timestamp",
            name = "httpDateOnTarget",
            target_id = prelude.Timestamp.id,
            traits = {
                [traits.TIMESTAMP_FORMAT] = { format = "http-date" },
            },
        }),
    },
})

M.StructArg = schema.new({
    id = id.from(_N, "StructArg"),
    type = "structure",
    members = {
        StringArg = schema.new({
            id = id.from(_N, "StructArg", "StringArg"),
            type = "string",
            name = "StringArg",
            target_id = prelude.String.id,
        }),
        OtherArg = schema.new({
            id = id.from(_N, "StructArg", "OtherArg"),
            type = "boolean",
            name = "OtherArg",
            target_id = prelude.Boolean.id,
        }),
        RecursiveArg = schema.new({
            id = id.from(_N, "StructArg", "RecursiveArg"),
            type = "structure",
            name = "RecursiveArg",
            target_id = id.from(_N, "StructArg"),
            target = M.StructArg,
        }),
    },
})

M.NestedStructuresInput = schema.new({
    id = id.from(_N, "NestedStructuresInput"),
    type = "structure",
    members = {
        Nested = schema.new({
            id = id.from(_N, "NestedStructuresInput", "Nested"),
            type = "structure",
            name = "Nested",
            target_id = id.from(_N, "StructArg"),
            target = M.StructArg,
        }),
    },
})

M.RecursiveXmlShapesOutputNested1 = schema.new({
    id = id.from(_N, "RecursiveXmlShapesOutputNested1"),
    type = "structure",
    members = {
        foo = schema.new({
            id = id.from(_N, "RecursiveXmlShapesOutputNested1", "foo"),
            type = "string",
            name = "foo",
            target_id = prelude.String.id,
        }),
        nested = schema.new({
            id = id.from(_N, "RecursiveXmlShapesOutputNested1", "nested"),
            type = "structure",
            name = "nested",
            target_id = id.from(_N, "RecursiveXmlShapesOutputNested2"),
            target = M.RecursiveXmlShapesOutputNested2,
        }),
    },
})

M.RecursiveXmlShapesOutputNested2 = schema.new({
    id = id.from(_N, "RecursiveXmlShapesOutputNested2"),
    type = "structure",
    members = {
        bar = schema.new({
            id = id.from(_N, "RecursiveXmlShapesOutputNested2", "bar"),
            type = "string",
            name = "bar",
            target_id = prelude.String.id,
        }),
        recursiveMember = schema.new({
            id = id.from(_N, "RecursiveXmlShapesOutputNested2", "recursiveMember"),
            type = "structure",
            name = "recursiveMember",
            target_id = id.from(_N, "RecursiveXmlShapesOutputNested1"),
            target = M.RecursiveXmlShapesOutputNested1,
        }),
    },
})

M.RecursiveXmlShapesOutput = schema.new({
    id = id.from(_N, "RecursiveXmlShapesOutput"),
    type = "structure",
    members = {
        nested = schema.new({
            id = id.from(_N, "RecursiveXmlShapesOutput", "nested"),
            type = "structure",
            name = "nested",
            target_id = id.from(_N, "RecursiveXmlShapesOutputNested1"),
            target = M.RecursiveXmlShapesOutputNested1,
        }),
    },
})

-- Fix forward references for recursive schemas
for _, s in pairs(M) do
    if type(s) == "table" and (s.type == "structure" or s.type == "union") then
        local members = rawget(s, "_members")
        if members then
            for _, ms in pairs(members) do
                if (ms.type == "structure" or ms.type == "union") and not rawget(ms, "_target") and ms.target_id then
                    rawset(ms, "_target", M[ms.target_id.name])
                end
            end
        end
    end
end

M.Service = schema.service({
    id = id.from("aws.protocoltests.query", "AwsQuery"),
    version = "2020-01-08",
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.DatetimeOffsets = schema.operation({
    id = id.from("aws.protocoltests.query", "DatetimeOffsets"),
    input = M.DatetimeOffsetsInput,
    output = M.DatetimeOffsetsOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.EmptyInputAndEmptyOutput = schema.operation({
    id = id.from("aws.protocoltests.query", "EmptyInputAndEmptyOutput"),
    input = M.EmptyInputAndEmptyOutputInput,
    output = M.EmptyInputAndEmptyOutputOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.EndpointOperation = schema.operation({
    id = id.from("aws.protocoltests.query", "EndpointOperation"),
    input = M.EndpointOperationInput,
    output = M.EndpointOperationOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.EndpointWithHostLabelOperation = schema.operation({
    id = id.from("aws.protocoltests.query", "EndpointWithHostLabelOperation"),
    input = M.EndpointWithHostLabelOperationInput,
    output = M.EndpointWithHostLabelOperationOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.FlattenedXmlMap = schema.operation({
    id = id.from("aws.protocoltests.query", "FlattenedXmlMap"),
    input = M.FlattenedXmlMapInput,
    output = M.FlattenedXmlMapOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.FlattenedXmlMapWithXmlName = schema.operation({
    id = id.from("aws.protocoltests.query", "FlattenedXmlMapWithXmlName"),
    input = M.FlattenedXmlMapWithXmlNameInput,
    output = M.FlattenedXmlMapWithXmlNameOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.FlattenedXmlMapWithXmlNamespace = schema.operation({
    id = id.from("aws.protocoltests.query", "FlattenedXmlMapWithXmlNamespace"),
    input = M.FlattenedXmlMapWithXmlNamespaceInput,
    output = M.FlattenedXmlMapWithXmlNamespaceOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.FractionalSeconds = schema.operation({
    id = id.from("aws.protocoltests.query", "FractionalSeconds"),
    input = M.FractionalSecondsInput,
    output = M.FractionalSecondsOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.GreetingWithErrors = schema.operation({
    id = id.from("aws.protocoltests.query", "GreetingWithErrors"),
    input = M.GreetingWithErrorsInput,
    output = M.GreetingWithErrorsOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.HostWithPathOperation = schema.operation({
    id = id.from("aws.protocoltests.query", "HostWithPathOperation"),
    input = M.HostWithPathOperationInput,
    output = M.HostWithPathOperationOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.IgnoresWrappingXmlName = schema.operation({
    id = id.from("aws.protocoltests.query", "IgnoresWrappingXmlName"),
    input = M.IgnoresWrappingXmlNameInput,
    output = M.IgnoresWrappingXmlNameOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.NestedStructures = schema.operation({
    id = id.from("aws.protocoltests.query", "NestedStructures"),
    input = M.NestedStructuresInput,
    output = M.NestedStructuresOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.NoInputAndNoOutput = schema.operation({
    id = id.from("aws.protocoltests.query", "NoInputAndNoOutput"),
    input = M.NoInputAndNoOutputInput,
    output = M.NoInputAndNoOutputOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.NoInputAndOutput = schema.operation({
    id = id.from("aws.protocoltests.query", "NoInputAndOutput"),
    input = M.NoInputAndOutputInput,
    output = M.NoInputAndOutputOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.PutWithContentEncoding = schema.operation({
    id = id.from("aws.protocoltests.query", "PutWithContentEncoding"),
    input = M.PutWithContentEncodingInput,
    output = M.PutWithContentEncodingOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.QueryIdempotencyTokenAutoFill = schema.operation({
    id = id.from("aws.protocoltests.query", "QueryIdempotencyTokenAutoFill"),
    input = M.QueryIdempotencyTokenAutoFillInput,
    output = M.QueryIdempotencyTokenAutoFillOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.QueryLists = schema.operation({
    id = id.from("aws.protocoltests.query", "QueryLists"),
    input = M.QueryListsInput,
    output = M.QueryListsOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.QueryMaps = schema.operation({
    id = id.from("aws.protocoltests.query", "QueryMaps"),
    input = M.QueryMapsInput,
    output = M.QueryMapsOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.QueryTimestamps = schema.operation({
    id = id.from("aws.protocoltests.query", "QueryTimestamps"),
    input = M.QueryTimestampsInput,
    output = M.QueryTimestampsOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.RecursiveXmlShapes = schema.operation({
    id = id.from("aws.protocoltests.query", "RecursiveXmlShapes"),
    input = M.RecursiveXmlShapesInput,
    output = M.RecursiveXmlShapesOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.SimpleInputParams = schema.operation({
    id = id.from("aws.protocoltests.query", "SimpleInputParams"),
    input = M.SimpleInputParamsInput,
    output = M.SimpleInputParamsOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.SimpleScalarXmlProperties = schema.operation({
    id = id.from("aws.protocoltests.query", "SimpleScalarXmlProperties"),
    input = M.SimpleScalarXmlPropertiesInput,
    output = M.SimpleScalarXmlPropertiesOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.XmlBlobs = schema.operation({
    id = id.from("aws.protocoltests.query", "XmlBlobs"),
    input = M.XmlBlobsInput,
    output = M.XmlBlobsOperationOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.XmlEmptyBlobs = schema.operation({
    id = id.from("aws.protocoltests.query", "XmlEmptyBlobs"),
    input = M.XmlEmptyBlobsInput,
    output = M.XmlEmptyBlobsOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.XmlEmptyLists = schema.operation({
    id = id.from("aws.protocoltests.query", "XmlEmptyLists"),
    input = M.XmlEmptyListsInput,
    output = M.XmlEmptyListsOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.XmlEmptyMaps = schema.operation({
    id = id.from("aws.protocoltests.query", "XmlEmptyMaps"),
    input = M.XmlEmptyMapsInput,
    output = M.XmlEmptyMapsOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.XmlEnums = schema.operation({
    id = id.from("aws.protocoltests.query", "XmlEnums"),
    input = M.XmlEnumsInput,
    output = M.XmlEnumsOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.XmlIntEnums = schema.operation({
    id = id.from("aws.protocoltests.query", "XmlIntEnums"),
    input = M.XmlIntEnumsInput,
    output = M.XmlIntEnumsOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.XmlLists = schema.operation({
    id = id.from("aws.protocoltests.query", "XmlLists"),
    input = M.XmlListsInput,
    output = M.XmlListsOperationOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.XmlMaps = schema.operation({
    id = id.from("aws.protocoltests.query", "XmlMaps"),
    input = M.XmlMapsInput,
    output = M.XmlMapsOperationOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.XmlMapsXmlName = schema.operation({
    id = id.from("aws.protocoltests.query", "XmlMapsXmlName"),
    input = M.XmlMapsXmlNameInput,
    output = M.XmlMapsXmlNameOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.XmlNamespaces = schema.operation({
    id = id.from("aws.protocoltests.query", "XmlNamespaces"),
    input = M.XmlNamespacesInput,
    output = M.XmlNamespacesOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

M.XmlTimestamps = schema.operation({
    id = id.from("aws.protocoltests.query", "XmlTimestamps"),
    input = M.XmlTimestampsInput,
    output = M.XmlTimestampsOutput,
    traits = {
        [traits.AUTH] = {
            { scheme_id = "aws.auth#sigv4" },
        },
    },
})

return M
