-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: awsQuery

local types = require("queryprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.awsquery")
local protocol = protocol_mod.new({ version = "2020-01-08" })

local service = schema.service({
    id = shape_id.from("aws.protocoltests.query", "AwsQuery"),
    version = "2020-01-08",
    traits = {},
})

describe("QueryTimestamps request", function()
    it("QueryTimestampsInput", function()
        local input = {
            normalFormat = 1422172800,
            epochMember = 1422172800,
            epochTarget = 1422172800,
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.query", "QueryTimestamps"),
            input = types.QueryTimestampsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-www-form-urlencoded")
        local body_str = h.read_body(request.body)
        h.assert_form_eq(body_str, [[Action=QueryTimestamps&Version=2020-01-08&normalFormat=2015-01-25T08%3A00%3A00Z&epochMember=1422172800&epochTarget=1422172800]])
    end)

end)
