-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: awsQuery

local types = require("queryprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.awsquery")
local protocol = protocol_mod.new({ version = "2020-01-08" })

local service = schema.service({
    id = shape_id.from("aws.protocoltests.query", "AwsQuery"),
    version = "2020-01-08",
    traits = {},
})

describe("GreetingWithErrors CustomCodeError error", function()
    it("QueryCustomizedError", function()
        local response = {
            status_code = 402,
            headers = {
                ["Content-Type"] = "text/xml",
            },
            body = http.string_reader([[<ErrorResponse>
               <Error>
                  <Type>Sender</Type>
                  <Code>Customized</Code>
                  <Message>Hi</Message>
               </Error>
               <RequestId>foo-id</RequestId>
            </ErrorResponse>
            ]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.query", "GreetingWithErrors"),
            input = schema.new({ type = "structure" }),
            output = types.CustomCodeError,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(output, "expected nil output for error response")
        assert.is_not_nil(err, "expected error")
        assert.are.equal("api", err.type)
        assert.is_true(err.code == "CustomCodeError" or (err.code and err.code:find("CustomCodeError", 1, true) ~= nil),
            "error code: expected CustomCodeError, got: " .. tostring(err.code))
        assert.are.equal("Hi", err.message)
    end)

end)
