-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: awsQuery

local types = require("queryprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.awsquery")
local protocol = protocol_mod.new({ version = "2020-01-08" })

local service = schema.service({
    id = shape_id.from("aws.protocoltests.query", "AwsQuery"),
    version = "2020-01-08",
    traits = {},
})

describe("XmlNamespaces response", function()
    it("QueryXmlNamespaces", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "text/xml",
            },
            body = http.string_reader([[<XmlNamespacesResponse xmlns="https://example.com/">
                <XmlNamespacesResult>
                    <nested>
                        <foo xmlns:baz="http://baz.com">Foo</foo>
                        <values xmlns="http://qux.com">
                            <member xmlns="http://bux.com">Bar</member>
                            <member xmlns="http://bux.com">Baz</member>
                        </values>
                    </nested>
                </XmlNamespacesResult>
            </XmlNamespacesResponse>
            ]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.query", "XmlNamespaces"),
            input = schema.new({ type = "structure" }),
            output = types.XmlNamespacesOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            nested = {
            foo = "Foo",
            values = {
            "Bar",
            "Baz",
        },
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

end)
