-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: awsQuery

local types = require("queryprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.awsquery")
local protocol = protocol_mod.new({ version = "2020-01-08" })

local service = schema.service({
    id = shape_id.from("aws.protocoltests.query", "AwsQuery"),
    version = "2020-01-08",
    traits = {},
})

describe("DatetimeOffsets response", function()
    it("AwsQueryDateTimeWithNegativeOffset", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "text/xml",
            },
            body = http.string_reader([[<DatetimeOffsetsResponse xmlns="https://example.com/">
                <DatetimeOffsetsResult>
                    <datetime>2019-12-16T22:48:18-01:00</datetime>
                </DatetimeOffsetsResult>
            </DatetimeOffsetsResponse>
            ]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.query", "DatetimeOffsets"),
            input = schema.new({ type = "structure" }),
            output = types.DatetimeOffsetsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            datetime = 1576540098,
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("AwsQueryDateTimeWithPositiveOffset", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "text/xml",
            },
            body = http.string_reader([[<DatetimeOffsetsResponse xmlns="https://example.com/">
                <DatetimeOffsetsResult>
                    <datetime>2019-12-17T00:48:18+01:00</datetime>
                </DatetimeOffsetsResult>
            </DatetimeOffsetsResponse>
            ]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.query", "DatetimeOffsets"),
            input = schema.new({ type = "structure" }),
            output = types.DatetimeOffsetsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            datetime = 1576540098,
        }
        h.assert_deep_eq(output, expected, "output")
    end)

end)
