-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: awsQuery

local types = require("queryprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.awsquery")
local protocol = protocol_mod.new({ version = "2020-01-08" })

local service = schema.service({
    id = shape_id.from("aws.protocoltests.query", "AwsQuery"),
    version = "2020-01-08",
    traits = {},
})

describe("FlattenedXmlMap response", function()
    it("QueryQueryFlattenedXmlMap", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "text/xml",
            },
            body = http.string_reader([[<FlattenedXmlMapResponse xmlns="https://example.com/">
                <FlattenedXmlMapResult>
                    <myMap>
                        <key>foo</key>
                        <value>Foo</value>
                    </myMap>
                    <myMap>
                        <key>baz</key>
                        <value>Baz</value>
                    </myMap>
                </FlattenedXmlMapResult>
            </FlattenedXmlMapResponse>]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.query", "FlattenedXmlMap"),
            input = schema.new({ type = "structure" }),
            output = types.FlattenedXmlMapOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            myMap = {
            foo = "Foo",
            baz = "Baz",
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

end)
