-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: awsQuery

local types = require("queryprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.awsquery")
local protocol = protocol_mod.new({ version = "2020-01-08" })

local service = schema.service({
    id = shape_id.from("aws.protocoltests.query", "AwsQuery"),
    version = "2020-01-08",
    traits = {},
})

describe("QueryIdempotencyTokenAutoFill request", function()
    it("QueryProtocolIdempotencyTokenAutoFill", function()
        local input = {}
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.query", "QueryIdempotencyTokenAutoFill"),
            input = types.QueryIdempotencyTokenAutoFillInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-www-form-urlencoded")
        local body_str = h.read_body(request.body)
        h.assert_form_eq(body_str, [[Action=QueryIdempotencyTokenAutoFill&Version=2020-01-08&token=00000000-0000-4000-8000-000000000000]])
    end)

    it("QueryProtocolIdempotencyTokenAutoFillIsSet", function()
        local input = {
            token = "00000000-0000-4000-8000-000000000123",
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.query", "QueryIdempotencyTokenAutoFill"),
            input = types.QueryIdempotencyTokenAutoFillInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-www-form-urlencoded")
        local body_str = h.read_body(request.body)
        h.assert_form_eq(body_str, [[Action=QueryIdempotencyTokenAutoFill&Version=2020-01-08&token=00000000-0000-4000-8000-000000000123]])
    end)

end)
