-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: awsQuery

local types = require("queryprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.awsquery")
local protocol = protocol_mod.new({ version = "2020-01-08" })

local service = schema.service({
    id = shape_id.from("aws.protocoltests.query", "AwsQuery"),
    version = "2020-01-08",
    traits = {},
})

describe("QueryMaps request", function()
    it("QuerySimpleQueryMaps", function()
        local input = {
            MapArg = {
            bar = "Bar",
            foo = "Foo",
        },
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.query", "QueryMaps"),
            input = types.QueryMapsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-www-form-urlencoded")
        local body_str = h.read_body(request.body)
        h.assert_form_eq(body_str, [[Action=QueryMaps&Version=2020-01-08&MapArg.entry.1.key=bar&MapArg.entry.1.value=Bar&MapArg.entry.2.key=foo&MapArg.entry.2.value=Foo]])
    end)

    it("QuerySimpleQueryMapsWithXmlName", function()
        local input = {
            RenamedMapArg = {
            foo = "Foo",
        },
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.query", "QueryMaps"),
            input = types.QueryMapsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-www-form-urlencoded")
        local body_str = h.read_body(request.body)
        h.assert_form_eq(body_str, [[Action=QueryMaps&Version=2020-01-08&Foo.entry.1.key=foo&Foo.entry.1.value=Foo]])
    end)

    it("QueryComplexQueryMaps", function()
        local input = {
            ComplexMapArg = {
            bar = {
            hi = "Bar",
        },
            foo = {
            hi = "Foo",
        },
        },
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.query", "QueryMaps"),
            input = types.QueryMapsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-www-form-urlencoded")
        local body_str = h.read_body(request.body)
        h.assert_form_eq(body_str, [[Action=QueryMaps&Version=2020-01-08&ComplexMapArg.entry.1.key=bar&ComplexMapArg.entry.1.value.hi=Bar&ComplexMapArg.entry.2.key=foo&ComplexMapArg.entry.2.value.hi=Foo]])
    end)

    it("QueryEmptyQueryMaps", function()
        local input = {
            MapArg = {},
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.query", "QueryMaps"),
            input = types.QueryMapsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-www-form-urlencoded")
        local body_str = h.read_body(request.body)
        h.assert_form_eq(body_str, [[Action=QueryMaps&Version=2020-01-08]])
    end)

    it("QueryQueryMapWithMemberXmlName", function()
        local input = {
            MapWithXmlMemberName = {
            bar = "Bar",
            foo = "Foo",
        },
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.query", "QueryMaps"),
            input = types.QueryMapsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-www-form-urlencoded")
        local body_str = h.read_body(request.body)
        h.assert_form_eq(body_str, [[Action=QueryMaps&Version=2020-01-08&MapWithXmlMemberName.entry.1.K=bar&MapWithXmlMemberName.entry.1.V=Bar&MapWithXmlMemberName.entry.2.K=foo&MapWithXmlMemberName.entry.2.V=Foo]])
    end)

    it("QueryFlattenedQueryMaps", function()
        local input = {
            FlattenedMap = {
            bar = "Bar",
            foo = "Foo",
        },
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.query", "QueryMaps"),
            input = types.QueryMapsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-www-form-urlencoded")
        local body_str = h.read_body(request.body)
        h.assert_form_eq(body_str, [[Action=QueryMaps&Version=2020-01-08&FlattenedMap.1.key=bar&FlattenedMap.1.value=Bar&FlattenedMap.2.key=foo&FlattenedMap.2.value=Foo]])
    end)

    it("QueryFlattenedQueryMapsWithXmlName", function()
        local input = {
            FlattenedMapWithXmlName = {
            bar = "Bar",
            foo = "Foo",
        },
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.query", "QueryMaps"),
            input = types.QueryMapsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-www-form-urlencoded")
        local body_str = h.read_body(request.body)
        h.assert_form_eq(body_str, [[Action=QueryMaps&Version=2020-01-08&Hi.1.K=bar&Hi.1.V=Bar&Hi.2.K=foo&Hi.2.V=Foo]])
    end)

    it("QueryQueryMapOfLists", function()
        local input = {
            MapOfLists = {
            bar = {
            "C",
            "D",
        },
            foo = {
            "A",
            "B",
        },
        },
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.query", "QueryMaps"),
            input = types.QueryMapsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-www-form-urlencoded")
        local body_str = h.read_body(request.body)
        h.assert_form_eq(body_str, [[Action=QueryMaps&Version=2020-01-08&MapOfLists.entry.1.key=bar&MapOfLists.entry.1.value.member.1=C&MapOfLists.entry.1.value.member.2=D&MapOfLists.entry.2.key=foo&MapOfLists.entry.2.value.member.1=A&MapOfLists.entry.2.value.member.2=B]])
    end)

    it("QueryNestedStructWithMap", function()
        local input = {
            NestedStructWithMap = {
            MapArg = {
            bar = "Bar",
            foo = "Foo",
        },
        },
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.query", "QueryMaps"),
            input = types.QueryMapsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-www-form-urlencoded")
        local body_str = h.read_body(request.body)
        h.assert_form_eq(body_str, [[Action=QueryMaps&Version=2020-01-08&NestedStructWithMap.MapArg.entry.1.key=bar&NestedStructWithMap.MapArg.entry.1.value=Bar&NestedStructWithMap.MapArg.entry.2.key=foo&NestedStructWithMap.MapArg.entry.2.value=Foo]])
    end)

end)
