-- Code generated by lua-client-codegen. DO NOT EDIT.

local base_client = require("smithy.client")
local defaults = require("smithy.defaults")
local restjson_protocol = require("smithy.protocol.restjson")
local schemas = require("restjsonprotocol.schemas")
local traits = require("smithy.traits")

local M = {}

local Client = {}
Client.__index = Client

Client.invokeOperation = base_client.invokeOperation

function M.new(cfg)
    cfg = cfg or {}
    cfg.service_id = "RestJson"
    if not cfg.protocol then
        cfg.protocol = restjson_protocol.new()
    end
    if not cfg.auth_scheme_resolver then
        cfg.auth_scheme_resolver = function(service, operation)
            local auth_trait = operation:trait(traits.AUTH) or service:trait(traits.AUTH)
            local options = {}
            for _, scheme in ipairs(auth_trait or {}) do
                local scheme_id = scheme.scheme_id or scheme
                if scheme_id == "aws.auth#sigv4" or scheme_id == "aws.auth#sigv4a" then
                    options[#options + 1] = { scheme_id = scheme_id, signer_properties = { signing_name = "restjson", signing_region = cfg.region } }
                else
                    options[#options + 1] = { scheme_id = scheme_id }
                end
            end
            return options
        end
    end
    defaults.resolve_auth_schemes(cfg)
    defaults.resolve_identity_resolvers(cfg)
    defaults.resolve_http_client(cfg)
    defaults.resolve_retry_strategy(cfg)
    local self = setmetatable(base_client.new(cfg), Client)
    return self
end

function Client:allQueryStringTypes(input, options)
    return self:invokeOperation(schemas.Service, schemas.AllQueryStringTypes, input, options)
end

function Client:constantAndVariableQueryString(input, options)
    return self:invokeOperation(schemas.Service, schemas.ConstantAndVariableQueryString, input, options)
end

function Client:constantQueryString(input, options)
    return self:invokeOperation(schemas.Service, schemas.ConstantQueryString, input, options)
end

function Client:contentTypeParameters(input, options)
    return self:invokeOperation(schemas.Service, schemas.ContentTypeParameters, input, options)
end

function Client:datetimeOffsets(input, options)
    return self:invokeOperation(schemas.Service, schemas.DatetimeOffsets, input, options)
end

function Client:documentType(input, options)
    return self:invokeOperation(schemas.Service, schemas.DocumentType, input, options)
end

function Client:documentTypeAsMapValue(input, options)
    return self:invokeOperation(schemas.Service, schemas.DocumentTypeAsMapValue, input, options)
end

function Client:documentTypeAsPayload(input, options)
    return self:invokeOperation(schemas.Service, schemas.DocumentTypeAsPayload, input, options)
end

function Client:duplexStream(input, options)
    return self:invokeOperation(schemas.Service, schemas.DuplexStream, input, options)
end

function Client:duplexStreamWithDistinctStreams(input, options)
    return self:invokeOperation(schemas.Service, schemas.DuplexStreamWithDistinctStreams, input, options)
end

function Client:duplexStreamWithInitialMessages(input, options)
    return self:invokeOperation(schemas.Service, schemas.DuplexStreamWithInitialMessages, input, options)
end

function Client:emptyInputAndEmptyOutput(input, options)
    return self:invokeOperation(schemas.Service, schemas.EmptyInputAndEmptyOutput, input, options)
end

function Client:endpointOperation(input, options)
    return self:invokeOperation(schemas.Service, schemas.EndpointOperation, input, options)
end

function Client:endpointWithHostLabelOperation(input, options)
    return self:invokeOperation(schemas.Service, schemas.EndpointWithHostLabelOperation, input, options)
end

function Client:fractionalSeconds(input, options)
    return self:invokeOperation(schemas.Service, schemas.FractionalSeconds, input, options)
end

function Client:greetingWithErrors(input, options)
    return self:invokeOperation(schemas.Service, schemas.GreetingWithErrors, input, options)
end

function Client:hostWithPathOperation(input, options)
    return self:invokeOperation(schemas.Service, schemas.HostWithPathOperation, input, options)
end

function Client:httpChecksumRequired(input, options)
    return self:invokeOperation(schemas.Service, schemas.HttpChecksumRequired, input, options)
end

function Client:httpEmptyPrefixHeaders(input, options)
    return self:invokeOperation(schemas.Service, schemas.HttpEmptyPrefixHeaders, input, options)
end

function Client:httpEnumPayload(input, options)
    return self:invokeOperation(schemas.Service, schemas.HttpEnumPayload, input, options)
end

function Client:httpPayloadTraits(input, options)
    return self:invokeOperation(schemas.Service, schemas.HttpPayloadTraits, input, options)
end

function Client:httpPayloadTraitsWithMediaType(input, options)
    return self:invokeOperation(schemas.Service, schemas.HttpPayloadTraitsWithMediaType, input, options)
end

function Client:httpPayloadWithStructure(input, options)
    return self:invokeOperation(schemas.Service, schemas.HttpPayloadWithStructure, input, options)
end

function Client:httpPayloadWithUnion(input, options)
    return self:invokeOperation(schemas.Service, schemas.HttpPayloadWithUnion, input, options)
end

function Client:httpPrefixHeaders(input, options)
    return self:invokeOperation(schemas.Service, schemas.HttpPrefixHeaders, input, options)
end

function Client:httpPrefixHeadersInResponse(input, options)
    return self:invokeOperation(schemas.Service, schemas.HttpPrefixHeadersInResponse, input, options)
end

function Client:httpQueryParamsOnlyOperation(input, options)
    return self:invokeOperation(schemas.Service, schemas.HttpQueryParamsOnlyOperation, input, options)
end

function Client:httpRequestWithFloatLabels(input, options)
    return self:invokeOperation(schemas.Service, schemas.HttpRequestWithFloatLabels, input, options)
end

function Client:httpRequestWithGreedyLabelInPath(input, options)
    return self:invokeOperation(schemas.Service, schemas.HttpRequestWithGreedyLabelInPath, input, options)
end

function Client:httpRequestWithLabels(input, options)
    return self:invokeOperation(schemas.Service, schemas.HttpRequestWithLabels, input, options)
end

function Client:httpRequestWithLabelsAndTimestampFormat(input, options)
    return self:invokeOperation(schemas.Service, schemas.HttpRequestWithLabelsAndTimestampFormat, input, options)
end

function Client:httpRequestWithRegexLiteral(input, options)
    return self:invokeOperation(schemas.Service, schemas.HttpRequestWithRegexLiteral, input, options)
end

function Client:httpResponseCode(input, options)
    return self:invokeOperation(schemas.Service, schemas.HttpResponseCode, input, options)
end

function Client:httpStringPayload(input, options)
    return self:invokeOperation(schemas.Service, schemas.HttpStringPayload, input, options)
end

function Client:ignoreQueryParamsInResponse(input, options)
    return self:invokeOperation(schemas.Service, schemas.IgnoreQueryParamsInResponse, input, options)
end

function Client:inputAndOutputWithHeaders(input, options)
    return self:invokeOperation(schemas.Service, schemas.InputAndOutputWithHeaders, input, options)
end

function Client:inputStream(input, options)
    return self:invokeOperation(schemas.Service, schemas.InputStream, input, options)
end

function Client:inputStreamWithInitialRequest(input, options)
    return self:invokeOperation(schemas.Service, schemas.InputStreamWithInitialRequest, input, options)
end

function Client:jsonBlobs(input, options)
    return self:invokeOperation(schemas.Service, schemas.JsonBlobs, input, options)
end

function Client:jsonEnums(input, options)
    return self:invokeOperation(schemas.Service, schemas.JsonEnums, input, options)
end

function Client:jsonIntEnums(input, options)
    return self:invokeOperation(schemas.Service, schemas.JsonIntEnums, input, options)
end

function Client:jsonLists(input, options)
    return self:invokeOperation(schemas.Service, schemas.JsonLists, input, options)
end

function Client:jsonMaps(input, options)
    return self:invokeOperation(schemas.Service, schemas.JsonMaps, input, options)
end

function Client:jsonTimestamps(input, options)
    return self:invokeOperation(schemas.Service, schemas.JsonTimestamps, input, options)
end

function Client:jsonUnions(input, options)
    return self:invokeOperation(schemas.Service, schemas.JsonUnions, input, options)
end

function Client:malformedAcceptWithBody(input, options)
    return self:invokeOperation(schemas.Service, schemas.MalformedAcceptWithBody, input, options)
end

function Client:malformedAcceptWithGenericString(input, options)
    return self:invokeOperation(schemas.Service, schemas.MalformedAcceptWithGenericString, input, options)
end

function Client:malformedAcceptWithPayload(input, options)
    return self:invokeOperation(schemas.Service, schemas.MalformedAcceptWithPayload, input, options)
end

function Client:malformedBlob(input, options)
    return self:invokeOperation(schemas.Service, schemas.MalformedBlob, input, options)
end

function Client:malformedBoolean(input, options)
    return self:invokeOperation(schemas.Service, schemas.MalformedBoolean, input, options)
end

function Client:malformedByte(input, options)
    return self:invokeOperation(schemas.Service, schemas.MalformedByte, input, options)
end

function Client:malformedContentTypeWithBody(input, options)
    return self:invokeOperation(schemas.Service, schemas.MalformedContentTypeWithBody, input, options)
end

function Client:malformedContentTypeWithGenericString(input, options)
    return self:invokeOperation(schemas.Service, schemas.MalformedContentTypeWithGenericString, input, options)
end

function Client:malformedContentTypeWithoutBody(input, options)
    return self:invokeOperation(schemas.Service, schemas.MalformedContentTypeWithoutBody, input, options)
end

function Client:malformedContentTypeWithoutBodyEmptyInput(input, options)
    return self:invokeOperation(schemas.Service, schemas.MalformedContentTypeWithoutBodyEmptyInput, input, options)
end

function Client:malformedContentTypeWithPayload(input, options)
    return self:invokeOperation(schemas.Service, schemas.MalformedContentTypeWithPayload, input, options)
end

function Client:malformedDouble(input, options)
    return self:invokeOperation(schemas.Service, schemas.MalformedDouble, input, options)
end

function Client:malformedFloat(input, options)
    return self:invokeOperation(schemas.Service, schemas.MalformedFloat, input, options)
end

function Client:malformedInteger(input, options)
    return self:invokeOperation(schemas.Service, schemas.MalformedInteger, input, options)
end

function Client:malformedList(input, options)
    return self:invokeOperation(schemas.Service, schemas.MalformedList, input, options)
end

function Client:malformedLong(input, options)
    return self:invokeOperation(schemas.Service, schemas.MalformedLong, input, options)
end

function Client:malformedMap(input, options)
    return self:invokeOperation(schemas.Service, schemas.MalformedMap, input, options)
end

function Client:malformedRequestBody(input, options)
    return self:invokeOperation(schemas.Service, schemas.MalformedRequestBody, input, options)
end

function Client:malformedShort(input, options)
    return self:invokeOperation(schemas.Service, schemas.MalformedShort, input, options)
end

function Client:malformedString(input, options)
    return self:invokeOperation(schemas.Service, schemas.MalformedString, input, options)
end

function Client:malformedTimestampBodyDateTime(input, options)
    return self:invokeOperation(schemas.Service, schemas.MalformedTimestampBodyDateTime, input, options)
end

function Client:malformedTimestampBodyDefault(input, options)
    return self:invokeOperation(schemas.Service, schemas.MalformedTimestampBodyDefault, input, options)
end

function Client:malformedTimestampBodyHttpDate(input, options)
    return self:invokeOperation(schemas.Service, schemas.MalformedTimestampBodyHttpDate, input, options)
end

function Client:malformedTimestampHeaderDateTime(input, options)
    return self:invokeOperation(schemas.Service, schemas.MalformedTimestampHeaderDateTime, input, options)
end

function Client:malformedTimestampHeaderDefault(input, options)
    return self:invokeOperation(schemas.Service, schemas.MalformedTimestampHeaderDefault, input, options)
end

function Client:malformedTimestampHeaderEpoch(input, options)
    return self:invokeOperation(schemas.Service, schemas.MalformedTimestampHeaderEpoch, input, options)
end

function Client:malformedTimestampPathDefault(input, options)
    return self:invokeOperation(schemas.Service, schemas.MalformedTimestampPathDefault, input, options)
end

function Client:malformedTimestampPathEpoch(input, options)
    return self:invokeOperation(schemas.Service, schemas.MalformedTimestampPathEpoch, input, options)
end

function Client:malformedTimestampPathHttpDate(input, options)
    return self:invokeOperation(schemas.Service, schemas.MalformedTimestampPathHttpDate, input, options)
end

function Client:malformedTimestampQueryDefault(input, options)
    return self:invokeOperation(schemas.Service, schemas.MalformedTimestampQueryDefault, input, options)
end

function Client:malformedTimestampQueryEpoch(input, options)
    return self:invokeOperation(schemas.Service, schemas.MalformedTimestampQueryEpoch, input, options)
end

function Client:malformedTimestampQueryHttpDate(input, options)
    return self:invokeOperation(schemas.Service, schemas.MalformedTimestampQueryHttpDate, input, options)
end

function Client:malformedUnion(input, options)
    return self:invokeOperation(schemas.Service, schemas.MalformedUnion, input, options)
end

function Client:mediaTypeHeader(input, options)
    return self:invokeOperation(schemas.Service, schemas.MediaTypeHeader, input, options)
end

function Client:noInputAndNoOutput(input, options)
    return self:invokeOperation(schemas.Service, schemas.NoInputAndNoOutput, input, options)
end

function Client:noInputAndOutput(input, options)
    return self:invokeOperation(schemas.Service, schemas.NoInputAndOutput, input, options)
end

function Client:nullAndEmptyHeadersClient(input, options)
    return self:invokeOperation(schemas.Service, schemas.NullAndEmptyHeadersClient, input, options)
end

function Client:nullAndEmptyHeadersServer(input, options)
    return self:invokeOperation(schemas.Service, schemas.NullAndEmptyHeadersServer, input, options)
end

function Client:omitsNullSerializesEmptyString(input, options)
    return self:invokeOperation(schemas.Service, schemas.OmitsNullSerializesEmptyString, input, options)
end

function Client:omitsSerializingEmptyLists(input, options)
    return self:invokeOperation(schemas.Service, schemas.OmitsSerializingEmptyLists, input, options)
end

function Client:operationWithDefaults(input, options)
    return self:invokeOperation(schemas.Service, schemas.OperationWithDefaults, input, options)
end

function Client:operationWithNestedStructure(input, options)
    return self:invokeOperation(schemas.Service, schemas.OperationWithNestedStructure, input, options)
end

function Client:outputStream(input, options)
    return self:invokeOperation(schemas.Service, schemas.OutputStream, input, options)
end

function Client:outputStreamWithInitialResponse(input, options)
    return self:invokeOperation(schemas.Service, schemas.OutputStreamWithInitialResponse, input, options)
end

function Client:postPlayerAction(input, options)
    return self:invokeOperation(schemas.Service, schemas.PostPlayerAction, input, options)
end

function Client:postUnionWithJsonName(input, options)
    return self:invokeOperation(schemas.Service, schemas.PostUnionWithJsonName, input, options)
end

function Client:putWithContentEncoding(input, options)
    return self:invokeOperation(schemas.Service, schemas.PutWithContentEncoding, input, options)
end

function Client:queryIdempotencyTokenAutoFill(input, options)
    return self:invokeOperation(schemas.Service, schemas.QueryIdempotencyTokenAutoFill, input, options)
end

function Client:queryParamsAsStringListMap(input, options)
    return self:invokeOperation(schemas.Service, schemas.QueryParamsAsStringListMap, input, options)
end

function Client:queryPrecedence(input, options)
    return self:invokeOperation(schemas.Service, schemas.QueryPrecedence, input, options)
end

function Client:recursiveShapes(input, options)
    return self:invokeOperation(schemas.Service, schemas.RecursiveShapes, input, options)
end

function Client:responseCodeHttpFallback(input, options)
    return self:invokeOperation(schemas.Service, schemas.ResponseCodeHttpFallback, input, options)
end

function Client:responseCodeRequired(input, options)
    return self:invokeOperation(schemas.Service, schemas.ResponseCodeRequired, input, options)
end

function Client:simpleScalarProperties(input, options)
    return self:invokeOperation(schemas.Service, schemas.SimpleScalarProperties, input, options)
end

function Client:sparseJsonLists(input, options)
    return self:invokeOperation(schemas.Service, schemas.SparseJsonLists, input, options)
end

function Client:sparseJsonMaps(input, options)
    return self:invokeOperation(schemas.Service, schemas.SparseJsonMaps, input, options)
end

function Client:streamingTraits(input, options)
    return self:invokeOperation(schemas.Service, schemas.StreamingTraits, input, options)
end

function Client:streamingTraitsRequireLength(input, options)
    return self:invokeOperation(schemas.Service, schemas.StreamingTraitsRequireLength, input, options)
end

function Client:streamingTraitsWithMediaType(input, options)
    return self:invokeOperation(schemas.Service, schemas.StreamingTraitsWithMediaType, input, options)
end

function Client:testBodyStructure(input, options)
    return self:invokeOperation(schemas.Service, schemas.TestBodyStructure, input, options)
end

function Client:testGetNoInputNoPayload(input, options)
    return self:invokeOperation(schemas.Service, schemas.TestGetNoInputNoPayload, input, options)
end

function Client:testGetNoPayload(input, options)
    return self:invokeOperation(schemas.Service, schemas.TestGetNoPayload, input, options)
end

function Client:testPayloadBlob(input, options)
    return self:invokeOperation(schemas.Service, schemas.TestPayloadBlob, input, options)
end

function Client:testPayloadStructure(input, options)
    return self:invokeOperation(schemas.Service, schemas.TestPayloadStructure, input, options)
end

function Client:testPostNoInputNoPayload(input, options)
    return self:invokeOperation(schemas.Service, schemas.TestPostNoInputNoPayload, input, options)
end

function Client:testPostNoPayload(input, options)
    return self:invokeOperation(schemas.Service, schemas.TestPostNoPayload, input, options)
end

function Client:timestampFormatHeaders(input, options)
    return self:invokeOperation(schemas.Service, schemas.TimestampFormatHeaders, input, options)
end

function Client:unitInputAndOutput(input, options)
    return self:invokeOperation(schemas.Service, schemas.UnitInputAndOutput, input, options)
end

return M
