-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: restJson1

local types = require("restjsonprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.restjson")
local protocol = protocol_mod.new()

local service = schema.service({
    id = shape_id.from("aws.protocoltests.restjson", "RestJson"),
    version = "2019-12-16",
    traits = {},
})

describe("DocumentType request", function()
    it("DocumentTypeInputWithObject", function()
        local input = {
            stringValue = "string",
            documentValue = {
            foo = "bar",
        },
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "DocumentType"),
            input = types.DocumentTypeInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "PUT", path = "/DocumentType" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("PUT", request.method)
        h.assert_url_path(request.url, "/DocumentType")
        h.assert_header(request, "Content-Type", "application/json")
        local body_str = h.read_body(request.body)
        h.assert_json_eq(body_str, [[{
            "stringValue": "string",
            "documentValue": {
                "foo": "bar"
            }
        }]])
    end)

    it("DocumentInputWithString", function()
        local input = {
            stringValue = "string",
            documentValue = "hello",
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "DocumentType"),
            input = types.DocumentTypeInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "PUT", path = "/DocumentType" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("PUT", request.method)
        h.assert_url_path(request.url, "/DocumentType")
        h.assert_header(request, "Content-Type", "application/json")
        local body_str = h.read_body(request.body)
        h.assert_json_eq(body_str, [[{
            "stringValue": "string",
            "documentValue": "hello"
        }]])
    end)

    it("DocumentInputWithNumber", function()
        local input = {
            stringValue = "string",
            documentValue = 10,
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "DocumentType"),
            input = types.DocumentTypeInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "PUT", path = "/DocumentType" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("PUT", request.method)
        h.assert_url_path(request.url, "/DocumentType")
        h.assert_header(request, "Content-Type", "application/json")
        local body_str = h.read_body(request.body)
        h.assert_json_eq(body_str, [[{
            "stringValue": "string",
            "documentValue": 10
        }]])
    end)

    it("DocumentInputWithBoolean", function()
        local input = {
            stringValue = "string",
            documentValue = true,
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "DocumentType"),
            input = types.DocumentTypeInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "PUT", path = "/DocumentType" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("PUT", request.method)
        h.assert_url_path(request.url, "/DocumentType")
        h.assert_header(request, "Content-Type", "application/json")
        local body_str = h.read_body(request.body)
        h.assert_json_eq(body_str, [[{
            "stringValue": "string",
            "documentValue": true
        }]])
    end)

    it("DocumentInputWithList", function()
        local input = {
            stringValue = "string",
            documentValue = {
            true,
            "hi",
            {
            1,
            2,
        },
            {
            foo = {
            baz = {
            3,
            4,
        },
        },
        },
        },
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "DocumentType"),
            input = types.DocumentTypeInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "PUT", path = "/DocumentType" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("PUT", request.method)
        h.assert_url_path(request.url, "/DocumentType")
        h.assert_header(request, "Content-Type", "application/json")
        local body_str = h.read_body(request.body)
        h.assert_json_eq(body_str, [[{
            "stringValue": "string",
            "documentValue": [
                true,
                "hi",
                [
                    1,
                    2
                ],
                {
                    "foo": {
                        "baz": [
                            3,
                            4
                        ]
                    }
                }
            ]
        }]])
    end)

end)
