-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: restJson1

local types = require("restjsonprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.restjson")
local protocol = protocol_mod.new()

local service = schema.service({
    id = shape_id.from("aws.protocoltests.restjson", "RestJson"),
    version = "2019-12-16",
    traits = {},
})

describe("HttpPayloadTraitsWithMediaType request", function()
    it("RestJsonHttpPayloadTraitsWithMediaTypeWithBlob", function()
        local input = {
            foo = "Foo",
            blob = "blobby blob blob",
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "HttpPayloadTraitsWithMediaType"),
            input = types.HttpPayloadTraitsWithMediaTypeInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/HttpPayloadTraitsWithMediaType" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/HttpPayloadTraitsWithMediaType")
        h.assert_header(request, "Content-Type", "text/plain")
        h.assert_header(request, "X-Foo", "Foo")
        local body_str = h.read_body(request.body)
        assert.are.equal([[blobby blob blob]], body_str)
    end)

end)
