-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: restJson1

local types = require("restjsonprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.restjson")
local protocol = protocol_mod.new()

local service = schema.service({
    id = shape_id.from("aws.protocoltests.restjson", "RestJson"),
    version = "2019-12-16",
    traits = {},
})

describe("GreetingWithErrors FooError error", function()
    it("RestJsonFooErrorUsingXAmznErrorType", function()
        local response = {
            status_code = 500,
            headers = {
                ["X-Amzn-Errortype"] = "FooError",
            },
            body = http.string_reader([[]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "GreetingWithErrors"),
            input = schema.new({ type = "structure" }),
            output = types.FooError,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(output, "expected nil output for error response")
        assert.is_not_nil(err, "expected error")
        assert.are.equal("api", err.type)
        assert.is_true(err.code == "FooError" or (err.code and err.code:find("FooError", 1, true) ~= nil),
            "error code: expected FooError, got: " .. tostring(err.code))
    end)

    it("RestJsonFooErrorUsingXAmznErrorTypeWithUri", function()
        local response = {
            status_code = 500,
            headers = {
                ["X-Amzn-Errortype"] = "FooError:http://internal.amazon.com/coral/com.amazon.coral.validate/",
            },
            body = http.string_reader([[]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "GreetingWithErrors"),
            input = schema.new({ type = "structure" }),
            output = types.FooError,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(output, "expected nil output for error response")
        assert.is_not_nil(err, "expected error")
        assert.are.equal("api", err.type)
        assert.is_true(err.code == "FooError" or (err.code and err.code:find("FooError", 1, true) ~= nil),
            "error code: expected FooError, got: " .. tostring(err.code))
    end)

    it("RestJsonFooErrorUsingXAmznErrorTypeWithUriAndNamespace", function()
        local response = {
            status_code = 500,
            headers = {
                ["X-Amzn-Errortype"] = "aws.protocoltests.restjson#FooError:http://internal.amazon.com/coral/com.amazon.coral.validate/",
            },
            body = http.string_reader([[]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "GreetingWithErrors"),
            input = schema.new({ type = "structure" }),
            output = types.FooError,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(output, "expected nil output for error response")
        assert.is_not_nil(err, "expected error")
        assert.are.equal("api", err.type)
        assert.is_true(err.code == "FooError" or (err.code and err.code:find("FooError", 1, true) ~= nil),
            "error code: expected FooError, got: " .. tostring(err.code))
    end)

    it("RestJsonFooErrorUsingCode", function()
        local response = {
            status_code = 500,
            headers = {
                ["Content-Type"] = "application/json",
            },
            body = http.string_reader([[{
                "code": "FooError"
            }]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "GreetingWithErrors"),
            input = schema.new({ type = "structure" }),
            output = types.FooError,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(output, "expected nil output for error response")
        assert.is_not_nil(err, "expected error")
        assert.are.equal("api", err.type)
        assert.is_true(err.code == "FooError" or (err.code and err.code:find("FooError", 1, true) ~= nil),
            "error code: expected FooError, got: " .. tostring(err.code))
    end)

    it("RestJsonFooErrorUsingCodeAndNamespace", function()
        local response = {
            status_code = 500,
            headers = {
                ["Content-Type"] = "application/json",
            },
            body = http.string_reader([[{
                "code": "aws.protocoltests.restjson#FooError"
            }]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "GreetingWithErrors"),
            input = schema.new({ type = "structure" }),
            output = types.FooError,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(output, "expected nil output for error response")
        assert.is_not_nil(err, "expected error")
        assert.are.equal("api", err.type)
        assert.is_true(err.code == "FooError" or (err.code and err.code:find("FooError", 1, true) ~= nil),
            "error code: expected FooError, got: " .. tostring(err.code))
    end)

    it("RestJsonFooErrorUsingCodeUriAndNamespace", function()
        local response = {
            status_code = 500,
            headers = {
                ["Content-Type"] = "application/json",
            },
            body = http.string_reader([[{
                "code": "aws.protocoltests.restjson#FooError:http://internal.amazon.com/coral/com.amazon.coral.validate/"
            }]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "GreetingWithErrors"),
            input = schema.new({ type = "structure" }),
            output = types.FooError,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(output, "expected nil output for error response")
        assert.is_not_nil(err, "expected error")
        assert.are.equal("api", err.type)
        assert.is_true(err.code == "FooError" or (err.code and err.code:find("FooError", 1, true) ~= nil),
            "error code: expected FooError, got: " .. tostring(err.code))
    end)

    it("RestJsonFooErrorWithDunderType", function()
        local response = {
            status_code = 500,
            headers = {
                ["Content-Type"] = "application/json",
            },
            body = http.string_reader([[{
                "__type": "FooError"
            }]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "GreetingWithErrors"),
            input = schema.new({ type = "structure" }),
            output = types.FooError,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(output, "expected nil output for error response")
        assert.is_not_nil(err, "expected error")
        assert.are.equal("api", err.type)
        assert.is_true(err.code == "FooError" or (err.code and err.code:find("FooError", 1, true) ~= nil),
            "error code: expected FooError, got: " .. tostring(err.code))
    end)

    it("RestJsonFooErrorWithDunderTypeAndNamespace", function()
        local response = {
            status_code = 500,
            headers = {
                ["Content-Type"] = "application/json",
            },
            body = http.string_reader([[{
                "__type": "aws.protocoltests.restjson#FooError"
            }]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "GreetingWithErrors"),
            input = schema.new({ type = "structure" }),
            output = types.FooError,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(output, "expected nil output for error response")
        assert.is_not_nil(err, "expected error")
        assert.are.equal("api", err.type)
        assert.is_true(err.code == "FooError" or (err.code and err.code:find("FooError", 1, true) ~= nil),
            "error code: expected FooError, got: " .. tostring(err.code))
    end)

    it("RestJsonFooErrorWithDunderTypeUriAndNamespace", function()
        local response = {
            status_code = 500,
            headers = {
                ["Content-Type"] = "application/json",
            },
            body = http.string_reader([[{
                "__type": "aws.protocoltests.restjson#FooError:http://internal.amazon.com/coral/com.amazon.coral.validate/"
            }]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "GreetingWithErrors"),
            input = schema.new({ type = "structure" }),
            output = types.FooError,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(output, "expected nil output for error response")
        assert.is_not_nil(err, "expected error")
        assert.are.equal("api", err.type)
        assert.is_true(err.code == "FooError" or (err.code and err.code:find("FooError", 1, true) ~= nil),
            "error code: expected FooError, got: " .. tostring(err.code))
    end)

    it("RestJsonFooErrorWithNestedTypeProperty", function()
        local response = {
            status_code = 500,
            headers = {
                ["Content-Type"] = "application/json",
            },
            body = http.string_reader([[{
                "__type": "aws.protocoltests.restjson#FooError",
                "ErrorDetails": [
                  {
                      "__type": "com.amazon.internal#ErrorDetails",
                      "reason": "Some reason"
                  }
                ]
            }]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "GreetingWithErrors"),
            input = schema.new({ type = "structure" }),
            output = types.FooError,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(output, "expected nil output for error response")
        assert.is_not_nil(err, "expected error")
        assert.are.equal("api", err.type)
        assert.is_true(err.code == "FooError" or (err.code and err.code:find("FooError", 1, true) ~= nil),
            "error code: expected FooError, got: " .. tostring(err.code))
    end)

end)
