-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: restJson1

local types = require("restjsonprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.restjson")
local protocol = protocol_mod.new()

local service = schema.service({
    id = shape_id.from("aws.protocoltests.restjson", "RestJson"),
    version = "2019-12-16",
    traits = {},
})

describe("TestPayloadBlob request", function()
    it("RestJsonHttpWithEmptyBlobPayload", function()
        local input = {}
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "TestPayloadBlob"),
            input = types.TestPayloadBlobInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/blob_payload" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/blob_payload")
        local body_str = h.read_body(request.body)
        assert.is_true(body_str == "" or body_str == nil, "expected empty body")
    end)

    it("RestJsonTestPayloadBlob", function()
        local input = {
            contentType = "image/jpg",
            data = "1234",
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "TestPayloadBlob"),
            input = types.TestPayloadBlobInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/blob_payload" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/blob_payload")
        h.assert_header(request, "Content-Type", "image/jpg")
        local body_str = h.read_body(request.body)
        assert.are.equal([[1234]], body_str)
    end)

end)
