-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: restJson1

local types = require("restjsonprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.restjson")
local protocol = protocol_mod.new()

local service = schema.service({
    id = shape_id.from("aws.protocoltests.restjson", "RestJson"),
    version = "2019-12-16",
    traits = {},
})

describe("JsonEnums response", function()
    it("RestJsonJsonEnums", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/json",
            },
            body = http.string_reader([[{
                "fooEnum1": "Foo",
                "fooEnum2": "0",
                "fooEnum3": "1",
                "fooEnumList": [
                    "Foo",
                    "0"
                ],
                "fooEnumSet": [
                    "Foo",
                    "0"
                ],
                "fooEnumMap": {
                    "hi": "Foo",
                    "zero": "0"
                }
            }]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "JsonEnums"),
            input = schema.new({ type = "structure" }),
            output = types.JsonEnumsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            fooEnum1 = "Foo",
            fooEnum2 = "0",
            fooEnum3 = "1",
            fooEnumList = {
            "Foo",
            "0",
        },
            fooEnumSet = {
            "Foo",
            "0",
        },
            fooEnumMap = {
            hi = "Foo",
            zero = "0",
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

end)
