-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: restJson1

local types = require("restjsonprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.restjson")
local protocol = protocol_mod.new()

local service = schema.service({
    id = shape_id.from("aws.protocoltests.restjson", "RestJson"),
    version = "2019-12-16",
    traits = {},
})

describe("JsonMaps response", function()
    it("RestJsonJsonMaps", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/json",
            },
            body = http.string_reader([[{
                "denseStructMap": {
                    "foo": {
                        "hi": "there"
                    },
                    "baz": {
                        "hi": "bye"
                    }
                }
            }]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "JsonMaps"),
            input = schema.new({ type = "structure" }),
            output = types.JsonMapsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            denseStructMap = {
            foo = {
            hi = "there",
        },
            baz = {
            hi = "bye",
        },
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("RestJsonDeserializesZeroValuesInMaps", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/json",
            },
            body = http.string_reader([[{
                "denseNumberMap": {
                    "x": 0
                },
                "denseBooleanMap": {
                    "x": false
                }
            }]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "JsonMaps"),
            input = schema.new({ type = "structure" }),
            output = types.JsonMapsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            denseNumberMap = {
            x = 0,
        },
            denseBooleanMap = {
            x = false,
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("RestJsonDeserializesDenseSetMap", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/json",
            },
            body = http.string_reader([[{
                "denseSetMap": {
                    "x": [],
                    "y": ["a", "b"]
                }
            }]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "JsonMaps"),
            input = schema.new({ type = "structure" }),
            output = types.JsonMapsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            denseSetMap = {
            x = {},
            y = {
            "a",
            "b",
        },
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

end)
