-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: restJson1

local types = require("restjsonprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.restjson")
local protocol = protocol_mod.new()

local service = schema.service({
    id = shape_id.from("aws.protocoltests.restjson", "RestJson"),
    version = "2019-12-16",
    traits = {},
})

describe("HttpPrefixHeaders request", function()
    it("RestJsonHttpPrefixHeadersArePresent", function()
        local input = {
            foo = "Foo",
            fooMap = {
            abc = "Abc value",
            def = "Def value",
        },
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "HttpPrefixHeaders"),
            input = types.HttpPrefixHeadersInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "GET", path = "/HttpPrefixHeaders" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("GET", request.method)
        h.assert_url_path(request.url, "/HttpPrefixHeaders")
        h.assert_header(request, "x-foo", "Foo")
        h.assert_header(request, "x-foo-abc", "Abc value")
        h.assert_header(request, "x-foo-def", "Def value")
        local body_str = h.read_body(request.body)
        assert.is_true(body_str == "" or body_str == nil, "expected empty body")
    end)

    it("RestJsonHttpPrefixHeadersAreNotPresent", function()
        local input = {
            foo = "Foo",
            fooMap = {},
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "HttpPrefixHeaders"),
            input = types.HttpPrefixHeadersInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "GET", path = "/HttpPrefixHeaders" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("GET", request.method)
        h.assert_url_path(request.url, "/HttpPrefixHeaders")
        h.assert_header(request, "x-foo", "Foo")
        local body_str = h.read_body(request.body)
        assert.is_true(body_str == "" or body_str == nil, "expected empty body")
    end)

    it("RestJsonHttpPrefixEmptyHeaders", function()
        local input = {
            fooMap = {
            abc = "",
        },
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "HttpPrefixHeaders"),
            input = types.HttpPrefixHeadersInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "GET", path = "/HttpPrefixHeaders" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("GET", request.method)
        h.assert_url_path(request.url, "/HttpPrefixHeaders")
        h.assert_header(request, "x-foo-abc", "")
        local body_str = h.read_body(request.body)
        assert.is_true(body_str == "" or body_str == nil, "expected empty body")
    end)

end)
