-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: restJson1

local types = require("restjsonprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.restjson")
local protocol = protocol_mod.new()

local service = schema.service({
    id = shape_id.from("aws.protocoltests.restjson", "RestJson"),
    version = "2019-12-16",
    traits = {},
})

describe("DocumentTypeAsPayload request", function()
    it("DocumentTypeAsPayloadInput", function()
        local input = {
            documentValue = {
            foo = "bar",
        },
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "DocumentTypeAsPayload"),
            input = types.DocumentTypeAsPayloadInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "PUT", path = "/DocumentTypeAsPayload" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("PUT", request.method)
        h.assert_url_path(request.url, "/DocumentTypeAsPayload")
        h.assert_header(request, "Content-Type", "application/json")
        local body_str = h.read_body(request.body)
        h.assert_json_eq(body_str, [[{
            "foo": "bar"
        }]])
    end)

    it("DocumentTypeAsPayloadInputString", function()
        local input = {
            documentValue = "hello",
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "DocumentTypeAsPayload"),
            input = types.DocumentTypeAsPayloadInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "PUT", path = "/DocumentTypeAsPayload" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("PUT", request.method)
        h.assert_url_path(request.url, "/DocumentTypeAsPayload")
        h.assert_header(request, "Content-Type", "application/json")
        local body_str = h.read_body(request.body)
        h.assert_json_eq(body_str, [["hello"]])
    end)

end)
