-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: restJson1

local types = require("restjsonprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.restjson")
local protocol = protocol_mod.new()

local service = schema.service({
    id = shape_id.from("aws.protocoltests.restjson", "RestJson"),
    version = "2019-12-16",
    traits = {},
})

describe("SparseJsonMaps response", function()
    it("RestJsonSparseJsonMaps", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/json",
            },
            body = http.string_reader([[{
                "sparseStructMap": {
                    "foo": {
                        "hi": "there"
                    },
                    "baz": {
                        "hi": "bye"
                    }
               }
            }]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "SparseJsonMaps"),
            input = schema.new({ type = "structure" }),
            output = types.SparseJsonMapsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            sparseStructMap = {
            foo = {
            hi = "there",
        },
            baz = {
            hi = "bye",
        },
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("RestJsonDeserializesSparseNullMapValues", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/json",
            },
            body = http.string_reader([[{
                "sparseBooleanMap": {
                    "x": null
                },
                "sparseNumberMap": {
                    "x": null
                },
                "sparseStringMap": {
                    "x": null
                },
                "sparseStructMap": {
                    "x": null
                }
            }]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "SparseJsonMaps"),
            input = schema.new({ type = "structure" }),
            output = types.SparseJsonMapsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            sparseBooleanMap = {
            x = nil,
        },
            sparseNumberMap = {
            x = nil,
        },
            sparseStringMap = {
            x = nil,
        },
            sparseStructMap = {
            x = nil,
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("RestJsonDeserializesZeroValuesInSparseMaps", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/json",
            },
            body = http.string_reader([[{
                "sparseNumberMap": {
                    "x": 0
                },
                "sparseBooleanMap": {
                    "x": false
                }
            }]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "SparseJsonMaps"),
            input = schema.new({ type = "structure" }),
            output = types.SparseJsonMapsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            sparseNumberMap = {
            x = 0,
        },
            sparseBooleanMap = {
            x = false,
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("RestJsonDeserializesSparseSetMap", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/json",
            },
            body = http.string_reader([[{
                "sparseSetMap": {
                    "x": [],
                    "y": ["a", "b"]
                }
            }]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "SparseJsonMaps"),
            input = schema.new({ type = "structure" }),
            output = types.SparseJsonMapsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            sparseSetMap = {
            x = {},
            y = {
            "a",
            "b",
        },
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("RestJsonDeserializesSparseSetMapAndRetainsNull", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/json",
            },
            body = http.string_reader([[{
                "sparseSetMap": {
                    "x": [],
                    "y": ["a", "b"],
                    "z": null
                }
            }]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "SparseJsonMaps"),
            input = schema.new({ type = "structure" }),
            output = types.SparseJsonMapsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            sparseSetMap = {
            x = {},
            y = {
            "a",
            "b",
        },
            z = nil,
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

end)
