-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: restJson1

local types = require("restjsonprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.restjson")
local protocol = protocol_mod.new()

local service = schema.service({
    id = shape_id.from("aws.protocoltests.restjson", "RestJson"),
    version = "2019-12-16",
    traits = {},
})

describe("GreetingWithErrors ComplexError error", function()
    it("RestJsonComplexErrorWithNoMessage", function()
        local response = {
            status_code = 403,
            headers = {
                ["Content-Type"] = "application/json",
                ["X-Amzn-Errortype"] = "ComplexError",
                ["X-Header"] = "Header",
            },
            body = http.string_reader([[{
                "TopLevel": "Top level",
                "Nested": {
                    "Fooooo": "bar"
                }
            }]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "GreetingWithErrors"),
            input = schema.new({ type = "structure" }),
            output = types.ComplexError,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(output, "expected nil output for error response")
        assert.is_not_nil(err, "expected error")
        assert.are.equal("api", err.type)
        assert.is_true(err.code == "ComplexError" or (err.code and err.code:find("ComplexError", 1, true) ~= nil),
            "error code: expected ComplexError, got: " .. tostring(err.code))
    end)

    it("RestJsonEmptyComplexErrorWithNoMessage", function()
        local response = {
            status_code = 403,
            headers = {
                ["Content-Type"] = "application/json",
                ["X-Amzn-Errortype"] = "ComplexError",
            },
            body = http.string_reader([[{}]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "GreetingWithErrors"),
            input = schema.new({ type = "structure" }),
            output = types.ComplexError,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(output, "expected nil output for error response")
        assert.is_not_nil(err, "expected error")
        assert.are.equal("api", err.type)
        assert.is_true(err.code == "ComplexError" or (err.code and err.code:find("ComplexError", 1, true) ~= nil),
            "error code: expected ComplexError, got: " .. tostring(err.code))
    end)

end)
