-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: restJson1

local types = require("restjsonprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.restjson")
local protocol = protocol_mod.new()

local service = schema.service({
    id = shape_id.from("aws.protocoltests.restjson", "RestJson"),
    version = "2019-12-16",
    traits = {},
})

describe("ConstantAndVariableQueryString request", function()
    it("RestJsonConstantAndVariableQueryStringMissingOneValue", function()
        local input = {
            baz = "bam",
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "ConstantAndVariableQueryString"),
            input = types.ConstantAndVariableQueryStringInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "GET", path = "/ConstantAndVariableQueryString?foo=bar" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("GET", request.method)
        h.assert_url_path(request.url, "/ConstantAndVariableQueryString")
        h.assert_query_param(request.url, "foo=bar")
        h.assert_query_param(request.url, "baz=bam")
        h.assert_no_query_param(request.url, "maybeSet")
        local body_str = h.read_body(request.body)
        assert.is_true(body_str == "" or body_str == nil, "expected empty body")
    end)

    it("RestJsonConstantAndVariableQueryStringAllValues", function()
        local input = {
            baz = "bam",
            maybeSet = "yes",
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restjson", "ConstantAndVariableQueryString"),
            input = types.ConstantAndVariableQueryStringInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "GET", path = "/ConstantAndVariableQueryString?foo=bar" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("GET", request.method)
        h.assert_url_path(request.url, "/ConstantAndVariableQueryString")
        h.assert_query_param(request.url, "foo=bar")
        h.assert_query_param(request.url, "baz=bam")
        h.assert_query_param(request.url, "maybeSet=yes")
        local body_str = h.read_body(request.body)
        assert.is_true(body_str == "" or body_str == nil, "expected empty body")
    end)

end)
