package software.amazon.smithy.lua.codegen;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.Locale;
import software.amazon.smithy.model.knowledge.OperationIndex;
import software.amazon.smithy.model.knowledge.TopDownIndex;

/**
 * Generates client.tl — the typed service client module.
 */
final class ClientGenerator {

    static void generate(LuaContext context) {
        var model = context.model();
        var service = context.service();
        var serviceNs = LuaSymbolProvider.getServiceNamespace(service);
        var symbolProvider = context.symbolProvider();
        var delegator = context.writerDelegator();
        var file = serviceNs + "/client.tl";

        delegator.useFileWriter(file, serviceNs, writer -> {
            var topDown = TopDownIndex.of(model);
            var operationIndex = OperationIndex.of(model);

            // Collect config resolvers from integrations
            var configResolvers = new ArrayList<ConfigResolver>();
            var configFinalizers = new ArrayList<ConfigResolver>();
            for (var integration : context.integrations()) {
                if (!integration.forService(service.getId())) continue;
                configResolvers.addAll(integration.getConfigResolvers(context));
                configFinalizers.addAll(integration.getConfigFinalizers(context));
            }

            // Determine protocol
            String protocolAlias = null;
            String protocolRequire = null;
            String protocolExpr = null;
            for (var traitId : service.getAllTraits().keySet()) {
                var n = traitId.toString();
                if (n.equals("aws.protocols#awsJson1_0")) {
                    protocolAlias = "awsjson_protocol"; protocolRequire = "smithy.protocol.awsjson";
                    protocolExpr = "awsjson_protocol.new({ version = \"1.0\", service_id = c.service_id })";
                } else if (n.equals("aws.protocols#awsJson1_1")) {
                    protocolAlias = "awsjson_protocol"; protocolRequire = "smithy.protocol.awsjson";
                    protocolExpr = "awsjson_protocol.new({ version = \"1.1\", service_id = c.service_id })";
                } else if (n.equals("aws.protocols#restJson1")) {
                    protocolAlias = "restjson_protocol"; protocolRequire = "smithy.protocol.restjson";
                    protocolExpr = "restjson_protocol.new()";
                } else if (n.equals("aws.protocols#restXml")) {
                    protocolAlias = "restxml_protocol"; protocolRequire = "smithy.protocol.restxml";
                    var noWrap = service.getAllTraits().get(traitId).toNode().asObjectNode()
                            .flatMap(o -> o.getBooleanMember("noErrorWrapping")).map(b -> b.getValue()).orElse(false);
                    protocolExpr = noWrap ? "restxml_protocol.new({ no_error_wrapping = true })" : "restxml_protocol.new()";
                } else if (n.equals("aws.protocols#awsQuery")) {
                    protocolAlias = "query_protocol"; protocolRequire = "smithy.protocol.awsquery";
                    protocolExpr = "query_protocol.new(\"awsQuery\")";
                } else if (n.equals("aws.protocols#ec2Query")) {
                    protocolAlias = "query_protocol"; protocolRequire = "smithy.protocol.ec2query";
                    protocolExpr = "query_protocol.new(\"ec2Query\")";
                } else if (n.equals("smithy.protocols#rpcv2Cbor")) {
                    protocolAlias = "rpcv2_protocol"; protocolRequire = "smithy.protocol.rpcv2";
                    protocolExpr = "rpcv2_protocol.new_cbor()";
                }
            }

            String signingName = service.getId().getName().toLowerCase(Locale.US);
            var sigv4 = service.getTrait(software.amazon.smithy.aws.traits.auth.SigV4Trait.class);
            if (sigv4.isPresent()) signingName = sigv4.get().getName();

            // Requires
            writer.write("-- Code generated by lua-client-codegen. DO NOT EDIT.");
            writer.write("");
            writer.write("local async = require(\"smithy.async\")");
            writer.write("local base_client = require(\"smithy.client\")");
            writer.write("local defaults = require(\"smithy.defaults\")");
            writer.write("local endpoint = require(\"smithy.endpoint\")");
            writer.write("local endpoint_rules = require(\"$L.endpoint_rules\")", serviceNs);
            if (protocolRequire != null) {
                writer.write("local $L = require(\"$L\")", protocolAlias, protocolRequire);
            }
            writer.write("local schemas = require(\"$L.schemas\")", serviceNs);
            writer.write("local traits = require(\"smithy.traits\")");
            writer.write("local types = require(\"$L.types\")", serviceNs);
            var emittedAliases = new HashSet<String>();
            for (var resolver : configResolvers) {
                if (emittedAliases.add(resolver.requireAlias())) {
                    writer.write("local $L = require(\"$L\")", resolver.requireAlias(), resolver.requirePath());
                }
            }
            for (var finalizer : configFinalizers) {
                if (emittedAliases.add(finalizer.requireAlias())) {
                    writer.write("local $L = require(\"$L\")", finalizer.requireAlias(), finalizer.requirePath());
                }
            }
            writer.write("");

            // Client record
            writer.write("local record Client");
            writer.indent();
            writer.write("config: {string:any}");
            writer.write("invokeOperation: function(Client, any, any, any, any): async.Operation<any>");
            for (var operation : topDown.getContainedOperations(service)) {
                var opName = symbolProvider.toSymbol(operation).getName();
                var inputName = operationIndex.expectInputShape(operation).getId().getName(service);
                var outputName = operationIndex.expectOutputShape(operation).getId().getName(service);
                writer.write("$L: function(Client, types.$L, any): async.Operation<types.$L>",
                        opName, inputName, outputName);
            }
            writer.dedent();
            writer.write("end");
            writer.write("");

            writer.write("local record M");
            writer.indent();
            writer.write("new: function(cfg?: {string:any}): Client");
            writer.dedent();
            writer.write("end");
            writer.write("");

            // Metatable
            writer.write("local Client_mt: metatable<Client> = { __index = {} as Client }");
            writer.write("local C = Client_mt.__index as Client");
            writer.write("C.invokeOperation = base_client.invokeOperation");
            writer.write("");

            // Constructor
            writer.write("function M.new(cfg?: {string:any}): Client");
            writer.indent();
            writer.write("local c = cfg or {}");
            writer.write("c.service_id = $S", service.getId().getName());
            if (protocolExpr != null) {
                writer.write("if not c.protocol then c.protocol = $L end", protocolExpr);
            }
            writer.write("if not c.endpoint_provider then");
            writer.indent();
            writer.write("c.endpoint_provider = function(params)");
            writer.indent();
            writer.write("return endpoint.resolve(endpoint_rules, params)");
            writer.dedent();
            writer.write("end");
            writer.dedent();
            writer.write("end");
            writer.write("if not c.auth_scheme_resolver then");
            writer.indent();
            writer.write("c.auth_scheme_resolver = function(_service, operation)");
            writer.indent();
            writer.write("local auth_trait = operation:trait(traits.AUTH) or _service:trait(traits.AUTH)");
            writer.write("local options = {}");
            writer.write("for _, scheme in ipairs(auth_trait or {}) do");
            writer.indent();
            writer.write("local scheme_id = scheme.scheme_id or scheme");
            writer.write("if scheme_id == \"aws.auth#sigv4\" or scheme_id == \"aws.auth#sigv4a\" then");
            writer.indent();
            writer.write("options[#options + 1] = { scheme_id = scheme_id, signer_properties = { signing_name = $S, signing_region = c.region } }", signingName);
            writer.dedent();
            writer.write("else");
            writer.indent();
            writer.write("options[#options + 1] = { scheme_id = scheme_id }");
            writer.dedent();
            writer.write("end");
            writer.dedent();
            writer.write("end");
            writer.write("return options");
            writer.dedent();
            writer.write("end");
            writer.dedent();
            writer.write("end");
            writer.write("defaults.resolve_auth_schemes(c)");
            writer.write("defaults.resolve_identity_resolvers(c)");
            writer.write("defaults.resolve_http_client(c)");
            writer.write("defaults.resolve_retry_strategy(c)");
            for (var resolver : configResolvers) {
                writer.write(resolver.functionCall().replace("cfg", "c"));
            }
            writer.write("local self = setmetatable(base_client.new(c) as Client, Client_mt)");
            for (var finalizer : configFinalizers) {
                writer.write(finalizer.functionCall().replace("cfg", "c"));
            }
            writer.write("return self");
            writer.dedent();
            writer.write("end");
            writer.write("");

            // Operation methods
            for (var operation : topDown.getContainedOperations(service)) {
                var opName = symbolProvider.toSymbol(operation).getName();
                var opSchemaName = operation.getId().getName(service);
                var inputName = operationIndex.expectInputShape(operation).getId().getName(service);
                var outputName = operationIndex.expectOutputShape(operation).getId().getName(service);
                writer.write("function C:$L(input: types.$L, options: any): async.Operation<types.$L>",
                        opName, inputName, outputName);
                writer.indent();
                writer.write("return self:invokeOperation(schemas.Service, schemas.$L, input, options) as async.Operation<types.$L>",
                        opSchemaName, outputName);
                writer.dedent();
                writer.write("end");
                writer.write("");
            }

            writer.write("return M");
        });
    }
}
