-- Code generated by lua-client-codegen. DO NOT EDIT.

local awsjson_protocol = require("smithy.protocol.awsjson")
local base_client = require("smithy.client")
local defaults = require("smithy.defaults")
local schemas = require("jsonrpc10.schemas")
local traits = require("smithy.traits")

local M = {}

local Client = {}
Client.__index = Client

Client.invokeOperation = base_client.invokeOperation

function M.new(cfg)
    cfg = cfg or {}
    cfg.service_id = "JsonRpc10"
    if not cfg.protocol then
        cfg.protocol = awsjson_protocol.new({ version = "1.0", service_id = cfg.service_id })
    end
    if not cfg.auth_scheme_resolver then
        cfg.auth_scheme_resolver = function(service, operation)
            local auth_trait = operation:trait(traits.AUTH) or service:trait(traits.AUTH)
            local options = {}
            for _, scheme in ipairs(auth_trait or {}) do
                local scheme_id = scheme.scheme_id or scheme
                if scheme_id == "aws.auth#sigv4" or scheme_id == "aws.auth#sigv4a" then
                    options[#options + 1] = { scheme_id = scheme_id, signer_properties = { signing_name = "jsonrpc10", signing_region = cfg.region } }
                else
                    options[#options + 1] = { scheme_id = scheme_id }
                end
            end
            return options
        end
    end
    defaults.resolve_auth_schemes(cfg)
    defaults.resolve_identity_resolvers(cfg)
    defaults.resolve_http_client(cfg)
    defaults.resolve_retry_strategy(cfg)
    local self = setmetatable(base_client.new(cfg), Client)
    return self
end

function Client:contentTypeParameters(input, options)
    return self:invokeOperation(schemas.Service, schemas.ContentTypeParameters, input, options)
end

function Client:emptyInputAndEmptyOutput(input, options)
    return self:invokeOperation(schemas.Service, schemas.EmptyInputAndEmptyOutput, input, options)
end

function Client:endpointOperation(input, options)
    return self:invokeOperation(schemas.Service, schemas.EndpointOperation, input, options)
end

function Client:endpointWithHostLabelOperation(input, options)
    return self:invokeOperation(schemas.Service, schemas.EndpointWithHostLabelOperation, input, options)
end

function Client:greetingWithErrors(input, options)
    return self:invokeOperation(schemas.Service, schemas.GreetingWithErrors, input, options)
end

function Client:hostWithPathOperation(input, options)
    return self:invokeOperation(schemas.Service, schemas.HostWithPathOperation, input, options)
end

function Client:jsonUnions(input, options)
    return self:invokeOperation(schemas.Service, schemas.JsonUnions, input, options)
end

function Client:noInputAndNoOutput(input, options)
    return self:invokeOperation(schemas.Service, schemas.NoInputAndNoOutput, input, options)
end

function Client:noInputAndOutput(input, options)
    return self:invokeOperation(schemas.Service, schemas.NoInputAndOutput, input, options)
end

function Client:operationWithDefaults(input, options)
    return self:invokeOperation(schemas.Service, schemas.OperationWithDefaults, input, options)
end

function Client:operationWithNestedStructure(input, options)
    return self:invokeOperation(schemas.Service, schemas.OperationWithNestedStructure, input, options)
end

function Client:operationWithRequiredMembers(input, options)
    return self:invokeOperation(schemas.Service, schemas.OperationWithRequiredMembers, input, options)
end

function Client:operationWithRequiredMembersWithDefaults(input, options)
    return self:invokeOperation(schemas.Service, schemas.OperationWithRequiredMembersWithDefaults, input, options)
end

function Client:putWithContentEncoding(input, options)
    return self:invokeOperation(schemas.Service, schemas.PutWithContentEncoding, input, options)
end

function Client:queryIncompatibleOperation(input, options)
    return self:invokeOperation(schemas.Service, schemas.QueryIncompatibleOperation, input, options)
end

function Client:simpleScalarProperties(input, options)
    return self:invokeOperation(schemas.Service, schemas.SimpleScalarProperties, input, options)
end

return M
