-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: awsJson1_0

local types = require("jsonrpc10.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.awsjson")
local protocol = protocol_mod.new({ version = "1.0" })

local service = schema.service({
    id = shape_id.from("aws.protocoltests.json10", "JsonRpc10"),
    version = "2020-07-14",
    traits = {},
})

describe("OperationWithDefaults request", function()
    it("AwsJson10ClientPopulatesDefaultValuesInInput", function()
        local input = {
            defaults = {},
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json10", "OperationWithDefaults"),
            input = types.OperationWithDefaultsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-amz-json-1.0")
        local body_str = h.read_body(request.body)
        h.assert_json_eq(body_str, [[{
            "defaults": {
                "defaultString": "hi",
                "defaultBoolean": true,
                "defaultList": [],
                "defaultDocumentMap": {},
                "defaultDocumentString": "hi",
                "defaultDocumentBoolean": true,
                "defaultDocumentList": [],
                "defaultTimestamp": 0,
                "defaultBlob": "YWJj",
                "defaultByte": 1,
                "defaultShort": 1,
                "defaultInteger": 10,
                "defaultLong": 100,
                "defaultFloat": 1.0,
                "defaultDouble": 1.0,
                "defaultMap": {},
                "defaultEnum": "FOO",
                "defaultIntEnum": 1,
                "emptyString": "",
                "falseBoolean": false,
                "emptyBlob": "",
                "zeroByte": 0,
                "zeroShort": 0,
                "zeroInteger": 0,
                "zeroLong": 0,
                "zeroFloat": 0.0,
                "zeroDouble": 0.0
            }
        }]])
    end)

    it("AwsJson10ClientSkipsTopLevelDefaultValuesInInput", function()
        local input = {}
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json10", "OperationWithDefaults"),
            input = types.OperationWithDefaultsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-amz-json-1.0")
        local body_str = h.read_body(request.body)
        h.assert_json_eq(body_str, [[{
        }]])
    end)

    it("AwsJson10ClientUsesExplicitlyProvidedMemberValuesOverDefaults", function()
        local input = {
            defaults = {
            defaultString = "bye",
            defaultBoolean = true,
            defaultList = {
            "a",
        },
            defaultDocumentMap = {
            name = "Jack",
        },
            defaultDocumentString = "bye",
            defaultDocumentBoolean = true,
            defaultDocumentList = {
            "b",
        },
            defaultNullDocument = "notNull",
            defaultTimestamp = 1,
            defaultBlob = "hi",
            defaultByte = 2,
            defaultShort = 2,
            defaultInteger = 20,
            defaultLong = 200,
            defaultFloat = 2.0,
            defaultDouble = 2.0,
            defaultMap = {
            name = "Jack",
        },
            defaultEnum = "BAR",
            defaultIntEnum = 2,
            emptyString = "foo",
            falseBoolean = true,
            emptyBlob = "hi",
            zeroByte = 1,
            zeroShort = 1,
            zeroInteger = 1,
            zeroLong = 1,
            zeroFloat = 1.0,
            zeroDouble = 1.0,
        },
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json10", "OperationWithDefaults"),
            input = types.OperationWithDefaultsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-amz-json-1.0")
        local body_str = h.read_body(request.body)
        h.assert_json_eq(body_str, [[{
            "defaults": {
                "defaultString": "bye",
                "defaultBoolean": true,
                "defaultList": ["a"],
                "defaultDocumentMap": {"name": "Jack"},
                "defaultDocumentString": "bye",
                "defaultDocumentBoolean": true,
                "defaultDocumentList": ["b"],
                "defaultNullDocument": "notNull",
                "defaultTimestamp": 1,
                "defaultBlob": "aGk=",
                "defaultByte": 2,
                "defaultShort": 2,
                "defaultInteger": 20,
                "defaultLong": 200,
                "defaultFloat": 2.0,
                "defaultDouble": 2.0,
                "defaultMap": {"name": "Jack"},
                "defaultEnum": "BAR",
                "defaultIntEnum": 2,
                "emptyString": "foo",
                "falseBoolean": true,
                "emptyBlob": "aGk=",
                "zeroByte": 1,
                "zeroShort": 1,
                "zeroInteger": 1,
                "zeroLong": 1,
                "zeroFloat": 1.0,
                "zeroDouble": 1.0
            }
        }]])
    end)

    it("AwsJson10ClientUsesExplicitlyProvidedValuesInTopLevel", function()
        local input = {
            topLevelDefault = "hi",
            otherTopLevelDefault = 0,
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json10", "OperationWithDefaults"),
            input = types.OperationWithDefaultsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-amz-json-1.0")
        local body_str = h.read_body(request.body)
        h.assert_json_eq(body_str, [[{
            "topLevelDefault": "hi",
            "otherTopLevelDefault": 0
        }]])
    end)

    it("AwsJson10ClientIgnoresNonTopLevelDefaultsOnMembersWithClientOptional", function()
        local input = {
            clientOptionalDefaults = {},
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json10", "OperationWithDefaults"),
            input = types.OperationWithDefaultsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-amz-json-1.0")
        local body_str = h.read_body(request.body)
        h.assert_json_eq(body_str, [[{
            "clientOptionalDefaults": {}
        }]])
    end)

end)
