-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: awsJson1_0

local types = require("jsonrpc10.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.awsjson")
local protocol = protocol_mod.new({ version = "1.0" })

local service = schema.service({
    id = shape_id.from("aws.protocoltests.json10", "JsonRpc10"),
    version = "2020-07-14",
    traits = {},
})

describe("JsonUnions response", function()
    it("AwsJson10DeserializeStringUnionValue", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.0",
            },
            body = http.string_reader([[{
                "contents": {
                    "stringValue": "foo"
                }
            }]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json10", "JsonUnions"),
            input = schema.new({ type = "structure" }),
            output = types.JsonUnionsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            contents = {
            stringValue = "foo",
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("AwsJson10DeserializeBooleanUnionValue", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.0",
            },
            body = http.string_reader([[{
                "contents": {
                    "booleanValue": true
                }
            }]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json10", "JsonUnions"),
            input = schema.new({ type = "structure" }),
            output = types.JsonUnionsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            contents = {
            booleanValue = true,
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("AwsJson10DeserializeNumberUnionValue", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.0",
            },
            body = http.string_reader([[{
                "contents": {
                    "numberValue": 1
                }
            }]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json10", "JsonUnions"),
            input = schema.new({ type = "structure" }),
            output = types.JsonUnionsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            contents = {
            numberValue = 1,
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("AwsJson10DeserializeBlobUnionValue", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.0",
            },
            body = http.string_reader([[{
                "contents": {
                    "blobValue": "Zm9v"
                }
            }]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json10", "JsonUnions"),
            input = schema.new({ type = "structure" }),
            output = types.JsonUnionsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            contents = {
            blobValue = "foo",
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("AwsJson10DeserializeTimestampUnionValue", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.0",
            },
            body = http.string_reader([[{
                "contents": {
                    "timestampValue": 1398796238
                }
            }]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json10", "JsonUnions"),
            input = schema.new({ type = "structure" }),
            output = types.JsonUnionsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            contents = {
            timestampValue = 1398796238,
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("AwsJson10DeserializeEnumUnionValue", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.0",
            },
            body = http.string_reader([[{
                "contents": {
                    "enumValue": "Foo"
                }
            }]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json10", "JsonUnions"),
            input = schema.new({ type = "structure" }),
            output = types.JsonUnionsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            contents = {
            enumValue = "Foo",
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("AwsJson10DeserializeIntEnumUnionValue", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.0",
            },
            body = http.string_reader([[{
                "contents": {
                    "intEnumValue": 1
                }
            }]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json10", "JsonUnions"),
            input = schema.new({ type = "structure" }),
            output = types.JsonUnionsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            contents = {
            intEnumValue = 1,
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("AwsJson10DeserializeListUnionValue", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.0",
            },
            body = http.string_reader([[{
                "contents": {
                    "listValue": ["foo", "bar"]
                }
            }]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json10", "JsonUnions"),
            input = schema.new({ type = "structure" }),
            output = types.JsonUnionsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            contents = {
            listValue = {
            "foo",
            "bar",
        },
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("AwsJson10DeserializeMapUnionValue", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.0",
            },
            body = http.string_reader([[{
                "contents": {
                    "mapValue": {
                        "foo": "bar",
                        "spam": "eggs"
                    }
                }
            }]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json10", "JsonUnions"),
            input = schema.new({ type = "structure" }),
            output = types.JsonUnionsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            contents = {
            mapValue = {
            foo = "bar",
            spam = "eggs",
        },
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("AwsJson10DeserializeStructureUnionValue", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.0",
            },
            body = http.string_reader([[{
                "contents": {
                    "structureValue": {
                        "hi": "hello"
                    }
                }
            }]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json10", "JsonUnions"),
            input = schema.new({ type = "structure" }),
            output = types.JsonUnionsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            contents = {
            structureValue = {
            hi = "hello",
        },
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("AwsJson10DeserializeIgnoreType", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.0",
            },
            body = http.string_reader([[{
                "contents": {
                    "__type": "aws.protocoltests.json10#MyUnion",
                    "structureValue": {
                        "hi": "hello"
                    }
                }
            }]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json10", "JsonUnions"),
            input = schema.new({ type = "structure" }),
            output = types.JsonUnionsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            contents = {
            structureValue = {
            hi = "hello",
        },
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("AwsJson10DeserializeAllowNulls", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.0",
            },
            body = http.string_reader([[{
                "contents": {
                  "stringValue": null,
                  "booleanValue": null,
                  "numberValue": null,
                  "blobValue": null,
                  "timestampValue": null,
                  "enumValue": null,
                  "intEnumValue": null,
                  "listValue": null,
                  "mapValue": null,
                  "structureValue": {
                      "hi": "hello"
                  }
                }
            }]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json10", "JsonUnions"),
            input = schema.new({ type = "structure" }),
            output = types.JsonUnionsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            contents = {
            structureValue = {
            hi = "hello",
        },
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

end)
