-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: awsJson1_0

local types = require("jsonrpc10.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.awsjson")
local protocol = protocol_mod.new({ version = "1.0" })

local service = schema.service({
    id = shape_id.from("aws.protocoltests.json10", "JsonRpc10"),
    version = "2020-07-14",
    traits = {},
})

describe("EndpointWithHostLabelOperation request", function()
    it("AwsJson10EndpointTraitWithHostLabel", function()
        local input = {
            label = "bar",
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json10", "EndpointWithHostLabelOperation"),
            input = types.EndpointWithHostLabelOperationInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        local body_str = h.read_body(request.body)
        h.assert_json_eq(body_str, [[{"label": "bar"}]])
    end)

end)
