-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: awsJson1_0

local types = require("jsonrpc10.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.awsjson")
local protocol = protocol_mod.new({ version = "1.0" })

local service = schema.service({
    id = shape_id.from("aws.protocoltests.json10", "JsonRpc10"),
    version = "2020-07-14",
    traits = {},
})

describe("EmptyInputAndEmptyOutput response", function()
    it("AwsJson10EmptyInputAndEmptyOutputSendJsonObject", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/x-amz-json-1.0",
            },
            body = http.string_reader([[{}]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.json10", "EmptyInputAndEmptyOutput"),
            input = schema.new({ type = "structure" }),
            output = types.EmptyInputAndEmptyOutputOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
    end)

end)
