-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: ec2Query

local types = require("ec2protocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.ec2query")
local protocol = protocol_mod.new({ version = "2020-01-08" })

local service = schema.service({
    id = shape_id.from("aws.protocoltests.ec2", "AwsEc2"),
    version = "2020-01-08",
    traits = {},
})

describe("GreetingWithErrors InvalidGreeting error", function()
    it("Ec2InvalidGreetingError", function()
        local response = {
            status_code = 400,
            headers = {
                ["Content-Type"] = "text/xml;charset=UTF-8",
            },
            body = http.string_reader([[<Response>
                <Errors>
                    <Error>
                        <Code>InvalidGreeting</Code>
                        <Message>Hi</Message>
                    </Error>
                </Errors>
                <RequestID>foo-id</RequestID>
            </Response>
            ]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.ec2", "GreetingWithErrors"),
            input = schema.new({ type = "structure" }),
            output = types.InvalidGreeting,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(output, "expected nil output for error response")
        assert.is_not_nil(err, "expected error")
        assert.are.equal("api", err.type)
        assert.is_true(err.code == "InvalidGreeting" or (err.code and err.code:find("InvalidGreeting", 1, true) ~= nil),
            "error code: expected InvalidGreeting, got: " .. tostring(err.code))
        assert.are.equal("Hi", err.message)
    end)

end)
