-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: ec2Query

local types = require("ec2protocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.ec2query")
local protocol = protocol_mod.new({ version = "2020-01-08" })

local service = schema.service({
    id = shape_id.from("aws.protocoltests.ec2", "AwsEc2"),
    version = "2020-01-08",
    traits = {},
})

describe("SimpleInputParams request", function()
    it("Ec2SimpleInputParamsStrings", function()
        local input = {
            Foo = "val1",
            Bar = "val2",
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.ec2", "SimpleInputParams"),
            input = types.SimpleInputParamsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-www-form-urlencoded")
        local body_str = h.read_body(request.body)
        h.assert_form_eq(body_str, [[Action=SimpleInputParams&Version=2020-01-08&Foo=val1&Bar=val2]])
    end)

    it("Ec2SimpleInputParamsStringAndBooleanTrue", function()
        local input = {
            Foo = "val1",
            Baz = true,
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.ec2", "SimpleInputParams"),
            input = types.SimpleInputParamsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-www-form-urlencoded")
        local body_str = h.read_body(request.body)
        h.assert_form_eq(body_str, [[Action=SimpleInputParams&Version=2020-01-08&Foo=val1&Baz=true]])
    end)

    it("Ec2SimpleInputParamsStringsAndBooleanFalse", function()
        local input = {
            Baz = false,
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.ec2", "SimpleInputParams"),
            input = types.SimpleInputParamsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-www-form-urlencoded")
        local body_str = h.read_body(request.body)
        h.assert_form_eq(body_str, [[Action=SimpleInputParams&Version=2020-01-08&Baz=false]])
    end)

    it("Ec2SimpleInputParamsInteger", function()
        local input = {
            Bam = 10,
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.ec2", "SimpleInputParams"),
            input = types.SimpleInputParamsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-www-form-urlencoded")
        local body_str = h.read_body(request.body)
        h.assert_form_eq(body_str, [[Action=SimpleInputParams&Version=2020-01-08&Bam=10]])
    end)

    it("Ec2SimpleInputParamsFloat", function()
        local input = {
            Boo = 10.8,
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.ec2", "SimpleInputParams"),
            input = types.SimpleInputParamsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-www-form-urlencoded")
        local body_str = h.read_body(request.body)
        h.assert_form_eq(body_str, [[Action=SimpleInputParams&Version=2020-01-08&Boo=10.8]])
    end)

    it("Ec2SimpleInputParamsBlob", function()
        local input = {
            Qux = "value",
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.ec2", "SimpleInputParams"),
            input = types.SimpleInputParamsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-www-form-urlencoded")
        local body_str = h.read_body(request.body)
        h.assert_form_eq(body_str, [[Action=SimpleInputParams&Version=2020-01-08&Qux=dmFsdWU%3D]])
    end)

    it("Ec2Enums", function()
        local input = {
            FooEnum = "Foo",
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.ec2", "SimpleInputParams"),
            input = types.SimpleInputParamsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-www-form-urlencoded")
        local body_str = h.read_body(request.body)
        h.assert_form_eq(body_str, [[Action=SimpleInputParams&Version=2020-01-08&FooEnum=Foo]])
    end)

    it("Ec2Query", function()
        local input = {
            HasQueryName = "Hi",
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.ec2", "SimpleInputParams"),
            input = types.SimpleInputParamsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-www-form-urlencoded")
        local body_str = h.read_body(request.body)
        h.assert_form_eq(body_str, [[Action=SimpleInputParams&Version=2020-01-08&HasQueryName=Hi]])
    end)

    it("Ec2QueryIsPreferred", function()
        local input = {
            HasQueryAndXmlName = "Hi",
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.ec2", "SimpleInputParams"),
            input = types.SimpleInputParamsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-www-form-urlencoded")
        local body_str = h.read_body(request.body)
        h.assert_form_eq(body_str, [[Action=SimpleInputParams&Version=2020-01-08&HasQueryAndXmlName=Hi]])
    end)

    it("Ec2XmlNameIsUppercased", function()
        local input = {
            UsesXmlName = "Hi",
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.ec2", "SimpleInputParams"),
            input = types.SimpleInputParamsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-www-form-urlencoded")
        local body_str = h.read_body(request.body)
        h.assert_form_eq(body_str, [[Action=SimpleInputParams&Version=2020-01-08&UsesXmlName=Hi]])
    end)

    it("Ec2QueryNameDistinctFromXmlNameAndMemberName", function()
        local input = {
            DistinctQueryName = "value1",
            DistinctQueryAndXmlName = "value2",
            DistinctXmlName = "value3",
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.ec2", "SimpleInputParams"),
            input = types.SimpleInputParamsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-www-form-urlencoded")
        local body_str = h.read_body(request.body)
        h.assert_form_eq(body_str, [[Action=SimpleInputParams&Version=2020-01-08&QueryName=value1&queryAndXmlName=value2&XmlNameOnly=value3]])
    end)

    it("Ec2QuerySupportsNaNFloatInputs", function()
        local input = {
            FloatValue = 0/0,
            Boo = 0/0,
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.ec2", "SimpleInputParams"),
            input = types.SimpleInputParamsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-www-form-urlencoded")
        local body_str = h.read_body(request.body)
        h.assert_form_eq(body_str, [[Action=SimpleInputParams&Version=2020-01-08&FloatValue=NaN&Boo=NaN]])
    end)

    it("Ec2QuerySupportsInfinityFloatInputs", function()
        local input = {
            FloatValue = math.huge,
            Boo = math.huge,
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.ec2", "SimpleInputParams"),
            input = types.SimpleInputParamsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-www-form-urlencoded")
        local body_str = h.read_body(request.body)
        h.assert_form_eq(body_str, [[Action=SimpleInputParams&Version=2020-01-08&FloatValue=Infinity&Boo=Infinity]])
    end)

    it("Ec2QuerySupportsNegativeInfinityFloatInputs", function()
        local input = {
            FloatValue = -math.huge,
            Boo = -math.huge,
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.ec2", "SimpleInputParams"),
            input = types.SimpleInputParamsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/")
        h.assert_header(request, "Content-Type", "application/x-www-form-urlencoded")
        local body_str = h.read_body(request.body)
        h.assert_form_eq(body_str, [[Action=SimpleInputParams&Version=2020-01-08&FloatValue=-Infinity&Boo=-Infinity]])
    end)

end)
