-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: ec2Query

local types = require("ec2protocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.ec2query")
local protocol = protocol_mod.new({ version = "2020-01-08" })

local service = schema.service({
    id = shape_id.from("aws.protocoltests.ec2", "AwsEc2"),
    version = "2020-01-08",
    traits = {},
})

describe("SimpleScalarXmlProperties response", function()
    it("Ec2SimpleScalarProperties", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "text/xml;charset=UTF-8",
            },
            body = http.string_reader([[<SimpleScalarXmlPropertiesResponse xmlns="https://example.com/">
                <stringValue>string</stringValue>
                <emptyStringValue/>
                <trueBooleanValue>true</trueBooleanValue>
                <falseBooleanValue>false</falseBooleanValue>
                <byteValue>1</byteValue>
                <shortValue>2</shortValue>
                <integerValue>3</integerValue>
                <longValue>4</longValue>
                <floatValue>5.5</floatValue>
                <DoubleDribble>6.5</DoubleDribble>
                <requestId>requestid</requestId>
            </SimpleScalarXmlPropertiesResponse>
            ]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.ec2", "SimpleScalarXmlProperties"),
            input = schema.new({ type = "structure" }),
            output = types.SimpleScalarXmlPropertiesOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            stringValue = "string",
            emptyStringValue = "",
            trueBooleanValue = true,
            falseBooleanValue = false,
            byteValue = 1,
            shortValue = 2,
            integerValue = 3,
            longValue = 4,
            floatValue = 5.5,
            doubleValue = 6.5,
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("Ec2QuerySupportsNaNFloatOutputs", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "text/xml;charset=UTF-8",
            },
            body = http.string_reader([[<SimpleScalarXmlPropertiesResponse xmlns="https://example.com/">
                <floatValue>NaN</floatValue>
                <DoubleDribble>NaN</DoubleDribble>
            </SimpleScalarXmlPropertiesResponse>
            ]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.ec2", "SimpleScalarXmlProperties"),
            input = schema.new({ type = "structure" }),
            output = types.SimpleScalarXmlPropertiesOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            floatValue = 0/0,
            doubleValue = 0/0,
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("Ec2QuerySupportsInfinityFloatOutputs", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "text/xml;charset=UTF-8",
            },
            body = http.string_reader([[<SimpleScalarXmlPropertiesResponse xmlns="https://example.com/">
                <floatValue>Infinity</floatValue>
                <DoubleDribble>Infinity</DoubleDribble>
            </SimpleScalarXmlPropertiesResponse>
            ]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.ec2", "SimpleScalarXmlProperties"),
            input = schema.new({ type = "structure" }),
            output = types.SimpleScalarXmlPropertiesOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            floatValue = math.huge,
            doubleValue = math.huge,
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("Ec2QuerySupportsNegativeInfinityFloatOutputs", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "text/xml;charset=UTF-8",
            },
            body = http.string_reader([[<SimpleScalarXmlPropertiesResponse xmlns="https://example.com/">
                <floatValue>-Infinity</floatValue>
                <DoubleDribble>-Infinity</DoubleDribble>
            </SimpleScalarXmlPropertiesResponse>
            ]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.ec2", "SimpleScalarXmlProperties"),
            input = schema.new({ type = "structure" }),
            output = types.SimpleScalarXmlPropertiesOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            floatValue = -math.huge,
            doubleValue = -math.huge,
        }
        h.assert_deep_eq(output, expected, "output")
    end)

end)
