-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: ec2Query

local types = require("ec2protocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.ec2query")
local protocol = protocol_mod.new({ version = "2020-01-08" })

local service = schema.service({
    id = shape_id.from("aws.protocoltests.ec2", "AwsEc2"),
    version = "2020-01-08",
    traits = {},
})

describe("FractionalSeconds response", function()
    it("Ec2QueryDateTimeWithFractionalSeconds", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "text/xml;charset=UTF-8",
            },
            body = http.string_reader([[<FractionalSecondsResponse xmlns="https://example.com/">
                <datetime>2000-01-02T20:34:56.123Z</datetime>
                <requestId>requestid</requestId>
            </FractionalSecondsResponse>
            ]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.ec2", "FractionalSeconds"),
            input = schema.new({ type = "structure" }),
            output = types.FractionalSecondsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            datetime = 9.46845296123E8,
        }
        h.assert_deep_eq(output, expected, "output")
    end)

end)
