-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: ec2Query

local types = require("ec2protocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.ec2query")
local protocol = protocol_mod.new({ version = "2020-01-08" })

local service = schema.service({
    id = shape_id.from("aws.protocoltests.ec2", "AwsEc2"),
    version = "2020-01-08",
    traits = {},
})

describe("RecursiveXmlShapes response", function()
    it("Ec2RecursiveShapes", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "text/xml;charset=UTF-8",
            },
            body = http.string_reader([[<RecursiveXmlShapesResponse xmlns="https://example.com/">
                <nested>
                    <foo>Foo1</foo>
                    <nested>
                        <bar>Bar1</bar>
                        <recursiveMember>
                            <foo>Foo2</foo>
                            <nested>
                                <bar>Bar2</bar>
                            </nested>
                        </recursiveMember>
                    </nested>
                </nested>
                <requestId>requestid</requestId>
            </RecursiveXmlShapesResponse>
            ]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.ec2", "RecursiveXmlShapes"),
            input = schema.new({ type = "structure" }),
            output = types.RecursiveXmlShapesOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            nested = {
            foo = "Foo1",
            nested = {
            bar = "Bar1",
            recursiveMember = {
            foo = "Foo2",
            nested = {
            bar = "Bar2",
        },
        },
        },
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

end)
