-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: ec2Query

local types = require("ec2protocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.ec2query")
local protocol = protocol_mod.new({ version = "2020-01-08" })

local service = schema.service({
    id = shape_id.from("aws.protocoltests.ec2", "AwsEc2"),
    version = "2020-01-08",
    traits = {},
})

describe("HostWithPathOperation request", function()
    it("Ec2QueryHostWithPath", function()
        local input = {}
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.ec2", "HostWithPathOperation"),
            input = types.HostWithPathOperationInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/custom/" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/custom/")
        local body_str = h.read_body(request.body)
        h.assert_form_eq(body_str, [[Action=HostWithPathOperation&Version=2020-01-08]])
    end)

end)
