-- Code generated by lua-client-codegen. DO NOT EDIT.

local base_client = require("smithy.client")
local defaults = require("smithy.defaults")
local restxml_protocol = require("smithy.protocol.restxml")
local schemas = require("restxmlprotocol.schemas")
local traits = require("smithy.traits")

local M = {}

local Client = {}
Client.__index = Client

Client.invokeOperation = base_client.invokeOperation

function M.new(cfg)
    cfg = cfg or {}
    cfg.service_id = "RestXml"
    if not cfg.protocol then
        cfg.protocol = restxml_protocol.new()
    end
    if not cfg.auth_scheme_resolver then
        cfg.auth_scheme_resolver = function(service, operation)
            local auth_trait = operation:trait(traits.AUTH) or service:trait(traits.AUTH)
            local options = {}
            for _, scheme in ipairs(auth_trait or {}) do
                local scheme_id = scheme.scheme_id or scheme
                if scheme_id == "aws.auth#sigv4" or scheme_id == "aws.auth#sigv4a" then
                    options[#options + 1] = { scheme_id = scheme_id, signer_properties = { signing_name = "restxml", signing_region = cfg.region } }
                else
                    options[#options + 1] = { scheme_id = scheme_id }
                end
            end
            return options
        end
    end
    defaults.resolve_auth_schemes(cfg)
    defaults.resolve_identity_resolvers(cfg)
    defaults.resolve_http_client(cfg)
    defaults.resolve_retry_strategy(cfg)
    local self = setmetatable(base_client.new(cfg), Client)
    return self
end

function Client:allQueryStringTypes(input, options)
    return self:invokeOperation(schemas.Service, schemas.AllQueryStringTypes, input, options)
end

function Client:bodyWithXmlName(input, options)
    return self:invokeOperation(schemas.Service, schemas.BodyWithXmlName, input, options)
end

function Client:constantAndVariableQueryString(input, options)
    return self:invokeOperation(schemas.Service, schemas.ConstantAndVariableQueryString, input, options)
end

function Client:constantQueryString(input, options)
    return self:invokeOperation(schemas.Service, schemas.ConstantQueryString, input, options)
end

function Client:contentTypeParameters(input, options)
    return self:invokeOperation(schemas.Service, schemas.ContentTypeParameters, input, options)
end

function Client:datetimeOffsets(input, options)
    return self:invokeOperation(schemas.Service, schemas.DatetimeOffsets, input, options)
end

function Client:emptyInputAndEmptyOutput(input, options)
    return self:invokeOperation(schemas.Service, schemas.EmptyInputAndEmptyOutput, input, options)
end

function Client:endpointOperation(input, options)
    return self:invokeOperation(schemas.Service, schemas.EndpointOperation, input, options)
end

function Client:endpointWithHostLabelHeaderOperation(input, options)
    return self:invokeOperation(schemas.Service, schemas.EndpointWithHostLabelHeaderOperation, input, options)
end

function Client:endpointWithHostLabelOperation(input, options)
    return self:invokeOperation(schemas.Service, schemas.EndpointWithHostLabelOperation, input, options)
end

function Client:flattenedXmlMap(input, options)
    return self:invokeOperation(schemas.Service, schemas.FlattenedXmlMap, input, options)
end

function Client:flattenedXmlMapWithXmlName(input, options)
    return self:invokeOperation(schemas.Service, schemas.FlattenedXmlMapWithXmlName, input, options)
end

function Client:flattenedXmlMapWithXmlNamespace(input, options)
    return self:invokeOperation(schemas.Service, schemas.FlattenedXmlMapWithXmlNamespace, input, options)
end

function Client:fractionalSeconds(input, options)
    return self:invokeOperation(schemas.Service, schemas.FractionalSeconds, input, options)
end

function Client:greetingWithErrors(input, options)
    return self:invokeOperation(schemas.Service, schemas.GreetingWithErrors, input, options)
end

function Client:httpEmptyPrefixHeaders(input, options)
    return self:invokeOperation(schemas.Service, schemas.HttpEmptyPrefixHeaders, input, options)
end

function Client:httpEnumPayload(input, options)
    return self:invokeOperation(schemas.Service, schemas.HttpEnumPayload, input, options)
end

function Client:httpPayloadTraits(input, options)
    return self:invokeOperation(schemas.Service, schemas.HttpPayloadTraits, input, options)
end

function Client:httpPayloadTraitsWithMediaType(input, options)
    return self:invokeOperation(schemas.Service, schemas.HttpPayloadTraitsWithMediaType, input, options)
end

function Client:httpPayloadWithMemberXmlName(input, options)
    return self:invokeOperation(schemas.Service, schemas.HttpPayloadWithMemberXmlName, input, options)
end

function Client:httpPayloadWithStructure(input, options)
    return self:invokeOperation(schemas.Service, schemas.HttpPayloadWithStructure, input, options)
end

function Client:httpPayloadWithUnion(input, options)
    return self:invokeOperation(schemas.Service, schemas.HttpPayloadWithUnion, input, options)
end

function Client:httpPayloadWithXmlName(input, options)
    return self:invokeOperation(schemas.Service, schemas.HttpPayloadWithXmlName, input, options)
end

function Client:httpPayloadWithXmlNamespace(input, options)
    return self:invokeOperation(schemas.Service, schemas.HttpPayloadWithXmlNamespace, input, options)
end

function Client:httpPayloadWithXmlNamespaceAndPrefix(input, options)
    return self:invokeOperation(schemas.Service, schemas.HttpPayloadWithXmlNamespaceAndPrefix, input, options)
end

function Client:httpPrefixHeaders(input, options)
    return self:invokeOperation(schemas.Service, schemas.HttpPrefixHeaders, input, options)
end

function Client:httpRequestWithFloatLabels(input, options)
    return self:invokeOperation(schemas.Service, schemas.HttpRequestWithFloatLabels, input, options)
end

function Client:httpRequestWithGreedyLabelInPath(input, options)
    return self:invokeOperation(schemas.Service, schemas.HttpRequestWithGreedyLabelInPath, input, options)
end

function Client:httpRequestWithLabels(input, options)
    return self:invokeOperation(schemas.Service, schemas.HttpRequestWithLabels, input, options)
end

function Client:httpRequestWithLabelsAndTimestampFormat(input, options)
    return self:invokeOperation(schemas.Service, schemas.HttpRequestWithLabelsAndTimestampFormat, input, options)
end

function Client:httpResponseCode(input, options)
    return self:invokeOperation(schemas.Service, schemas.HttpResponseCode, input, options)
end

function Client:httpStringPayload(input, options)
    return self:invokeOperation(schemas.Service, schemas.HttpStringPayload, input, options)
end

function Client:ignoreQueryParamsInResponse(input, options)
    return self:invokeOperation(schemas.Service, schemas.IgnoreQueryParamsInResponse, input, options)
end

function Client:inputAndOutputWithHeaders(input, options)
    return self:invokeOperation(schemas.Service, schemas.InputAndOutputWithHeaders, input, options)
end

function Client:nestedXmlMaps(input, options)
    return self:invokeOperation(schemas.Service, schemas.NestedXmlMaps, input, options)
end

function Client:nestedXmlMapWithXmlName(input, options)
    return self:invokeOperation(schemas.Service, schemas.NestedXmlMapWithXmlName, input, options)
end

function Client:noInputAndNoOutput(input, options)
    return self:invokeOperation(schemas.Service, schemas.NoInputAndNoOutput, input, options)
end

function Client:noInputAndOutput(input, options)
    return self:invokeOperation(schemas.Service, schemas.NoInputAndOutput, input, options)
end

function Client:nullAndEmptyHeadersClient(input, options)
    return self:invokeOperation(schemas.Service, schemas.NullAndEmptyHeadersClient, input, options)
end

function Client:nullAndEmptyHeadersServer(input, options)
    return self:invokeOperation(schemas.Service, schemas.NullAndEmptyHeadersServer, input, options)
end

function Client:omitsNullSerializesEmptyString(input, options)
    return self:invokeOperation(schemas.Service, schemas.OmitsNullSerializesEmptyString, input, options)
end

function Client:putWithContentEncoding(input, options)
    return self:invokeOperation(schemas.Service, schemas.PutWithContentEncoding, input, options)
end

function Client:queryIdempotencyTokenAutoFill(input, options)
    return self:invokeOperation(schemas.Service, schemas.QueryIdempotencyTokenAutoFill, input, options)
end

function Client:queryParamsAsStringListMap(input, options)
    return self:invokeOperation(schemas.Service, schemas.QueryParamsAsStringListMap, input, options)
end

function Client:queryPrecedence(input, options)
    return self:invokeOperation(schemas.Service, schemas.QueryPrecedence, input, options)
end

function Client:recursiveShapes(input, options)
    return self:invokeOperation(schemas.Service, schemas.RecursiveShapes, input, options)
end

function Client:simpleScalarProperties(input, options)
    return self:invokeOperation(schemas.Service, schemas.SimpleScalarProperties, input, options)
end

function Client:timestampFormatHeaders(input, options)
    return self:invokeOperation(schemas.Service, schemas.TimestampFormatHeaders, input, options)
end

function Client:xmlAttributes(input, options)
    return self:invokeOperation(schemas.Service, schemas.XmlAttributes, input, options)
end

function Client:xmlAttributesInMiddle(input, options)
    return self:invokeOperation(schemas.Service, schemas.XmlAttributesInMiddle, input, options)
end

function Client:xmlAttributesOnPayload(input, options)
    return self:invokeOperation(schemas.Service, schemas.XmlAttributesOnPayload, input, options)
end

function Client:xmlBlobs(input, options)
    return self:invokeOperation(schemas.Service, schemas.XmlBlobs, input, options)
end

function Client:xmlEmptyBlobs(input, options)
    return self:invokeOperation(schemas.Service, schemas.XmlEmptyBlobs, input, options)
end

function Client:xmlEmptyLists(input, options)
    return self:invokeOperation(schemas.Service, schemas.XmlEmptyLists, input, options)
end

function Client:xmlEmptyMaps(input, options)
    return self:invokeOperation(schemas.Service, schemas.XmlEmptyMaps, input, options)
end

function Client:xmlEmptyStrings(input, options)
    return self:invokeOperation(schemas.Service, schemas.XmlEmptyStrings, input, options)
end

function Client:xmlEnums(input, options)
    return self:invokeOperation(schemas.Service, schemas.XmlEnums, input, options)
end

function Client:xmlIntEnums(input, options)
    return self:invokeOperation(schemas.Service, schemas.XmlIntEnums, input, options)
end

function Client:xmlLists(input, options)
    return self:invokeOperation(schemas.Service, schemas.XmlLists, input, options)
end

function Client:xmlMaps(input, options)
    return self:invokeOperation(schemas.Service, schemas.XmlMaps, input, options)
end

function Client:xmlMapsXmlName(input, options)
    return self:invokeOperation(schemas.Service, schemas.XmlMapsXmlName, input, options)
end

function Client:xmlMapWithXmlNamespace(input, options)
    return self:invokeOperation(schemas.Service, schemas.XmlMapWithXmlNamespace, input, options)
end

function Client:xmlNamespaces(input, options)
    return self:invokeOperation(schemas.Service, schemas.XmlNamespaces, input, options)
end

function Client:xmlTimestamps(input, options)
    return self:invokeOperation(schemas.Service, schemas.XmlTimestamps, input, options)
end

function Client:xmlUnions(input, options)
    return self:invokeOperation(schemas.Service, schemas.XmlUnions, input, options)
end

return M
