-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: restXml

local types = require("restxmlprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.restxml")
local protocol = protocol_mod.new()

local service = schema.service({
    id = shape_id.from("aws.protocoltests.restxml", "RestXml"),
    version = "2019-12-16",
    traits = {},
})

describe("HttpRequestWithLabelsAndTimestampFormat request", function()
    it("HttpRequestWithLabelsAndTimestampFormat", function()
        local input = {
            memberEpochSeconds = 1576540098,
            memberHttpDate = 1576540098,
            memberDateTime = 1576540098,
            defaultFormat = 1576540098,
            targetEpochSeconds = 1576540098,
            targetHttpDate = 1576540098,
            targetDateTime = 1576540098,
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restxml", "HttpRequestWithLabelsAndTimestampFormat"),
            input = types.HttpRequestWithLabelsAndTimestampFormatInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "GET", path = "/HttpRequestWithLabelsAndTimestampFormat/{memberEpochSeconds}/{memberHttpDate}/{memberDateTime}/{defaultFormat}/{targetEpochSeconds}/{targetHttpDate}/{targetDateTime}" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("GET", request.method)
        h.assert_url_path(request.url, "/HttpRequestWithLabelsAndTimestampFormat/1576540098/Mon%2C%2016%20Dec%202019%2023%3A48%3A18%20GMT/2019-12-16T23%3A48%3A18Z/2019-12-16T23%3A48%3A18Z/1576540098/Mon%2C%2016%20Dec%202019%2023%3A48%3A18%20GMT/2019-12-16T23%3A48%3A18Z")
        local body_str = h.read_body(request.body)
        assert.is_true(body_str == "" or body_str == nil, "expected empty body")
    end)

end)
