-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: restXml

local types = require("restxmlprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.restxml")
local protocol = protocol_mod.new()

local service = schema.service({
    id = shape_id.from("aws.protocoltests.restxml", "RestXml"),
    version = "2019-12-16",
    traits = {},
})

describe("XmlMapWithXmlNamespace response", function()
    it("RestXmlXmlMapWithXmlNamespace", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/xml",
            },
            body = http.string_reader([[<XmlMapWithXmlNamespaceResponse>
                <KVP xmlns="https://the-member.example.com">
                    <entry>
                        <K xmlns="https://the-key.example.com">a</K>
                        <V xmlns="https://the-value.example.com">A</V>
                    </entry>
                    <entry>
                        <K xmlns="https://the-key.example.com">b</K>
                        <V xmlns="https://the-value.example.com">B</V>
                    </entry>
                </KVP>
            </XmlMapWithXmlNamespaceResponse>]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restxml", "XmlMapWithXmlNamespace"),
            input = schema.new({ type = "structure" }),
            output = types.XmlMapWithXmlNamespaceOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            myMap = {
            a = "A",
            b = "B",
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

end)
