-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: restXml

local types = require("restxmlprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.restxml")
local protocol = protocol_mod.new()

local service = schema.service({
    id = shape_id.from("aws.protocoltests.restxml", "RestXml"),
    version = "2019-12-16",
    traits = {},
})

describe("EmptyInputAndEmptyOutput response", function()
    it("EmptyInputAndEmptyOutput", function()
        local response = {
            status_code = 200,
            headers = {
            },
            body = http.string_reader([[]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restxml", "EmptyInputAndEmptyOutput"),
            input = schema.new({ type = "structure" }),
            output = types.EmptyInputAndEmptyOutputOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
    end)

end)
