-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: restXml

local types = require("restxmlprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.restxml")
local protocol = protocol_mod.new()

local service = schema.service({
    id = shape_id.from("aws.protocoltests.restxml", "RestXml"),
    version = "2019-12-16",
    traits = {},
})

describe("NestedXmlMaps request", function()
    it("NestedXmlMapRequest", function()
        local input = {
            nestedMap = {
            foo = {
            bar = "Bar",
        },
        },
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restxml", "NestedXmlMaps"),
            input = types.NestedXmlMapsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/NestedXmlMaps" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/NestedXmlMaps")
        h.assert_header(request, "Content-Type", "application/xml")
        local body_str = h.read_body(request.body)
        h.assert_xml_eq(body_str, [[<NestedXmlMapsRequest>
            <nestedMap>
                <entry>
                    <key>foo</key>
                    <value>
                        <entry>
                            <key>bar</key>
                            <value>Bar</value>
                        </entry>
                    </value>
                </entry>
            </nestedMap>
        </NestedXmlMapsRequest>]])
    end)

    it("FlatNestedXmlMapRequest", function()
        local input = {
            flatNestedMap = {
            foo = {
            bar = "Bar",
        },
        },
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restxml", "NestedXmlMaps"),
            input = types.NestedXmlMapsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/NestedXmlMaps" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/NestedXmlMaps")
        h.assert_header(request, "Content-Type", "application/xml")
        local body_str = h.read_body(request.body)
        h.assert_xml_eq(body_str, [[<NestedXmlMapsRequest>
            <flatNestedMap>
                <key>foo</key>
                <value>
                    <entry>
                        <key>bar</key>
                        <value>Bar</value>
                    </entry>
                </value>
            </flatNestedMap>
        </NestedXmlMapsRequest>]])
    end)

end)
