-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: restXml

local types = require("restxmlprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.restxml")
local protocol = protocol_mod.new()

local service = schema.service({
    id = shape_id.from("aws.protocoltests.restxml", "RestXml"),
    version = "2019-12-16",
    traits = {},
})

describe("FractionalSeconds response", function()
    it("RestXmlDateTimeWithFractionalSeconds", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/xml",
            },
            body = http.string_reader([[<FractionalSecondsOutput>
                <datetime>2000-01-02T20:34:56.123Z</datetime>
            </FractionalSecondsOutput>
            ]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restxml", "FractionalSeconds"),
            input = schema.new({ type = "structure" }),
            output = types.FractionalSecondsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            datetime = 9.46845296123E8,
        }
        h.assert_deep_eq(output, expected, "output")
    end)

end)
