-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: restXml

local types = require("restxmlprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.restxml")
local protocol = protocol_mod.new()

local service = schema.service({
    id = shape_id.from("aws.protocoltests.restxml", "RestXml"),
    version = "2019-12-16",
    traits = {},
})

describe("XmlTimestamps response", function()
    it("XmlTimestamps", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/xml",
            },
            body = http.string_reader([[<XmlTimestampsResponse>
                <normal>2014-04-29T18:30:38Z</normal>
            </XmlTimestampsResponse>
            ]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restxml", "XmlTimestamps"),
            input = schema.new({ type = "structure" }),
            output = types.XmlTimestampsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            normal = 1398796238,
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("XmlTimestampsWithDateTimeFormat", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/xml",
            },
            body = http.string_reader([[<XmlTimestampsResponse>
                <dateTime>2014-04-29T18:30:38Z</dateTime>
            </XmlTimestampsResponse>
            ]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restxml", "XmlTimestamps"),
            input = schema.new({ type = "structure" }),
            output = types.XmlTimestampsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            dateTime = 1398796238,
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("XmlTimestampsWithDateTimeOnTargetFormat", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/xml",
            },
            body = http.string_reader([[<XmlTimestampsResponse>
                <dateTimeOnTarget>2014-04-29T18:30:38Z</dateTimeOnTarget>
            </XmlTimestampsResponse>
            ]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restxml", "XmlTimestamps"),
            input = schema.new({ type = "structure" }),
            output = types.XmlTimestampsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            dateTimeOnTarget = 1398796238,
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("XmlTimestampsWithEpochSecondsFormat", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/xml",
            },
            body = http.string_reader([[<XmlTimestampsResponse>
                <epochSeconds>1398796238</epochSeconds>
            </XmlTimestampsResponse>
            ]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restxml", "XmlTimestamps"),
            input = schema.new({ type = "structure" }),
            output = types.XmlTimestampsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            epochSeconds = 1398796238,
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("XmlTimestampsWithEpochSecondsOnTargetFormat", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/xml",
            },
            body = http.string_reader([[<XmlTimestampsResponse>
                <epochSecondsOnTarget>1398796238</epochSecondsOnTarget>
            </XmlTimestampsResponse>
            ]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restxml", "XmlTimestamps"),
            input = schema.new({ type = "structure" }),
            output = types.XmlTimestampsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            epochSecondsOnTarget = 1398796238,
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("XmlTimestampsWithHttpDateFormat", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/xml",
            },
            body = http.string_reader([[<XmlTimestampsResponse>
                <httpDate>Tue, 29 Apr 2014 18:30:38 GMT</httpDate>
            </XmlTimestampsResponse>
            ]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restxml", "XmlTimestamps"),
            input = schema.new({ type = "structure" }),
            output = types.XmlTimestampsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            httpDate = 1398796238,
        }
        h.assert_deep_eq(output, expected, "output")
    end)

    it("XmlTimestampsWithHttpDateOnTargetFormat", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/xml",
            },
            body = http.string_reader([[<XmlTimestampsResponse>
                <httpDateOnTarget>Tue, 29 Apr 2014 18:30:38 GMT</httpDateOnTarget>
            </XmlTimestampsResponse>
            ]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restxml", "XmlTimestamps"),
            input = schema.new({ type = "structure" }),
            output = types.XmlTimestampsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            httpDateOnTarget = 1398796238,
        }
        h.assert_deep_eq(output, expected, "output")
    end)

end)
