-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: restXml

local types = require("restxmlprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.restxml")
local protocol = protocol_mod.new()

local service = schema.service({
    id = shape_id.from("aws.protocoltests.restxml", "RestXml"),
    version = "2019-12-16",
    traits = {},
})

describe("XmlEnums response", function()
    it("XmlEnums", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/xml",
            },
            body = http.string_reader([[<XmlEnumsResponse>
                <fooEnum1>Foo</fooEnum1>
                <fooEnum2>0</fooEnum2>
                <fooEnum3>1</fooEnum3>
                <fooEnumList>
                    <member>Foo</member>
                    <member>0</member>
                </fooEnumList>
                <fooEnumSet>
                    <member>Foo</member>
                    <member>0</member>
                </fooEnumSet>
                <fooEnumMap>
                    <entry>
                        <key>hi</key>
                        <value>Foo</value>
                    </entry>
                    <entry>
                        <key>zero</key>
                        <value>0</value>
                    </entry>
                </fooEnumMap>
            </XmlEnumsResponse>
            ]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restxml", "XmlEnums"),
            input = schema.new({ type = "structure" }),
            output = types.XmlEnumsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            fooEnum1 = "Foo",
            fooEnum2 = "0",
            fooEnum3 = "1",
            fooEnumList = {
            "Foo",
            "0",
        },
            fooEnumSet = {
            "Foo",
            "0",
        },
            fooEnumMap = {
            hi = "Foo",
            zero = "0",
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

end)
