-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: restXml

local types = require("restxmlprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.restxml")
local protocol = protocol_mod.new()

local service = schema.service({
    id = shape_id.from("aws.protocoltests.restxml", "RestXml"),
    version = "2019-12-16",
    traits = {},
})

describe("XmlUnions request", function()
    it("XmlUnionsWithStructMember", function()
        local input = {
            unionValue = {
            structValue = {
            stringValue = "string",
            booleanValue = true,
            byteValue = 1,
            shortValue = 2,
            integerValue = 3,
            longValue = 4,
            floatValue = 5.5,
            doubleValue = 6.5,
        },
        },
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restxml", "XmlUnions"),
            input = types.XmlUnionsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "PUT", path = "/XmlUnions" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("PUT", request.method)
        h.assert_url_path(request.url, "/XmlUnions")
        h.assert_header(request, "Content-Type", "application/xml")
        local body_str = h.read_body(request.body)
        h.assert_xml_eq(body_str, [[<XmlUnionsRequest>
            <unionValue>
               <structValue>
                  <stringValue>string</stringValue>
                  <booleanValue>true</booleanValue>
                  <byteValue>1</byteValue>
                  <shortValue>2</shortValue>
                  <integerValue>3</integerValue>
                  <longValue>4</longValue>
                  <floatValue>5.5</floatValue>
                  <doubleValue>6.5</doubleValue>
               </structValue>
            </unionValue>
        </XmlUnionsRequest>
        ]])
    end)

    it("XmlUnionsWithStringMember", function()
        local input = {
            unionValue = {
            stringValue = "some string",
        },
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restxml", "XmlUnions"),
            input = types.XmlUnionsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "PUT", path = "/XmlUnions" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("PUT", request.method)
        h.assert_url_path(request.url, "/XmlUnions")
        h.assert_header(request, "Content-Type", "application/xml")
        local body_str = h.read_body(request.body)
        h.assert_xml_eq(body_str, [[<XmlUnionsRequest>
           <unionValue>
              <stringValue>some string</stringValue>
           </unionValue>
        </XmlUnionsRequest>
        ]])
    end)

    it("XmlUnionsWithBooleanMember", function()
        local input = {
            unionValue = {
            booleanValue = true,
        },
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restxml", "XmlUnions"),
            input = types.XmlUnionsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "PUT", path = "/XmlUnions" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("PUT", request.method)
        h.assert_url_path(request.url, "/XmlUnions")
        h.assert_header(request, "Content-Type", "application/xml")
        local body_str = h.read_body(request.body)
        h.assert_xml_eq(body_str, [[<XmlUnionsRequest>
           <unionValue>
              <booleanValue>true</booleanValue>
           </unionValue>
        </XmlUnionsRequest>
        ]])
    end)

    it("XmlUnionsWithUnionMember", function()
        local input = {
            unionValue = {
            unionValue = {
            booleanValue = true,
        },
        },
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restxml", "XmlUnions"),
            input = types.XmlUnionsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "PUT", path = "/XmlUnions" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("PUT", request.method)
        h.assert_url_path(request.url, "/XmlUnions")
        h.assert_header(request, "Content-Type", "application/xml")
        local body_str = h.read_body(request.body)
        h.assert_xml_eq(body_str, [[<XmlUnionsRequest>
           <unionValue>
              <unionValue>
                 <booleanValue>true</booleanValue>
              </unionValue>
           </unionValue>
        </XmlUnionsRequest>
        ]])
    end)

end)
