-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: restXml

local types = require("restxmlprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.restxml")
local protocol = protocol_mod.new()

local service = schema.service({
    id = shape_id.from("aws.protocoltests.restxml", "RestXml"),
    version = "2019-12-16",
    traits = {},
})

describe("QueryIdempotencyTokenAutoFill request", function()
    it("QueryIdempotencyTokenAutoFill", function()
        local input = {}
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restxml", "QueryIdempotencyTokenAutoFill"),
            input = types.QueryIdempotencyTokenAutoFillInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/QueryIdempotencyTokenAutoFill" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/QueryIdempotencyTokenAutoFill")
        h.assert_query_param(request.url, "token=00000000-0000-4000-8000-000000000000")
        local body_str = h.read_body(request.body)
        assert.is_true(body_str == "" or body_str == nil, "expected empty body")
    end)

    it("QueryIdempotencyTokenAutoFillIsSet", function()
        local input = {
            token = "00000000-0000-4000-8000-000000000000",
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restxml", "QueryIdempotencyTokenAutoFill"),
            input = types.QueryIdempotencyTokenAutoFillInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/QueryIdempotencyTokenAutoFill" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/QueryIdempotencyTokenAutoFill")
        h.assert_query_param(request.url, "token=00000000-0000-4000-8000-000000000000")
        local body_str = h.read_body(request.body)
        assert.is_true(body_str == "" or body_str == nil, "expected empty body")
    end)

end)
