-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: restXml

local types = require("restxmlprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.restxml")
local protocol = protocol_mod.new()

local service = schema.service({
    id = shape_id.from("aws.protocoltests.restxml", "RestXml"),
    version = "2019-12-16",
    traits = {},
})

describe("GreetingWithErrors ComplexError error", function()
    it("ComplexError", function()
        local response = {
            status_code = 403,
            headers = {
                ["Content-Type"] = "application/xml",
                ["X-Header"] = "Header",
            },
            body = http.string_reader([[<ErrorResponse>
               <Error>
                  <Type>Sender</Type>
                  <Code>ComplexError</Code>
                  <Message>Hi</Message>
                  <TopLevel>Top level</TopLevel>
                  <Nested>
                      <Foo>bar</Foo>
                  </Nested>
               </Error>
               <RequestId>foo-id</RequestId>
            </ErrorResponse>
            ]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restxml", "GreetingWithErrors"),
            input = schema.new({ type = "structure" }),
            output = types.ComplexError,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(output, "expected nil output for error response")
        assert.is_not_nil(err, "expected error")
        assert.are.equal("api", err.type)
        assert.is_true(err.code == "ComplexError" or (err.code and err.code:find("ComplexError", 1, true) ~= nil),
            "error code: expected ComplexError, got: " .. tostring(err.code))
    end)

end)
