-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: restXml

local types = require("restxmlprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.restxml")
local protocol = protocol_mod.new()

local service = schema.service({
    id = shape_id.from("aws.protocoltests.restxml", "RestXml"),
    version = "2019-12-16",
    traits = {},
})

describe("XmlLists response", function()
    it("XmlLists", function()
        local response = {
            status_code = 200,
            headers = {
                ["Content-Type"] = "application/xml",
            },
            body = http.string_reader([[<XmlListsResponse>
                <stringList>
                    <member>foo</member>
                    <member>bar</member>
                </stringList>
                <stringSet>
                    <member>foo</member>
                    <member>bar</member>
                </stringSet>
                <integerList>
                    <member>1</member>
                    <member>2</member>
                </integerList>
                <booleanList>
                    <member>true</member>
                    <member>false</member>
                </booleanList>
                <timestampList>
                    <member>2014-04-29T18:30:38Z</member>
                    <member>2014-04-29T18:30:38Z</member>
                </timestampList>
                <enumList>
                    <member>Foo</member>
                    <member>0</member>
                </enumList>
                <intEnumList>
                    <member>1</member>
                    <member>2</member>
                </intEnumList>
                <nestedStringList>
                    <member>
                        <member>foo</member>
                        <member>bar</member>
                    </member>
                    <member>
                        <member>baz</member>
                        <member>qux</member>
                    </member>
                </nestedStringList>
                <renamed>
                    <item>foo</item>
                    <item>bar</item>
                </renamed>
                <flattenedList>hi</flattenedList>
                <flattenedList>bye</flattenedList>
                <customName>yep</customName>
                <customName>nope</customName>
                <flattenedListWithMemberNamespace xmlns="https://xml-member.example.com">a</flattenedListWithMemberNamespace>
                <flattenedListWithMemberNamespace xmlns="https://xml-member.example.com">b</flattenedListWithMemberNamespace>
                <flattenedListWithNamespace>a</flattenedListWithNamespace>
                <flattenedListWithNamespace>b</flattenedListWithNamespace>
                <myStructureList>
                    <item>
                        <value>1</value>
                        <other>2</other>
                    </item>
                    <item>
                        <value>3</value>
                        <other>4</other>
                    </item>
                </myStructureList>
                <flattenedStructureList>
                    <value>5</value>
                    <other>6</other>
                </flattenedStructureList>
                <flattenedStructureList>
                    <value>7</value>
                    <other>8</other>
                </flattenedStructureList>
            </XmlListsResponse>
            ]]),
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restxml", "XmlLists"),
            input = schema.new({ type = "structure" }),
            output = types.XmlListsOutput,
            traits = {},
        })
        local output, err = protocol:deserialize(response, operation)
        assert.is_nil(err, "deserialize error: " .. tostring(err and err.message or err))
        local expected = {
            stringList = {
            "foo",
            "bar",
        },
            stringSet = {
            "foo",
            "bar",
        },
            integerList = {
            1,
            2,
        },
            booleanList = {
            true,
            false,
        },
            timestampList = {
            1398796238,
            1398796238,
        },
            enumList = {
            "Foo",
            "0",
        },
            intEnumList = {
            1,
            2,
        },
            nestedStringList = {
            {
            "foo",
            "bar",
        },
            {
            "baz",
            "qux",
        },
        },
            renamedListMembers = {
            "foo",
            "bar",
        },
            flattenedList = {
            "hi",
            "bye",
        },
            flattenedList2 = {
            "yep",
            "nope",
        },
            flattenedListWithMemberNamespace = {
            "a",
            "b",
        },
            flattenedListWithNamespace = {
            "a",
            "b",
        },
            structureList = {
            {
            a = "1",
            b = "2",
        },
            {
            a = "3",
            b = "4",
        },
        },
            flattenedStructureList = {
            {
            a = "5",
            b = "6",
        },
            {
            a = "7",
            b = "8",
        },
        },
        }
        h.assert_deep_eq(output, expected, "output")
    end)

end)
