-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: restXml

local types = require("restxmlprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.restxml")
local protocol = protocol_mod.new()

local service = schema.service({
    id = shape_id.from("aws.protocoltests.restxml", "RestXml"),
    version = "2019-12-16",
    traits = {},
})

describe("QueryPrecedence request", function()
    it("RestXmlQueryPrecedence", function()
        local input = {
            foo = "named",
            baz = {
            bar = "fromMap",
            qux = "alsoFromMap",
        },
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restxml", "QueryPrecedence"),
            input = types.QueryPrecedenceInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/Precedence" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/Precedence")
        h.assert_query_param(request.url, "bar=named")
        h.assert_query_param(request.url, "qux=alsoFromMap")
        local body_str = h.read_body(request.body)
        assert.is_true(body_str == "" or body_str == nil, "expected empty body")
    end)

end)
