-- Code generated by lua-client-codegen. DO NOT EDIT.

-- Generated protocol test file — do not edit
-- Protocol: restXml

local types = require("restxmlprotocol.schemas")
local schema = require("smithy.schema")
local shape_id = require("smithy.shape_id")
local traits = require("smithy.traits")
local http = require("smithy.http")
local h = require("smithy.testing")
local protocol_mod = require("smithy.protocol.restxml")
local protocol = protocol_mod.new()

local service = schema.service({
    id = shape_id.from("aws.protocoltests.restxml", "RestXml"),
    version = "2019-12-16",
    traits = {},
})

describe("XmlMaps request", function()
    it("XmlMaps", function()
        local input = {
            myMap = {
            foo = {
            hi = "there",
        },
            baz = {
            hi = "bye",
        },
        },
        }
        local operation = schema.operation({
            id = shape_id.from("aws.protocoltests.restxml", "XmlMaps"),
            input = types.XmlMapsInput,
            output = schema.new({ type = "structure" }),
            traits = {
                [traits.HTTP] = { method = "POST", path = "/XmlMaps" },
            },
        })
        local request, err = protocol:serialize(input, service, operation)
        assert.is_nil(err, "serialize error: " .. tostring(err))
        assert.are.equal("POST", request.method)
        h.assert_url_path(request.url, "/XmlMaps")
        h.assert_header(request, "Content-Type", "application/xml")
        local body_str = h.read_body(request.body)
        h.assert_xml_eq(body_str, [[<XmlMapsRequest>
            <myMap>
                <entry>
                    <key>foo</key>
                    <value>
                        <hi>there</hi>
                    </value>
                </entry>
                <entry>
                    <key>baz</key>
                    <value>
                        <hi>bye</hi>
                    </value>
                </entry>
            </myMap>
        </XmlMapsRequest>
        ]])
    end)

end)
